### ISSUE TITLE
leading digit truncated in the 24h timestamp that appears on hover

### ISSUE THREAD

**Issue by ryjm** [tloncorp/landscape-apps#1014]
almost thought it was time for bed

![image.png](https://images.zenhubusercontent.com/633dbccadf81de073e12f57a/670069ab-7464-4532-82e3-ae8c0cff4488)

**Comment by rcrdlbl** [comment]
Can you still reproduce this? I'm unable to, even if i go in and set something to 19:56 as shown in the screenshot.
