### ISSUE TITLE
inputs: disable spellcheck where it makes sense

### ISSUE THREAD

**Issue by rcrdlbl** [tloncorp/landscape-apps#1030]
This is a huge friction point on mobile that's relatively low-lift to fix.

Basically, in inputs such as `ShipSelector` where people are primarily typing planet names or other non-prose content, adding `spellcheck=false` as an attribute prevents autocorrect from running.

This issue is particularly noticeable with planet names due to being human-pronouncable words that can easily be read as a typo by autocorrect, and they contain a dash, giving autocorrect a staggering THREE places to replace an (actually correct) Urbit ID with (grammatically correct) real words while typing one out.

For those curious, the three places autocorrect can fire when typing a planet name are the first half of the planet name, the second half, and the whole thing as a hyphenated word.

**Comment by mrozanski** [comment]
This seems to be there.
I checked the input in Join a Group and New Message.
If it's still an issue in other places feel free to comment and we'll reopen.
