### ISSUE TITLE
chat: unread marking sometimes loops

### ISSUE THREAD

**Issue by arthyn** [tloncorp/landscape-apps#1042]
**Describe the bug**
When you have guess have a single new message marker, marking briefs read seems to send back 

**To Reproduce**
1. Go to a channel
2. Wait for a new message to happen from someone else
3. See unread marker
4. Check console and see constant flow of marking

**Expected behavior**
It should only have to mark unread once

This almost seems like an issue with the backend, but maybe the frontend is causing it by requesting it too many times?

**Comment by arthyn** [comment]
@jamesacklin marking this sev 1 because it basically makes the page nearly unresponsive even on desktop

**Comment by jamesacklin** [comment]
@arthyn Still out there? #1249?
