### ISSUE TITLE
chat: group references that haven't completed finding preview have broken join links

### ISSUE THREAD

**Issue by arthyn** [tloncorp/landscape-apps#1043]
**Describe the bug**
If a subscription takes too long or never comes back, group refs will have a broken join link (possibly go too?)

**To Reproduce**
1. Go to Tlon
2. Click on Watercooler
3. Scroll up to ed's group ref

**Expected behavior**
If the subscription is taking too long we should just link directly to the find groups page with the group flag preloaded or possibly show some kind of status indicator instead of a button.

**Comment by jamesacklin** [comment]
@tomholford For your consideration when solving for #1010, but feel free to address separately
