### ISSUE TITLE
groups: non-admins receiving join request notifications

### ISSUE THREAD

**Issue by rcrdlbl** [tloncorp/landscape-apps#1055]
![Screen Shot 2022-10-31 at 9.21.23 PM.png](https://images.zenhubusercontent.com/62978c3c8908c3c644f74a3d/ee93186c-cdbc-4f6d-8141-3a8f7c05e885)

As a non-admin of this private group, getting a notification for everyone who requests to join:
1. clutters up my notifications with information I can't do anything about
2. gives me probably too much private info on admin actions (wait, you didn't let [name] in? why not?)

**Comment by arthyn** [comment]
I thought Tom fixed this?

**Comment by jamesacklin** [comment]
We missed this one.
