### ISSUE TITLE
chat: .jpeg images not previewing

### ISSUE THREAD

**Issue by rcrdlbl** [tloncorp/landscape-apps#1062]
**Describe the bug, optionally with screenshots**
uploading/pasting an image link to an image with a .jpeg file extension doesn't load an image preview – this is strange as the previews seem to load just fine in galleries.

**To Reproduce**
1. Open a group chat
2. Upload a .jpeg (i was using [this one](https://nyc3.digitaloceanspaces.com/bladee/tocref-ripmyr/2022.11.01..22.53.16-IMG_7941.jpeg))
3. See URL of JPEG and not the image

**Expected behavior**
An image preview loads for .jpeg files, same way as it would for a .jpg file

**Additional context:**
- planet
- self-hosted (digitalocean)
- chrome on macos

**Comment by jamesacklin** [comment]
Fixed by https://github.com/tloncorp/landscape-apps/pull/1059
