### ISSUE TITLE
groups: after clicking into a group invite via notifications, I see no "invite row" in the "find groups" interface

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1067]
**Describe the bug**
I requested (out of band/product) an invite to Tlon's private group in new Groups and successfully received the invite from James in my app notifications. After clicking into the notification, and being brought to the "Find Groups" interface (which shows an invite count of (1) in the sidebar), I see no group invite interface/row:

<img width="1567" alt="Screen Shot 2022-11-02 at 10 06 51 AM" src="https://user-images.githubusercontent.com/1195363/199510538-fbe601e2-df3c-4177-bd4c-8b2b910d5442.png">

**To Reproduce**
1. Ask someone to invite you to a (private?) group in new groups
2. You should receive a new invite in your notifications interface
3. Clicking into the notification should bring you to find groups, where the invite should reside
4. If you see nothing here, you've replicated the bug

**Expected behavior**
After receiving the invite, I expected to be led to an interface where I could accept the group invite

**Additional context:**
- Ship: planet (~fabled-faster)
- Instance type: Tlon-hosted
- MacOS Monterey — 12.6 (21G115)
- Safari — 15.6.1 (17613.3.9.1.16)
- Chromium — Engine Version 106.0.5249.103

**Comment by urcades** [comment]
An additional detail: searching for the group I've been supposedly invited to in "Find Groups" yields no results, i.e. searching for the host of the chat does not display Tlon Corporation

**Comment by tomholford** [comment]
> An additional detail: searching for the group I've been supposedly invited to in "Find Groups" yields no results, i.e. searching for the host of the chat does not display Tlon Corporation

Just ran into this issue too - I think it's when the sig is not included in the search query

**Comment by patosullivan** [comment]
In trying to repro this (haven't been able to) I've encountered a different bug: I can't leave a private group I was invited to. Not sure if it's because the group is hosted on a ~wannec ship and the invite was sent to my planet (on ~binnec).

**Comment by patosullivan** [comment]
> > An additional detail: searching for the group I've been supposedly invited to in "Find Groups" yields no results, i.e. searching for the host of the chat does not display Tlon Corporation
> 
> Just ran into this issue too - I think it's when the sig is not included in the search query

shouldn't be able to search for it without the sig. How'd you get to the search in this instance?

**Comment by arthyn** [comment]
I think I may have found the issue here. When you receive an invite and click join for a private group and the join fails (a separate issue), you will still have a join in progress which hides any new invitations. There's a bit of complexity here that we need to solve around the exact mechanics of what state transitions should happen. And we also need to figure out why trying to add my self to a private group that I've been invited to is failing. Stack trace:

```
%groups: on-agent on wire /gangs/~bollug-worlus/tlon/join/add, %poke-ack
Joining failed
poke-ack
/app/groups/hoon:<[877 7].[921 9]>
/app/groups/hoon:<[873 7].[921 9]>
/app/groups/hoon:<[871 5].[998 7]>
/app/groups/hoon:<[870 5].[998 7]>
/app/groups/hoon:<[682 17].[682 45]>
/app/groups/hoon:<[680 5].[690 7]>
/app/groups/hoon:<[679 5].[690 7]>
/app/groups/hoon:<[677 5].[690 7]>
/app/groups/hoon:<[676 5].[690 7]>
/app/groups/hoon:<[117 13].[117 44]>
/app/groups/hoon:<[117 5].[117 44]>
/app/groups/hoon:<[116 5].[117 44]>
/app/groups/hoon:<[115 5].[117 44]>
/app/groups/hoon:<[114 5].[117 44]>
/app/groups/hoon:<[84 3].[151 5]>
/app/groups/hoon:<[83 3].[151 5]>
/app/groups/hoon:<[48 12].[48 32]>
/app/groups/hoon:<[48 7].[48 32]>
/app/groups/hoon:<[47 5].[49 17]>
/app/groups/hoon:<[46 5].[49 17]>
/sys/vane/gall/hoon:<[1.559 9].[1.559 37]>
```

**Comment by arthyn** [comment]
Another issue, our cancel join button doesn't actually have an equivalent in the backend. We're calling reject which sends an invite decline, but that's only for rejecting an actual invite.
