### ISSUE TITLE
groups: creating a channel with the same flag in different groups causes collision

### ISSUE THREAD

**Issue by tomholford** [tloncorp/landscape-apps#1068]
**To Reproduce**
1. Create a group and a notebook within it, then add a test post
2. Create another group, then a new notebook with the same name as the previous notebook
3. Observe that the post from the first notebook is duplicated in the new notebook
4. Delete the post in the second notebook
5. Observe that the post is gone from the first notebook

**Expected behavior**
Channels should be able to have the same name across multiple different groups

**Additional context:**
This is because we are only considering the channel flag for some state operations and component rendering. Will need to refactor to use a composite key of group flag + channel flag

**Comment by ryjm** [comment]
https://user-images.githubusercontent.com/2065299/199561886-46893d06-72a4-4b5f-8259-0caf4eb71a1d.mov

**Comment by ryjm** [comment]
applies to channels too, so if you make a channel with the name 'general' in two different groups it gets mirrored

**Comment by jamesacklin** [comment]
@liam-fitzgerald Do you have thoughts on how to address this? The team is suggesting using the group name along with the channel name in the `whom` to prevent duplicate entries in the pact.

**Comment by jamesacklin** [comment]
As per @liam-fitzgerald via @arthyn: add an integer - the most straightforward and most-secure thing may be to associate with the group but causes some incompatibility. Maybe we hash the group name? 

@patosullivan feel free to spike a few approaches.
