### ISSUE TITLE
groups: channels not sorting by recency

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1073]
At the moment, channels are sorted statically:

![image.png](https://images.zenhubusercontent.com/6245cc0024d90711bcf4ea06/e98bd5d6-25bb-42c3-9e60-993b49d168b9)

...where posts in the Watercooler (among others) occurred more recently than any new posts in the Tlon Notebook.

This ordering appears to correspond with edits in the Channel Editor.

**Comment by rcrdlbl** [comment]
I might need some help from someone on this, what appears to be happening is `last` on the briefs isn't getting updated properly – i posted in 3 different channels, at 3 different times – their last value is somehow identical
