### ISSUE TITLE
chat: don't produce unread markers for un-replied threads

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1075]
From @rcrdlbl:

At the moment, you currently have to visit every single thread in a Chat channel that has a new message to trigger the automatic "mark read." However, we have no unread markers for the little thread preview, nor do we have any indication that the thread preview you have to click on may be way back in the backscroll of the chat log.

Therefore, we should not mark a chat thread as "unread" unless it's attached to:
(A) a message you posted, or
(B) you've posted in the thread.

This will cease to aggravate everyone's blue-dot-clearing compulsions.

**Comment by arthyn** [comment]
This will likely be difficult because our backend treats all messages including those in threads as the same and the way we calculate unreads works off of that list.

**Comment by rcrdlbl** [comment]
At the very least, we should have an unread indicator on the thread preview
in the chat – which we currently don't have.

**Comment by patosullivan** [comment]
We do have an unread marker for threads now. Is this issue moot?

**Comment by jamesacklin** [comment]
As long as threads I haven't replied to don't produce an unread marker on the channel, then perhaps?

**Comment by arthyn** [comment]
that won't be the case

**Comment by jamesacklin** [comment]
Great, then. Closing, TYFYS o7 etc

**Comment by arthyn** [comment]
oh I meant that they still will produce a "channel" unread

**Comment by jamesacklin** [comment]
Then the bug stands!

**Comment by jamesacklin** [comment]
From userland:

> Feedback from the user side: Messages in threads should not count as "unread" messages, of the kind that produce the "X new messages since Y - Click to View" banner at the top

> Threads are often not relevant for anyone who isn't the OP or the person starting the thread. Anyone who isn't one of those two people will either be directly mentioned, and therefore get a notification, or will see that there's a thread on a message relevant to him while catching up on the backlog of unread messages

> Replies to threads already send direct notifications to anyone mentioned, and anyone who has posted in the thread previously. Likely, no one else cares

**Comment by lukestiles** [comment]
I'm also getting unread threads when I comment on them.

**Comment by jamesacklin** [comment]
@lukestiles I'm a little confused by your comment but I think I know what your mean.

Is the following behavior what you expect?

- Don't mark threads as unread, in general
- ...unless I've replied to it once
- ... but only mark the thread as unread if I haven't seen the first message from another user which immediately follows my latest message in the thread
  - Do not produce unreads if the thread continues on without me

**Comment by lukestiles** [comment]
Apologies for the terse and unhelpful comment. 

When I add to a thread, my addition produces an unread marker for the thread. This does not seem correct to me.

**Comment by jamesacklin** [comment]
Got it -- we are handling that in #1839

**Comment by patosullivan** [comment]
I think we basically shouldn't show unreads for a thread unless you participated in the thread, right?

**Comment by jamesacklin** [comment]
@midsum-salrux @arthyn Relevant to today's discussion.
