### ISSUE TITLE
groups: disconnect not thrown on ship shutdown

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1086]
To reproduce:
1. Open Groups in a browser window
2. Shut your ship down and do not close Groups

Expected behavior:
The disconnect notice in #1058 should appear and attempt to reconnect me.

---

Further steps:
3. Restart your ship with Groups still open

Expected behavior:
I should be reconnected to my now-running ship.

**Comment by arthyn** [comment]
@patosullivan and I paired on this for a bit. We think there's two things we can do to improve this without having to go write the vitals agent yet. Basically we need to use the error count more and also we need to add an onError to our airlock like old groups did.
