### ISSUE TITLE
chat: adding new messages does not pin chat log to bottom

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1095]
A breakout of #965:

As I a) post new messages while b) situated at the "bottom" of the scroll, I'm not "pinned" to the bottom of the scroll — I seemingly jump back in time to the last date separator, which happens on every new message sent (see video)

Screenshots: 

https://user-images.githubusercontent.com/1195363/193628063-299a7988-77d2-4f78-b826-18a6863a8b63.mov

![](https://images.zenhubusercontent.com/6245cc0024d90711bcf4ea06/56d4ea86-a1c3-44d8-8097-ed8ba9f25701)

**Comment by rcrdlbl** [comment]
Can you still replicate this? I've been trying to for a while and can't seem to

**Comment by jamesacklin** [comment]
@rcrdlbl I'm stuck without a Groups 2-running ship at the moment; @patosullivan can you try to reproduce?

**Comment by patosullivan** [comment]
Yep, can't repro this.
