### ISSUE TITLE
talk: clicking the "back" button on a group chat channel on mobile is broken

### ISSUE THREAD

**Issue by patosullivan** [tloncorp/landscape-apps#1125]
**Describe the bug, optionally with screenshots**
If you click the "back" button at the top left from a group chat within talk you will go back to a gray screen.

https://user-images.githubusercontent.com/1221094/201192888-30c6b44e-d6dd-4e20-be23-09e1433398b6.mov

**Comment by rcrdlbl** [comment]
This should be fixed by #1137.

**Comment by tomholford** [comment]
Closed in #1137
