### ISSUE TITLE
talk: new messages generate noisy `ResizeObserver loop completed with undelivered notifications.` error

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1126]
New messages sent to chat appear to consistently create devtools errors:

`ResizeObserver loop completed with undelivered notifications.`:

https://user-images.githubusercontent.com/1195363/201193365-16ea7852-d167-4a57-9025-bf0d6720748f.mov

**To Reproduce**
1. Open DevTools
2. Go to any talk channel
3. Send a plain message
4. Observe devtools' error log
5. If you see the errors, you're reproduced the error

**Expected behavior**

**Additional context:**
- Ship: planet (~fabled-faster)
- Instance type: Tlon-hosted
- MacOS Monterey — 12.6 (21G115)
- Safari — Version 16.0 (17614.1.25.9.10, 17614)
- Chromium — Engine Version 106.0.5249.103

**Comment by tomholford** [comment]
This appears to be a known issue with Webkit / Safari:

https://github.com/microsoft/vscode/issues/135833

Per the linked conversation, seems to be "benign" in that there are no noticeable effects to UX.
