### ISSUE TITLE
talk/notebooks/collections: channel options dropdown requires updates/adherence to spec

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1127]
Currently, the only way to access channel options is to dig within the group's management interfaces. The "options" menu that each channel surfaces only offers a single option for non-admins:

<img width="262" alt="Screenshot 2022-11-10 at 3 33 26 PM" src="https://user-images.githubusercontent.com/1195363/201200193-7ae4c2df-4010-43b7-a4aa-69455ffe98e9.png">

And as of writing, this menu literally does nothing for admins — clicking it yields no dropdown:

https://user-images.githubusercontent.com/1195363/201200374-b9b5f9fc-5f5a-49c1-b5df-d56962031787.mov

As designed, channels of all types are designed to accommodate a standard set of functions in their respective dropdown:

Talk:

<img width="340" alt="Screenshot 2022-11-10 at 3 36 13 PM" src="https://user-images.githubusercontent.com/1195363/201200963-97a42685-6aa3-4c0d-8df2-1b59a9fbbf8e.png">

Notebooks:

<img width="336" alt="Screenshot 2022-11-10 at 3 36 26 PM" src="https://user-images.githubusercontent.com/1195363/201200982-15678edc-753e-4437-ae50-c4c6cdf69a90.png">

Galleries:

<img width="296" alt="Screenshot 2022-11-10 at 3 38 05 PM" src="https://user-images.githubusercontent.com/1195363/201200997-e6763808-c03b-4805-bbd2-ab691fb20fa5.png">

**Comment by jamesacklin** [comment]
@urcades This is great, but channel invitations, channel links, and channel mutes do not exist yet.

What we do have:
- Mark read (for everyone)
- Edit channel (for admins)
- Leave channel (for non-admins)

**Comment by jamesacklin** [comment]
... and in the latest version on `master`, we mark all channels read on enter (either directly or when the new content enters the viewport, as is the case in Chat), so we don't really need the Mark Read option at all.

**Comment by urcades** [comment]
> ... and in the latest version on `master`, we mark all channels read on enter (either directly or when the new content enters the viewport, as is the case in Chat), so we don't really need the Mark Read option at all.

Yes, I do recall us talking about this mechanic in question a while back – I can make the amendments to our spec to account for this – also heard re: the full span of functionality not yet being implemented, just wanted to be sure to capture some of the solves that addressed galen's immediate feedback during our call
