### ISSUE TITLE
talk: threads in DMs don't work as expected on mobile

### ISSUE THREAD

**Issue by patosullivan** [tloncorp/landscape-apps#1130]
OTT, example:
![image](https://user-images.githubusercontent.com/1221094/201204847-13c87b35-1bf7-4068-acbd-d8677d324b8a.png)

**Comment by rcrdlbl** [comment]
is this on binnec or wannec?

**Comment by rcrdlbl** [comment]
I can't replicate this on master

**Comment by tomholford** [comment]
Also unable to repro on master using Brave mobile on iOS 16.1

**Comment by patosullivan** [comment]
Yeah, I can't reproduce anymore either.
