### ISSUE TITLE
groups: channels from other groups sometimes appear in the wrong groups

### ISSUE THREAD

**Issue by ryjm** [tloncorp/landscape-apps#1135]
![image.png](https://images.zenhubusercontent.com/633dbccadf81de073e12f57a/bd436785-4cae-4ae7-98e0-7a84265d0679)

check out the url too - under my group, but with the channel set to bollug

**Comment by ryjm** [comment]
here's how to reproduce it.

https://user-images.githubusercontent.com/2065299/201234791-6e7bf171-4f1b-4350-96c6-6311375d0f5f.mov

**Comment by tomholford** [comment]
Per the example video above, tried to repro by using browser Back button to go to All Channels for another group, then again to a channel within that group. Unable to repro per the attached video

https://user-images.githubusercontent.com/16504501/201583200-846a1248-57ae-402d-9c8c-b086331a52e6.mp4
