### ISSUE TITLE
mobile: emoji picker occluded

### ISSUE THREAD

**Issue by tomholford** [tloncorp/landscape-apps#1154]
![image](https://user-images.githubusercontent.com/16504501/201958838-f14ec822-41d7-4be0-8ecc-cb7ef754230a.png)

Is there a directive to use the native device picker when on mobile?

**Comment by rcrdlbl** [comment]
IIRC we have custom emoji/stickers in the roadmap so we'll be unable to use the native one forever.

**Comment by urcades** [comment]
To Dan's point, we should eventually accommodate for a world in which we're adding additional custom functionality to this picker. In the current desktop implementation, we position the picker popover well, and we should adapt the existing behavior to whatever custom popover picker we implement in the future.

On mobile (web and apps) this gets a little more tricky, but we should essentially do whatever we can to maximize the size of the picker and align our interfaces to device-native patterns. On both iOS and Android, emoji pickers end up taking over or extending the keyboard interface, and end up emanating from the bottom of the screen as an edge-to-edge view:

<img width="727" alt="Screenshot 2022-11-16 at 1 46 54 PM" src="https://user-images.githubusercontent.com/1195363/202266786-9437857d-1dab-46ff-a553-0dc9e79d4a24.png">

I was doing a bit of research and ended up discovering that forcing the default emoji keyboard on mobile OSes [might not be supported](https://stackoverflow.com/questions/37873103/how-to-force-emoji-keyboard-on-input-type-text), so I imagine the next iteration of our selection interface might be abstracted as:

1. Click on the "react" button on a message
2. Open up the device's native mobile keyboard for quickly searching emoji, stack a bottom-anchored, left-edge to right-edge emoji/sticker selection interface directly above the keyboard (see the discord example above)
3. Tapping outside of the selection interface should dismiss it
