### ISSUE TITLE
groups: Inviting a ship to a group yields a "you are currently offline" header

### ISSUE THREAD

**Issue by jtobin** [tloncorp/landscape-apps#1156]
**Describe the bug, optionally with screenshots**
Upon inviting a ship (in this case, a moon) to join a group a "you are currently offline -- reconnect" header appears.

![](https://jtobin.s3-ap-southeast-2.amazonaws.com/Screen-Shot-2022-11-15-20-25-56.92.png)

**To Reproduce**
1. Click the group name and 'Invite People'
2. Invite a ship.
3. The header should appear.

**Expected behavior**
The header shouldn't appear.

**Additional context:**
- Brave on macOS.

**Comment by patosullivan** [comment]
Can't reproduce this one, I think it had to with the way we were detecting disconnects before #1174
