### ISSUE TITLE
groups: Group member doesn't appear in members list

### ISSUE THREAD

**Issue by jtobin** [tloncorp/landscape-apps#1159]
**Describe the bug, optionally with screenshots**
Having successfully joined a group, a ship doesn't appear under the 'Members & Group Info' list.

**To Reproduce**
1. Go through the sequence detailed in #1158.
2. As the ship that has joined, check 'Members & Group Info'.
3. The ship doesn't appear in the list.

**Expected behavior**
The ship should be on the list.

**Additional context:**
- The joiner here is a moon.
- Brave on macOS.

**Comment by patosullivan** [comment]
Can't reproduce this.
