### ISSUE TITLE
talk: joined dms/multi-dms show as unjoined on other devices

### ISSUE THREAD

**Issue by jyng** [tloncorp/landscape-apps#1162]
Take note of the double "Join" from jyng. I believe what happened here is that I had Talk open in Browser Window A and Browser Window B and clicked join for both. 

If I'm making changes and updates in one window they should be updated in the other window.

It looks like application state isn't shared across browser windows?

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/9557907/202021309-942c2ae2-d3c3-4041-b24d-b1a8b0925c35.png">

**Comment by arthyn** [comment]
Going to edit this so it's a little more clear. We don't seem to mark a DM or multi-DM as joined in a way that will prevent it from showing twice
