### ISSUE TITLE
chat: initial thread message occludes scroll window

### ISSUE THREAD

**Issue by arthyn** [tloncorp/landscape-apps#1166]
Large messages that start threads take up too much space leading to a very small scroll window. We should not leave them fixed they should just flow naturally into the chat and maybe have some kind of marker that they're the OP.

**Comment by arthyn** [comment]
@urcades @jamesacklin @jyng would be cool to get some design help here, especially since the thread header has been harped on as looking out of place within the app in addition to the issue above.

**Comment by jamesacklin** [comment]
Observe occlusion:

https://user-images.githubusercontent.com/748181/202268648-0bc3f036-2068-45da-b79c-2abeb859a8b7.mov

**Comment by jamesacklin** [comment]
@urcades Your thoughts?

**Comment by urcades** [comment]
The entire thing should scroll, apart from the header-area itself, essentially replicating the behavior of the primary chat scroll area.

**Comment by urcades** [comment]
Actually, we've essentially laid out how the header for a thread can take form in this frame and the following ones:

https://www.figma.com/file/sCFYLlAGjehlYXUkT2rarg/Product-Handoffs-(Locked)?node-id=1292%3A69199&t=Uh1E0wFGpgLqPkFF-1
