### ISSUE TITLE
talk: daily time demarcation/separators between messages not appearing

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1176]
**Describe the bug, optionally with screenshots**
In a DM with jimmy, I noticed after sending a message **today** that there was no marker being rendered after our last message in the DM, which was sent **yesterday**:

<img width="354" alt="Screenshot 2022-11-16 at 2 42 28 PM" src="https://user-images.githubusercontent.com/1195363/202279036-1e3beee3-2e96-43d7-bb3e-d2994c1b8e34.png">

Refreshing the interface does not seem to prompt a render of the date separator.

**To Reproduce**
1. Go to a DM in which the last response was yesterday, or earlier
2. Type a response and send it
3. If not date separator appears, you've replicated the bug

**Expected behavior**
I expected a visual separator to appear in the message area since the time between messages sent in the chat occurred on different days.

**Additional context:**
- Ship: planet (~tonlur-hidlyn)
- Instance type: Self-hosted (Digital Ocean)

Accessing the above urbit through the following machine, remotely:
- MacOS Ventura — 13.0.1 (22A400)
- Safari — Version 16.1 (18614.2.9.1.12)
- Chromium — Engine Version 106.0.5249.103

**Comment by arthyn** [comment]
I think this specifically happens only with the "join" notices and not regular messages.

**Comment by jamesacklin** [comment]
@urcades Still seeing this?

**Comment by urcades** [comment]
I currently have one more long-running test that requires a full day cycle to confirm I'm no longer seeing the behavior mentioned in this issue — will update when I see some results.
