### ISSUE TITLE
import/heap: links should be stored as the link content type

### ISSUE THREAD

**Issue by arthyn** [tloncorp/landscape-apps#1182]
Currently our migration uses the link content type for heap links, but our current implementation stores them as plain text. We should probably store them as links in general and to increase compatibility with the migration.

**Comment by jamesacklin** [comment]
Duplicate, covered in #1161

**Comment by arthyn** [comment]
well I split this out because it's a frontend only change

**Comment by jamesacklin** [comment]
![image.png](https://images.zenhubusercontent.com/6245cc0024d90711bcf4ea06/9cc0e0f9-600a-4ced-92a2-62ccf80367b9)

Use the `link` type here.
