### ISSUE TITLE
groups/talk: Inter not rendering ligatures, perhaps more

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1190]
**Describe the bug, optionally with screenshots**
It appears that opentype features such as automatic ligatures are not working with some people's groups/talk interfaces:

<img width="258" alt="Screenshot 2022-11-17 at 1 24 38 PM" src="https://user-images.githubusercontent.com/1195363/202528924-85380b8d-6760-46de-856e-aba2ab298c18.png">

**To Reproduce**
1. Go into any groups/talk interface where text can be input + rendered 
2. Type in text representative of an automatic opentype feature (`->` is a good/easy example) and submit it 
3. If the arrow/opentype feature doesn't render properly/fancily, you've replicated the bug 

**Expected behavior**
I essentially expect the full breadth of opentype/typographic features available via Inter to "just work"

**Additional context:**
- Ship: planet (~tonlur-hidlyn)
- Instance type: Self-hosted (Digital Ocean)

Accessing the above urbit through the following machine, remotely:
- MacOS Ventura — 13.0.1 (22A400)
- Safari — Version 16.1 (18614.2.9.1.12)
- Chromium — Engine Version 106.0.5249.103

**Comment by tomholford** [comment]
Same on Linux / Brave

**Comment by arthyn** [comment]
Can't remember but I may have done some subsetting or maybe because we're using the variable width version? idk we can investigate
