### ISSUE TITLE
talk: when the chat input field is focused in a mobile viewport, the header of the channel is pushed upward by the keboard

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1199]
**Describe the bug, optionally with screenshots**
While using Talk and talk channels in Groups on a mobile device, tapping the messaging input field to send a message pushes the header UI outside the boundary of the viewport:

![Screenshot 2022-11-18 at 11 08 36 AM](https://user-images.githubusercontent.com/1195363/202749565-3c36d899-c3c2-4c67-9422-34d26dd4358d.png)

In the image above, note that the keyboard is visible after tapping the text field, and there is no visible header UI on-screen. This is captured even more clearly in this video:

https://user-images.githubusercontent.com/1195363/202750031-164b7049-3c99-4f88-bac6-a8d9a291e546.mp4

**Expected behavior**
We should keep the header UI visible/fixed to the top edge of the chat view, as it surfaces context around where and what a person is communicating about. This is also a general affordance that most, if not all, chat experiences comply with.

**Comment by rcrdlbl** [comment]
@urcades do you know of any *mobile browser-based* chats that do this? I'm having trouble finding one – "keyboard-avoiding nav" is a known Hard Problem to solve on iOS Safari especially

**Comment by patosullivan** [comment]
Can't repro this in android/chrome (brave). Seems to be an iOS specific issue.

**Comment by patosullivan** [comment]
Gonna get a simulator running in xcode and look into it that way.

**Comment by patosullivan** [comment]
ok, I can repro in the simulator.

**Comment by urcades** [comment]
@rcrdlbl off the top of my head — no actually! If it turns out that the lift required to get this behavior down on the web is massive (or there straight up aren't existing patterns for implementing this webwise), we can put it off for later or ignore. It's definitely ideal though.

**Comment by patosullivan** [comment]
Yeah, there does not appear to be a straightforward way to prevent this behavior in safari on mobile.

**Comment by urcades** [comment]
Let's close this for the time being!
