### ISSUE TITLE
chat: sending a message doesn't scroll to bottom sometimes

### ISSUE THREAD

**Issue by arthyn** [tloncorp/landscape-apps#1200]
**Describe the bug, optionally with screenshots**
Sending a message with a `?msg=...` always scrolls to the focused msg and not the bottom.

**To Reproduce**
1. Click a reference link
2. Then try to send a message in the same channel
3. Notice window stays scrolled on previous focused message from ref link.

**Expected behavior**
Window should scroll to bottom when sending a message

**Comment by tomholford** [comment]
Able to repro on master. Also able to do the same without a message selected (no `msg` query param)

**Comment by tomholford** [comment]
This was actually not closed by #1197, working on a fix for this now
