### ISSUE TITLE
groups: clicking into a "notebook comment notification" row in Groups' notification feed errors out

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1213]
**Describe the bug, optionally with screenshots**
When I click into a notification (read or unread) for a notebook comment in Groups, I end up at a loading screen that never resolves. In addition, the devtools console prints out a few errors:

https://user-images.githubusercontent.com/1195363/203131861-8966113a-3dd5-489d-a7d5-c3936246e86d.mov

**To Reproduce**
1. Find a way to receive new notebook comment notifications in your Groups' notifications feed (author a post and ask for comments on it, or comment in an existing post)
2. Allow yourself to accumulate unread notifications
3. Click into a "new comment" notification
4. If you end up with the described issue, you've successfully replicated the bug

**Expected behavior**
While clicking into a notification, I'm expected to be brought directly to the location the notification was triggered from, in this case, a comment in a notebook.

**Additional context:**
- Ship: planet (~tonlur-hidlyn)
- Instance type: Self-hosted (Digital Ocean)

Accessing the above urbit through the following machine, remotely:
- MacOS Ventura — 13.0.1 (22A400)
- Safari — Version 16.1 (18614.2.9.1.12)
- Chromium — Engine Version 106.0.5249.103

**Comment by patosullivan** [comment]
This seems to be caused by the backend sending the wrong ID for the note in bin.topYarn.wer

**Comment by patosullivan** [comment]
@midsum-salrux @liam-fitzgerald @arthyn @ryjm any ideas as to why we're getting the wrong note ID from hark?
