### ISSUE TITLE
groups: clicking on group title shows broken Group Actions menu

### ISSUE THREAD

**Issue by patosullivan** [tloncorp/landscape-apps#1217]
Currently seeing this on master:

![image](https://user-images.githubusercontent.com/1221094/203144179-380d8a34-3aed-4e8a-81ee-e69585f2288b.png)

**Comment by jamesacklin** [comment]
On master, but not on ~binnec yet.

z-index is busted for sidebar dropdowns, @rcrdlbl:
![image](https://user-images.githubusercontent.com/748181/203145809-12b0c8d8-c4ca-4e24-801b-996f23370e67.png)
![image](https://user-images.githubusercontent.com/748181/203145943-426238f5-4f1c-4d86-8aa0-e431457fb9c8.png)
![image](https://user-images.githubusercontent.com/748181/203145974-c0f6b8e2-2920-42b7-a135-8603c6d37a70.png)
