### ISSUE TITLE
invites: I shouldn't be able to invite myself to any group or DM

### ISSUE THREAD

**Issue by patosullivan** [tloncorp/landscape-apps#1227]
OTT

**Comment by jamesacklin** [comment]
I do want a DM with myself as a scratch pad, though...

**Comment by patosullivan** [comment]
Good question. I'm not sure, but I imagine @arthyn would know.

**Comment by arthyn** [comment]
I think we'd have to guard against this, right now this would just loop and keep poking yourself over and over.

**Comment by urcades** [comment]
Closing this issue, it looks like DMing works without breaking things, and it's something we can find utility within (per the related issue #1539)
