### ISSUE TITLE
groups: invites on group creation are unclear

### ISSUE THREAD

**Issue by patosullivan** [tloncorp/landscape-apps#1234]
Create a new group, try to invite another ship, notice that it doesn't send the invite.

**Comment by patosullivan** [comment]
Nevermind, I didn't realize that I needed to hit enter. Seems like we should make that more clear? Also, upon hitting enter, the name doesn't get cleared from the ShipSelector, and actually gets listed twice.

**Comment by arthyn** [comment]
seems like same as #1867 ?

**Comment by jamesacklin** [comment]
Closing as duplicate.
