### ISSUE TITLE
groups: "create group" modal contents overflow container

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1236]
**Describe the bug, optionally with screenshots**

The internal form fields of the "Create New Group" window exceed their container on the right edge:

<img width="559" alt="Screenshot 2022-11-22 at 2 20 18 PM" src="https://user-images.githubusercontent.com/1195363/203403272-25cec4f5-097f-4c65-8301-d13335652006.png">

**Expected behavior**

These fields should be contained within their container as expected, with the regular margins/padding applied for modal windows.

**Additional context:**
- Ship: planet (~tonlur-hidlyn)
- Instance type: Self-hosted (Digital Ocean)

Accessing the above urbit through the following machine, remotely:
- MacOS Ventura — 13.0.1 (22A400)
- Safari — Version 16.1 (18614.2.9.1.12)
- Chromium — Engine Version 106.0.5249.103

**Comment by patosullivan** [comment]
Appears to be an issue specific to safari. Digging into it.
