### ISSUE TITLE
leaving a group and then rejoining messes up permissions with default channels

### ISSUE THREAD

**Issue by arthyn** [tloncorp/landscape-apps#1245]
We don't clear any channel state when leaving a group which is fine I think, but upon rejoining a group that has default channels, when those channels join something about those channels actually existing previously is preventing state from getting updated correctly. We lose the group flag in `perm` at the very least which prevents you from writing to channels.

**Comment by jamesacklin** [comment]
Log from @joemfb: https://pastebin.com/qmHYPYQW
