### ISSUE TITLE
groups: sidebar dividers shown for sections with no joined/visible channels

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/landscape-apps#1252]
**Describe the bug, optionally with screenshots**
Dividers shown for channels that are not visible. Read Only and Admin are the channels in 
Urbit Fan Club

<img width="1592" alt="Screenshot 2022-11-23 at 6 36 30 PM" src="https://user-images.githubusercontent.com/1903610/203600441-8c2a7d37-5a43-4252-98c2-78b55a61a754.png">

**Comment by jamesacklin** [comment]
Only render the sidebar section divider if the the number of joined channels in that section is non-zero.
