### ISSUE TITLE
chat: emoji picker runs off screen

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1253]
Desktop-only.

![image.png](https://images.zenhubusercontent.com/6245cc0024d90711bcf4ea06/a7b92ce2-2734-4556-bac6-7feeb1a8cc7b)

**Comment by rcrdlbl** [comment]
what platform/browser/size are you experiencing this at?

**Comment by jamesacklin** [comment]
Chrome/MacOS.

This is in the initial response stage, in the message actions set of buttons off to the right.

**Comment by rcrdlbl** [comment]
Yep, I haven't been able to replicate with that setup

**Comment by patosullivan** [comment]
I noticed this on mobile view in dev tools on chrome as well.

**Comment by jamesacklin** [comment]
This report comes from userland: 

![image.png](https://images.zenhubusercontent.com/6245cc0024d90711bcf4ea06/6ee32f4c-aa05-47eb-8cfb-718e951fe96f)

Firefox / MacOS

**Comment by rcrdlbl** [comment]
Okay – I seem to be able to replicate this on the current beta branch (I have to set the window to fullscreen width) but am unable to do so going off this repo's master branch; can someone pull master and try to replicate it? I'll keep poking around in the meantime.
