### ISSUE TITLE
talk: refs from the same chat not loading 

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1259]
**Describe the bug, optionally with screenshots**
<img width="264" alt="Screenshot 2022-11-24 at 9 24 47 AM" src="https://user-images.githubusercontent.com/441466/203839689-9a9f8785-c7e0-47da-955d-b1fa5c9ab837.png">

**To Reproduce**
1. Create a new DM in Talk
2. Type text
3. Copy your text using the hover over button for copy ("reference")
4. Paste that reference in the DM
5. See spinner

**Expected behavior**
When pasted you should see the reference like you do in channels in groups.

**Additional context:**
- macOS, Google Chrome

**Comment by patosullivan** [comment]
Yeah, we're going to need a totally different WritReference component for DMs I think.
