### ISSUE TITLE
import: mark non-hosted, non-migrated groups as pending

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1260]
During the OTA, we migrate your hosted groups first, then migrate the groups you're a member of but don't host, then tombstone the data in %graph-store. This will result in data being inaccessible via UI, but we need to inform users that it's not _gone_, just waiting for the host to migrate.

Things to do:
- [ ] Import just the metadata for non-hosted groups
- [ ] Set a flag for this metadata
- [ ] Surface the group name in Groups 2 in the all groups list
- [ ] Treat these groups differently (grayed-out, disabled, popup saying something about how the host hasn't OTA'd yet)

**Comment by liam-fitzgerald** [comment]
This is done in `lf/a-new-age`, needs FE support though

**Comment by arthyn** [comment]
Seen, working on that rn
