### ISSUE TITLE
groups/mobile: chat input v cramped

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1269]
![image.png](https://images.zenhubusercontent.com/6245cc0024d90711bcf4ea06/1caf00ad-df03-46fc-8305-f6b3c71158c3)

**Comment by urcades** [comment]
Hi @jamesacklin — added a few thoughts here:

https://www.figma.com/file/DF5veycqn4Za6dYrMTG85N/2022-Q4-Groups?node-id=1467%3A33807&t=FBZpYISfTJiezgKN-1

Here's an image preview:

<img width="1415" alt="Screenshot 2022-11-29 at 2 39 21 PM" src="https://user-images.githubusercontent.com/1195363/204632036-3c975e7d-d07f-4cec-9f79-ea6c949f0055.png">

Essentially, we could stand to remove the sigil/avatar icon, compress the "send" button into an iconographic representation (up arrow can work here) and potentially think of a way to better consolidate the one "Add" icon we have alongside the "Send" button.

As an added measure, I've expressed before that I feel the always-on formatting bar to be heavy-handed, and I think removing it would declutter the messaging input quite a bit. I understand we want to continue supporting styling of various sorts on mobile, but there are probably better/more compact ways to approach this — the work of rethinking mobile formatting could be captured in a standalone ticket though.
