### ISSUE TITLE
chat: respect code-fencing in messages

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1283]
Chat messages need to parse or understand triple-backtick code-fencing in messages.

![image.png](https://images.zenhubusercontent.com/6245cc0024d90711bcf4ea06/b0785745-7abd-42d0-a1fb-1eae634ce298)

**Comment by urcades** [comment]
Making a note here that we have some existing designs for code-fence message rows here:

https://www.figma.com/file/YLjErBShApNlWpE44nqnbC/Indigo-FW2022?node-id=2157%3A23839&t=wdtai91b9AJSQa7a-1

![Screenshot 2022-11-30 at 1 39 22 PM](https://user-images.githubusercontent.com/1195363/204881229-35926f90-fa40-4e92-bc06-1439f64b5d16.png)

Some markdown formats allow for an additional syntax label after the initial three ticks (ignore backslash):

```css
```css
...some code...
\```
```

And the thinking behind the "Hoon" label in the example above was to provide a visual affordance for indicating what type of syntax is being highlighted, if this is a feature we can easily support. If we're opting for a more simple initial implementation, we can ignore this label. 

The copy button feels like a nice affordance to keep, but again, if we're opting for a simple implementation, we can ignore this element.
