### ISSUE TITLE
groups: "group avatar" corner radii styling is being overridden by `rounded-md`

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1285]
This image illustrates what's going on pretty precisely — basically we're overriding `rounded` radii styling (seen in the user's avatar/sigil) on group avatars with `rounded-md`, which is making them appear a little visually disjointed from how we've intended for left-aligned icons to appear in sidebars universally:

<img width="1470" alt="Screenshot 2022-11-29 at 2 05 33 PM" src="https://user-images.githubusercontent.com/1195363/204623032-dad429c0-6671-4b91-bf25-b6e0c926baf0.png">

We should eliminate the styling overriding here, and ensure that all left-aligned icon boxes / avatars are hewing to the `rounded` styling.

(Now that I have an up to date dev environment locally, I tried to find the source of the override myself but couldn't find it, would appreciate someone also pointing out where I can assess components individually in the source)

**Comment by rcrdlbl** [comment]
components are available in the UI folder of the repo

**Comment by jamesacklin** [comment]
This is likely `SidebarItem`
