### ISSUE TITLE
groups: update to sidebar nav "filter" and "sort" component

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1293]
As we began to explore designs for the standalone notebook and collections apps, we realized that we were hitting some heavy limitations with our present "sort/filter" interface in the sidebar, so we've redesigned it.

Current Filter interface (dropdown selection emits from a row-button):

https://user-images.githubusercontent.com/1195363/204935067-1f39e391-dd35-4b7e-8cb7-6077ac1f19fa.mov

Proposed redesign (dropdown selection emits from an icon-button inlined with the separator label):

https://user-images.githubusercontent.com/1195363/204935110-8bdb4aa7-55f4-48cf-b4d9-b7ed692f2a62.mov

Effectively, this change amounts to moving the "filter/sort" function from the "Row"-like element into the "Separator" element as a right-aligned button, along with a potential "Search-Filter" function we'd like to add at some point.

We surmised this approach is beneficial for the following reasons:

1. This proposed location for the sort/filter button takes up less vertical space in the sidebar
2. The refactoring of the dropdown emanating from a button vs. a row clarifies the distinction between channel rows vs. the sort/filter function
3. The proposed location of the sort/filter button is a little more aligned with the _actual_ state of the separator label text, which changes depending on the currently selected sort. Inlining these two elements binds them closer together

**Comment by urcades** [comment]
The inclusion of a search-filter interface additionally means that we could ship a means of searching for especially long lists of channels or groups:

https://user-images.githubusercontent.com/1195363/204937276-dd78b645-0366-4d1a-94c7-ef88f3ea1fd2.mov

**Comment by jamesacklin** [comment]
@urcades Still relevant, or should I close in favor of another ticket?
