### ISSUE TITLE
apps: protect against host nuking

### ISSUE THREAD

**Issue by arthyn** [tloncorp/landscape-apps#1296]
It seems like we delete channels upon getting an errored watch-ack, but perhaps we should do something different here to guard against a host nuking/breaching/etc? At least so that we don't lose history until taking further action

**Comment by jamesacklin** [comment]
@arthyn Still relevant?

**Comment by arthyn** [comment]
yeah I still think it's worth doing if we can

**Comment by arthyn** [comment]
but very low priority
