### ISSUE TITLE
urbit/garden: late-breaking changes from 417 hotfixes

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1337]
These two commits need to make it over into urbit/garden, via @philipcmonk:

- https://github.com/urbit/urbit/commit/36514b21d436cea1ead92c5f66aa0d7d77781983
- https://github.com/urbit/urbit/commit/44ca16d0e7e74b6e0bb509c3be71d483e67769f1

**Comment by tomholford** [comment]
@jamesacklin Just opened a PR to import the updated block logic from https://github.com/urbit/urbit/commit/36514b21d436cea1ead92c5f66aa0d7d77781983. As for the copy, new grid no longer has this modal dialog.
