### ISSUE TITLE
groups: admin functionality is lost in latest iteration of groups, possible regression

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1341]
**Describe the bug, optionally with screenshots**
It appears as though in the latest pushes made to the apps, group admins have lost the ability to configure their group, or visit its settings page(s). Instead, a group admin can only view the "group info and members" page that ordinary members of the group see instead of the settings pages.

In the following video, I'm the admin of the group I click into:

https://user-images.githubusercontent.com/1195363/206303564-e2ea296e-e95e-4e0e-b431-2ad3bb3a494d.mov

Note that I've lost the ability to configure the group or add new channels to it.

**To Reproduce**
1. In the latest builds of Groups, create a group, or check out one you already admin
2. Attempt to click into your group's settings pages, or "All Channels"
3. If you can't see the appropriate interface, you've replicated the bug

**Expected behavior**
I expect admin functionality to remain intact across the migration.

**Comment by urcades** [comment]
Additional context: I'm seeing this on both `https://sammug-monful.tlon.network` (manually provisioned ship) and `https://tictem-fithul.tlon.network` (tlon hosting provisioned ship) — I've applied teaser + actual OTAs to both ships, and created groups on both ships.

**Comment by jamesacklin** [comment]
Fixed by #1382
