### ISSUE TITLE
notebooks: excessive newline insertion

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1357]
**Describe the bug, optionally with screenshots**
If you write a note that contains a list, save the note, and then re-edit the note. It adds extra new lines.

Sometimes the formatting gets removed, sometimes it won't convert things to a list.

**To Reproduce**
1. Create a note
2. Write things in the note, including lists separated by a new line.
3. Publish and edit the note
4. See formatting issues

**Comment by ixv** [comment]
This doesn't just happen with lists, if you click edit then publish without changing anything all paragraph breaks get an extra newline added to them.
