### ISSUE TITLE
groups: adding a group cover/image is confusing

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1360]
**Describe the bug, optionally with screenshots**
<img width="878" alt="Screenshot 2022-12-08 at 4 38 34 PM" src="https://user-images.githubusercontent.com/441466/206596183-b37eccfb-712a-4950-9be4-6aef89f4937f.png">
- You have to click Add Image to switch the field from color chooser hash to add link (not obvious)
- Then if you paste an image url in the button changes to upload image, but the button you actually need is save at the bottom.
- This flow needs design attention.
- Arguably the secondary icon shouldn't exist at all #1481

**Comment by jamesacklin** [comment]
Addressed in #2455
