### ISSUE TITLE
landscape: notifications don't use ship nicknames

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1361]
**Describe the bug, optionally with screenshots**
<img width="462" alt="Screenshot 2022-12-08 at 4 44 47 PM" src="https://user-images.githubusercontent.com/441466/206596921-05858a9e-7aaf-439e-8c38-c2d266ef9b9f.png">
- Notifications in garden don’t clear after interaction (at least not within any reasonable timeframe/without a full refresh)
- Notifications in garden don't use the nick of the user (this should say galen)

**Comment by zalberico** [comment]
On playing with this further, it looks like they do get marked read once you click one and it loads in a different page.

That feels heavy handed to me - it'd be better to mark read on view?

**Comment by jamesacklin** [comment]
Notifications are now marked read on view and we have a "Mark All as Read" button. 

Will work on getting nicknames in the notifications.
