### ISSUE TITLE
landscape: scrolling down in system preferences the right side scrolls too

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1370]
**Describe the bug, optionally with screenshots**
- Open system preferences and scroll
- Observe the right side scrolling even when it shouldn't
- This hides the content
<img width="569" alt="Screenshot 2022-12-08 at 4 55 51 PM" src="https://user-images.githubusercontent.com/441466/206598406-4d422356-1d6a-43a2-acce-41e32e89f6da.png">

**Comment by jamesacklin** [comment]
Closed by #1420
