### ISSUE TITLE
landscape: clicking sigil when the sigil menu is open doesn't close the menu

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1372]
**Describe the bug, optionally with screenshots**
- On mobile, click the sigil menu
- Try to click the sigil to close the menu
- Observe it doesn't work
- Observe trying to click outside of the menu to close it doesn't work either

**Comment by jamesacklin** [comment]
@zalberico Can you expound on what you mean by "sigil menu?"

**Comment by zalberico** [comment]
![IMG_2200](https://user-images.githubusercontent.com/441466/206600087-a28e2c15-5f91-4f31-b79b-e15ca20298c5.PNG)
