### ISSUE TITLE
landscape: clicking search when in the sys prefs menu zooms in weirdly

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1373]
**Describe the bug, optionally with screenshots**
- On mobile click the sigil menu
- Click the search bar
- Observe it weirdly zooming in

**Comment by jamesacklin** [comment]
@zalberico Which "sigil menu" do you refer to?

**Comment by zalberico** [comment]
![IMG_2200](https://user-images.githubusercontent.com/441466/206600265-bf0b5b3a-c3ef-412d-86b1-b768ed88cf08.PNG)
