### ISSUE TITLE
notebooks: nonsensical comment ordering

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1381]
**Describe the bug, optionally with screenshots**
This is less of a bug and more of a design thing. I think we should default to oldest and remove the option to change the ordering.

<img width="650" alt="Screenshot 2022-12-08 at 5 50 04 PM" src="https://user-images.githubusercontent.com/441466/206605078-ec9a3876-83fb-4d39-a531-a608526e0f75.png">

Often better to just make the good choice for this kind of thing.

**Comment by jamesacklin** [comment]
This is a legit bug -- the idea was to batch individual comments from the same author together such that it emulates a chat thread, but the batching sorts the comments by author, by the time of the first comment from that author. 

The fix here is to intersperse comments from different authors chronologically, then we can play with sort-ordering.
