### ISSUE TITLE
groups: admin edit actions succeed for group members, not reflected in local state

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1386]
**Describe the bug, optionally with screenshots**
As an admin of the Tlon group I changed the group color, to me it didn't look like it worked but others on the call saw the change.

I also tried an incognito browser to see if it was a local cache issue, but I didn't see the change there either.

**Comment by jamesacklin** [comment]
NB: this is for a _non-hosted_ but admin-roled user.

**Comment by ngzax** [comment]
see https://github.com/tloncorp/landscape-apps/issues/1409 for what appears to be same issue.

**Comment by jamesacklin** [comment]
@zalberico Are you still seeing this? Do you have a console log from the browser?

**Comment by zalberico** [comment]
Okay - working on this with @arthyn, if I left the group and rejoined, then got promoted to admin I could see the changes update.

For groups I'm an admin of that I host on my ship it works fine.

Corrina also sees this issue and she didn't run double migrate, so we suspect this affects anyone who was an admin of a group that they don't personally host.

**Comment by zalberico** [comment]
It'd be best if it was possible to ship a fix so people wouldn't have to leave and join the group.

More details:
 - We ran `:groups +dbug [%outgoing %ship ~bitpyx-dildus]`
 - In the broken state it returned no outgoing subscription
 - I left and rejoined the group and things were working
 - I ran the command again `groups +dbug [%outgoing %ship ~bitpyx-dildus]`
 - It returned the following:
```
%groups: on-poke with mark %dbug
>   [ wire=/groups/~bitpyx-dildus/tlon-support/updates
  agnt=[~bitpyx-dildus %groups]
  path=/groups/~bitpyx-dildus/tlon-support/updates/init
  ackd=%.y
]
> :groups +dbug [%outgoing %ship ~bitpyx-dildus]
>=
```

**Comment by zalberico** [comment]
@arthyn and I confirmed that the release on wannec fixed this for me

**Comment by tomholford** [comment]
> @arthyn and I confirmed that the release on wannec fixed this for me

Okay to close this out?

**Comment by arthyn** [comment]
yep!

**Comment by ngzax** [comment]
is this on the network yet? because if it is, i still can't update the setting for the Bookends group. (same host)

**Comment by arthyn** [comment]
@ngzax it is, what's your %groups hash? and can you share what errors if any you see?

**Comment by ngzax** [comment]
not sure what you mean by "hash?" do you mean ~darlur/bookends?

there are no errors. just when i change something, it changes on the page, but then clicking the "save" button does nothing.

Before:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/87197/207984036-a9459b4a-2c27-4463-b584-b5dda7fe7d5b.png">

After:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/87197/207984093-c34d7698-268c-4fc3-ab7d-4e41d8cc14da.png">

Save button is now active, but clicking it does nothing. There is nothing in the dojo either.

**Comment by ngzax** [comment]
i can invite you and make you an admin?

**Comment by arthyn** [comment]
@ngzax sure. I meant the hash shown from running `+vat %groups` sorry

**Comment by ngzax** [comment]
@arthyn : here it is:

> +vat %groups
%groups
  /sys/kelvin:      [%zuse 417]
  base hash:        0v1s.671ih.cnjeq.ep23n.kc28q.umb1l.m8knc.m3ecp.ug6ai.as5cs.iq85j
  %cz hash:         0v1s.671ih.cnjeq.ep23n.kc28q.umb1l.m8knc.m3ecp.ug6ai.as5cs.iq85j
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~sogryp-dister-dozzod-dozzod
  source desk:      %groups
  source aeon:      4
  kids desk:        ~
  pending updates:  ~
::
