### ISSUE TITLE
garden: DM notifications show content, but chat asks me to 'accept incoming dm'

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1387]
**Describe the bug, optionally with screenshots**
<img width="812" alt="Screenshot 2022-12-08 at 9 46 29 PM" src="https://user-images.githubusercontent.com/441466/206633194-c0d3979a-5a1d-4dec-aae0-68ac2c426bb7.png">

I think we should just kill the accept/decline dm workflow - I don't see the value in it.

**Comment by zalberico** [comment]
Also after accepting the dm in talk it seems to have disappeared?

**Comment by zalberico** [comment]
The dm disappear issue might have been due to remigration

**Comment by jamesacklin** [comment]
The fix: if a DM hasn't been accepted, surface a notification that reads "~sampel-palnet has invited you to a DM". The click-through should lead the user to the accept/deny screen.

@zalberico Auto-accepting new DMs isn't implemented yet but tracked in #362 as a user preference.
