### ISSUE TITLE
profile: cannot choose color that begins with 0

### ISSUE THREAD

**Issue by ashelkovnykov** [tloncorp/landscape-apps#1390]
**Describe the bug, optionally with screenshots**
Neither updating my personal profile nor the group profile for a group to which I have admin rights works. After making changes and hitting save, it just hangs indefinitely.

**To Reproduce**
1. Go to profile
2. Make changes
3. Hit save
4. Wait
5. Verbose logs in dojo suggest that some agents received an update, but aren't doing anything with it apparently

**Expected behavior**
Changes to profile are updated and visible.

**Additional context:**
- Ship type = planet, star
- Instance type = self-hosted planet, VPS-hosted star
- Chromium-based browser on Pop!_OS

**Comment by patosullivan** [comment]
Can't repro this one. Anyone else seeing this?

**Comment by rcrdlbl** [comment]
making admin changes to the group may be #1386.

i'm unable to reproduce the user profile part however.
please:
- clear browser cache + refresh
- shut down your ship + restart
- try this again, and either copy/paste or send screenshots of both browser console and dojo

**Comment by jyng** [comment]
![profile-update-error](https://user-images.githubusercontent.com/9557907/206785342-91681eba-8891-4ff4-bf6c-d3a758ffa85d.gif)

**Comment by rcrdlbl** [comment]
hmm – it appears contact-store isn't loading in properly if you can't see your own profile details at all, this is useful thank you

**Comment by ashelkovnykov** [comment]
Update: my error is unlike @jyng and appears to actually be a sigil color-picker error. I think it's a parser error - I'm unable to pick any color which begins with a `0`.

**Comment by philipcmonk** [comment]
Just noticed this today, I can change profile color to anything that doesn't start with 0, but eg `#0000FF` turns into `#FFFFFF`

**Comment by tomholford** [comment]
Able to repro, investigating

<img width="422" alt="image" src="https://user-images.githubusercontent.com/16504501/216256224-c0b5a640-d7c7-45a9-9fda-f2e0c0f36fc6.png">

**Comment by tomholford** [comment]
it looks like the frontend is sending the correct payload as per the previous screenshot; confirming that the agent state reflects the bogus value:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/16504501/216258183-3bc1cd16-71b6-4358-9182-b8fb481e754a.png">

**Comment by tomholford** [comment]
in the frontend, if a color value received in a subscription update is not valid, it is right-padded with `F` by `normalizeUrbitColor`; hence why we see a color "change" after saving it. in other words, poking `{ color: '00f0ff' }` is saved in agent state as `0xf0ff`, then "normalized" to `'f0ffff'`
