### ISSUE TITLE
chat: inline code (`with backticks`) rendering fails when text includes link

### ISSUE THREAD

**Issue by jtobin** [tloncorp/landscape-apps#1391]
Enter some monospace text that contains a link, e.g. `ping https://tlon.io`.  The link rendering will override the monospace.

![](https://jtobin.s3-ap-southeast-2.amazonaws.com/Screen-Shot-2022-12-09-10-56-01.11.png)

**Comment by arthyn** [comment]
Seems to be fixed in latest
