### ISSUE TITLE
chat: missing emoji reactions

### ISSUE THREAD

**Issue by ashelkovnykov** [tloncorp/landscape-apps#1393]
**Describe the bug, optionally with screenshots**
Emoji reactions on other people's posts appear in my chat, but emoji reactions of others to my posts do not render correctly.
[Example 1](https://0x0.st/odJK.png)
[Example 2](https://0x0.st/odJP.png)

**To Reproduce**
1. Make post
2. Have someone else emoji react to it

**Expected behavior**
I should see emojis rendered as I would for any other post

**Additional context:**
- Ship type = planet (comet/moon/planet/star/galaxy)
- Instance type = self-hosted
- Chromium-based browser on Pop!_OS

Poking around in JS console, I think it's that the people reacting to me are using MacOS and their emojis have different names than the ones on my end.

**Comment by jamesacklin** [comment]
@ashelkovnykov You're on Pop!_OS -- do you have `fonts-noto-color-emoji` installed and configured?

**Comment by ashelkovnykov** [comment]
@jamesacklin Yes - though I'm on version 20.10 of Pop!, so maybe there's a newer version of `fonts-noto-color-emoji` out that I don't have?

**Comment by jamesacklin** [comment]
Let me try to repro on fresh Debian. More pressingly, can you check the network console to see if you're getting the `Emoji Mart` webfont?

**Comment by ashelkovnykov** [comment]
Didn't see anything in console or network console about `EmojiMart`. I read online that uninstalling and reinstalling `fonts-noto-color-emoji` and restarting the system sometimes fixes this. I reinstalled the font, but I don't want to restart my system yet as I have my work environment setup how I like it currently. Will restart tomorrow or Sunday to check.

**Comment by ashelkovnykov** [comment]
Did full restart, but it wasn't fixed. However, I believe I've found the problem: I'm using version 20.10 of Pop!_OS, which is limited to an older version of `fonts-noto-color-emoji`, which does not have [Emoji 14 support](https://emojipedia.org/emoji-14.0/).

Closing issue as **won't fix**.
