### ISSUE TITLE
talk: filter by nickname/@p/clubname in messages sidebar

### ISSUE THREAD

**Issue by vcavallo** [tloncorp/landscape-apps#1395]
Would be lovely to have a search bar at the top of Talk (and Small Talk) whereby you could typeahead filter "messages"/channels. In this way you could quickly get to a desired channel/DM without having to scroll.

![image](https://user-images.githubusercontent.com/3201135/206741883-8401e7e6-90e9-47f2-b603-4e9425be9240.png)

**Comment by vcavallo** [comment]
Seems like https://github.com/tloncorp/landscape-apps/pull/1309 would address this

**Comment by rcrdlbl** [comment]
@vcavallo #1293 also directly surfaces this.

**Comment by rcrdlbl** [comment]
closed, resolved in two ways by both #1293 and #1309.

**Comment by jamesacklin** [comment]
@rcrdlbl Thanks, keep these open so I can corral them.

**Comment by rcrdlbl** [comment]
@vcavallo yes!
