### ISSUE TITLE
groups: channel sections aren't visible after loading

### ISSUE THREAD

**Issue by bonbud-macryg** [tloncorp/landscape-apps#1401]
I have a group with the sections Talk, with two chat channels, and Resources, with one links channel. When I click through to this group from the sidebar I don't see those sections at all. When I refresh the page on my planet I [see the Talk section briefly](https://0x0.st/odye.png), then when the Links channel loads [the sections vanish](https://0x0.st/odyj.png).

When I refresh the group from my moon, which hosts the group, [I see both sections](https://0x0.st/odyf.png) before the channel content loads, after which the sections vanish as in the second screenshot linked above.

**Comment by rcrdlbl** [comment]
@bonbud-macryg does setting the sorting to "arranged" bring back the channel arrangement? 

it seems possible to me that you have your sidebar set to sort this group's channels by recent activity and that it's taking a second to load that preference, leading to the brief appearance of the "arranged" view

**Comment by rcrdlbl** [comment]
(just FYI the dropdown above the channel list is a per-user, per-group setting that lets them decide how they want the group's channels to appear)

**Comment by bonbud-macryg** [comment]
Ah, my mistake; in my comment above I might have missed that the drop-down was changing between "arranged" and "recent". That seems to be working correctly.

I was experimenting with this between Safari and Firefox and found no differences. I did notice however that when I access the group on my planet, the Resources section doesn't show up in the Arranged view. It does show up in the Recent and A-Z views, but when I click the channel it's just blank.

* [Clicked Links in A-Z on planet](https://0x0.st/odxN.png)
* [Clicked Links A-Z on moon](https://0x0.st/odxb.png)
* [Arranged view missing Links on planet](https://0x0.st/odxT.png)
* [Arranged view looking correct on moon](https://0x0.st/odxc.png)

Should that be expected, considering the moon hosts the channel and things might still be migrating on my planet, or does that sound like a bug in itself?

**Comment by rcrdlbl** [comment]
@bonbud-macryg 

this looks off – was this group made fresh or migrated from groups 1?

on the ship that's missing the links, open "all channels" and
- make sure that channel is joined
- if it is joined, try leaving and re-joining it

let me know if this fixes the issue

**Comment by bonbud-macryg** [comment]
The group was migrated from Groups 1. The host moon's migration was totally seamless, didn't even have to touch it.

My planet actually can't see the Links channel to leave/join in All Channels. It has admin rights, so I can open the Channel Settings menu and see the channel is there.

* [Planet can't see Links channel in All Channels](https://0x0.st/od6i.png)
* [Planet can see Links channel in Channel Settings](https://0x0.st/od6-.png)

I could try leaving/rejoining the channel from the backend, if someone knows what I'd put in the Terminal to do that.

**Comment by rcrdlbl** [comment]
@bonbud-macryg okay, two more steps:

- change the channel's permissions to "admin only" and back to "open to all" (maybe visibility permissions are somehow stuck in some odd way)
- try having the ship with channel visibility issues leave and rejoin the group

**Comment by bonbud-macryg** [comment]
I actually can't change the channel permissions to "Admin Only". When I select the "Admin Only" setting and hit Done on either the planet with the issues or the host moon, across Safari or Firefox, it stays on "Open to All" for several seconds then changes to "Members Can View". When I changed it back to open it took several seconds to update too.

And I have to access the Edit Channel button from Channel Settings. If I click Edit Channel where it appears in the All Channels menu, I get a blank screen on both Safari and Firefox. This is the case on both the planet and host moon.

* [Blank screen on Safari](https://0x0.st/onrB.png)
* [Blank screen on Firefox](https://0x0.st/onra.png)

Changing to "Members Can View" back to "Open to All" did actually work though. I got a notification on the planet saying "Links has been added to Rosetta Code", and can see the Resources section from my planet now when it's in the Arranged view.

* [Resources section now visible to the planet](https://0x0.st/onrQ.png)

So visibility permissions seem to have something to do with it, though the Links channel was always open to everyone in Groups 1. And my planet was made an admin of this group within minutes of my creating it from the host moon.

**Comment by rcrdlbl** [comment]
@bonbud-macryg

okay, i was immediately able to replicate the "all channels > blank screen" issue, i've opened #1424 to keep this thread focused on the channel visibility issue.

leaving this issue open to see if other team members have ideas about what it could have been

**Comment by rcrdlbl** [comment]
btw, i wasn't able to replicate being unable to set the channel to admin only – which leads me to suspect being unable to set the channel to "admin-only" had something to do with the botched visibility with that channel
