### ISSUE TITLE
talk: Text entry gets wiped when a new message appears (maybe just group DMs)

### ISSUE THREAD

**Issue by vcavallo** [tloncorp/landscape-apps#1404]
**Describe the bug, optionally with screenshots**
When drafting a new message in a group DM, if a new message comes in while you have text in the composition field, your text will disappear.  
~sicdev-pilnup and I have both experienced this in the same group DM. I have _not_ noticed it in one-on-one DMs, but perhaps they just aren't as active.

**To Reproduce**
1. Have a group DM with 3 or more participants
2. Begin typing a message...
3. While typing, have someone else send a message
4. Your composed message will be wiped.

**Expected behavior**
The text you're entering in the composer is never deleted except by you :)

**Additional context:**
- Ship type: planet
- Instance type: hosted on digital ocean VPS
- OS/browser: Brave 1.46.140 Chromium: 108.0.5359.99 (Official Build) (64-bit) on Ubuntu 20.04 focal

**Comment by thelifeandtimes** [comment]
can confirm that @sigilante and myself have experiences this as well. really infuriating.

**Comment by thelifeandtimes** [comment]
@arthyn what do we need to do to get this assigned and fixed? it is a huge issue that totally interrupts the group DM experience and has a drastic negative impact on productivity.

**Comment by jamesacklin** [comment]
@thelifeandtimes We're all back in the office January 3, we'll get it assigned and planned for before then.

**Comment by jamesacklin** [comment]
@thelifeandtimes @vcavallo Due out this week. :)

**Comment by vcavallo** [comment]
I think this was fixed, but I'm noticing it again as of today. regression in latest release? @jamesacklin
