### ISSUE TITLE
chat: attempting to write `[%this ~]` results in aggressive attempts to convert to @p tag.

### ISSUE THREAD

**Issue by rabsef-bicrym** [tloncorp/landscape-apps#1405]
![image](https://user-images.githubusercontent.com/52549148/206786263-f6237002-f2f2-4e53-8030-1d5d2ffed0d2.png)

**Comment by jamesacklin** [comment]
The fix here is to not pop the autocomplete if we are within code-fenced inline or block segments. This is unique to Urbit because we use sigs in Hoon.
