### ISSUE TITLE
chat: endless on peek when looking @ a threaded response

### ISSUE THREAD

**Issue by rabsef-bicrym** [tloncorp/landscape-apps#1406]
When attempting to view a threaded response in UC, I am getting an endless stream of watch and peak alternation between groups and chat. Unclear if this is intended behavior.

<img width="995" alt="image" src="https://user-images.githubusercontent.com/52549148/206786446-e1f6c2ea-7f4e-4ab6-b486-620efa8bf3dd.png">

![image](https://user-images.githubusercontent.com/52549148/206786512-2bf6e1ac-3f2e-4a95-8618-eff5c99c95dd.png)

**Comment by jamesacklin** [comment]
@rabsef-bicrym Thank you, we're confirming our fix for this. We're thinking it'll be an inline thread you run as a two-liner in dojo, but this should quiet things down.

**Comment by patosullivan** [comment]
It is not related to typing [%this ~] in the chatinput

**Comment by rabsef-bicrym** [comment]
No yah - sorry - just noticed it while doing the other action as well.

**Comment by arthyn** [comment]
@jamesacklin this is something different, I'm working on fixing part of this
