### ISSUE TITLE
groups and talk: link format isn't limited to highlighted text

### ISSUE THREAD

**Issue by bonbud-macryg** [tloncorp/landscape-apps#1408]
**Describe the bug, optionally with screenshots**
When I add a link to some text in Groups or Talk, everything I type afterwards is part of the hyperlink. The whole message afterwards is clickable, and if I delete the whole message with backspaces and type a new message, that message is hyperlinked.

![image](https://user-images.githubusercontent.com/101650933/206790503-df9ebf29-01cd-4315-aa50-830342172cdb.png)
![image](https://user-images.githubusercontent.com/101650933/206790602-8fa2daaa-b6c9-4859-8fbd-73dd9e4bcd78.png)

**To Reproduce**
1. Highlight the last word(s) in a draft message in Groups or Talk
2. Add a link with the menu that hovers above the word(s).
3. Continue typing.

**Expected behavior**
Only the text I have highlighted should become a link. Whatever I type next should be normal text. If I highlight the word "foo" and make it a link, the "bar" I add to make it "foobar" should not be link text.

**Additional context:**
- The bug occurs across Safari and Firefox on macOS Ventura.

**Comment by patosullivan** [comment]
probably the same issue as #1391
