### ISSUE TITLE
Ships that double migrated have broken pending state

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1411]
**Describe the bug, optionally with screenshots**
Patrick, Nathan, Hunter, Zach ran `:groups-store %migrate`

Now we're stuck with channels in groups stuck pending when we know they've migrated successfully.

<img width="786" alt="Screenshot 2022-12-09 at 1 24 51 PM" src="https://user-images.githubusercontent.com/441466/206798517-9633ef5f-1f80-4a6c-9107-2e4999b54e45.png">

We confirmed this is isolated to people that ran this command. Galen's ship updated properly once he had the new OTA, but our ships that double migrated did not.

Patrick tried leaving and joining the UC group, but that didn't fix the issue.

**Comment by zalberico** [comment]
@arthyn @midsum-salrux @patosullivan

**Comment by zalberico** [comment]
@liam-fitzgerald while this affects just a couple of us, it'd be really great to have a resolution for this since it's the only thing remaining that has people in a broken state (and requires your knowledge of how the migration works to fix).

**Comment by zalberico** [comment]
@jamesacklin nice - should I see the pending stuff migrate after the new version?

**Comment by zalberico** [comment]
@jamesacklin, @arthyn mentioned this might have been a mistake and isn't actually fixed/working?

**Comment by arthyn** [comment]
it's a similar issue as #1402

**Comment by zalberico** [comment]
I think this is still broken

**Comment by zalberico** [comment]
Yeah I still see UC general and a bunch of others as pending. It's worst for general because it means I can help out with support there.

**Comment by zalberico** [comment]
We have this working on my ship! 🎉 Still need to ship broadly though.

**Comment by hosted-fornet** [comment]
Is an OTA coming to fix this? I still see "Pending Migration" for a number of chats on one ship that I know are migrated (because I am in them on another ship).

**Comment by jamesacklin** [comment]
@hosted-fornet The OTA you wish for is minutes away.

**Comment by hosted-fornet** [comment]
Thank you :pray:
