### ISSUE TITLE
migration: move "My Channels" data from backup to secret group

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1412]
We orphaned My Channels in Groups 1 as part of the migration to Groups 2. However, this group of channels still exists in %graph-store and should not have been tombstoned. Users enjoyed the private note-taking/thought-collecting features My Channels afforded and used Groups as a personal tool for self-organization. Therefore, we must restore everyone's My Channels content in Groups 2 to fully sunset the %landscape desk.

Our current thinking is to issue an OTA to the %landscape desk that:

1. Creates a new Secret Groups 2 group on everyone's ships called "My Channels"
2. Starts %graph-store if it's not running
3. Reaches into %graph-store and gets the My Channels data
4. Creates new channels in the new Groups 2 group and injects the data
5. Shuts %graph-store back down if it wasn't running already

This work is a prerequisite to our desk cleanup (moving %s3-store, orphaning %contact-store, removing the %landscape desk, and renaming %garden to %landscape, all with the help of a kelvin bump).

**Comment by wundrellama** [comment]
I can oddly still see notebooks from "My Channels" in the %studio app, which is actually the only way I have access to the contents of those notebooks.

**Comment by jamesacklin** [comment]
@midsum-salrux has made good progress. He has My Channels channels picked out of all self-hosted channels (which previously included old DMs) and massaged into the right format to run the migration with some of the existing gladio code.

We can expect to see it running locally tomorrow and on the testnet next week.
