### ISSUE TITLE
landscape: groups 1 in sysprefs sidebar, app ordering should be sensical

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1420]
![image](https://user-images.githubusercontent.com/748181/206855373-da0d88d4-8784-4e37-a967-5d9b025e7809.jpeg)

**Comment by zalberico** [comment]
Mostly a duplicate of https://github.com/tloncorp/landscape-apps/issues/1370

**Comment by jamesacklin** [comment]
> Mostly a duplicate of https://github.com/tloncorp/landscape-apps/issues/1370

Partial. Could be rolled into one, wanted to capture anyways
