### ISSUE TITLE
talk: incoming DM says "0 members"

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1421]
**Describe the bug, optionally with screenshots**
<img width="892" alt="Screenshot 2022-12-10 at 8 52 43 AM" src="https://user-images.githubusercontent.com/441466/206866183-ec0a0dde-2746-4982-ae0c-f87e0e1c53dd.png">
<img width="562" alt="Screenshot 2022-12-10 at 8 53 03 AM" src="https://user-images.githubusercontent.com/441466/206866187-48379623-e3aa-44c5-894c-625cb52f8a2e.png">

I have this notification for an incoming dm, then there are a few issues.
- This DM is not possible to find outside of this notification (it's not in the DM list)
- When I click the notification it goes to a DM that says it has zero members
- I'm not sure if DMs I'm sending them are working

**Comment by arthyn** [comment]
closing until we see more
