### ISSUE TITLE
groups: delay in clearing unreads

### ISSUE THREAD

**Issue by tinnus-napbus** [tloncorp/landscape-apps#1426]
**Describe the bug, optionally with screenshots**

It can take up to a few seconds for the unread indicator to disappear after I've viewed the unreads

**To Reproduce**
1. See unread on group
2. open group
3. view channel with unread
4. return to group index
5. still unread for a while

**Expected behavior**
unread indicator should be cleared instantaneously upon viewing channel

**Additional context:**
- Ship type: planet
- Instance type: self-hosted
- OS/browser: qutebrowser & chromium on arch linux64

**Comment by arthyn** [comment]
we need to clear the timer and mark final read on navigation away

**Comment by patosullivan** [comment]
is this related to #1461 @arthyn ? if so, should be fixed in #1490

**Comment by arthyn** [comment]
not related to the X, we set a delay upon seeing the banner after we hide it and the brief doesn't get marked read until that delay finishes. we probably should just call "read" on navigation away.
