### ISSUE TITLE
Inconsistent notification display

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/landscape-apps#1427]
**Describe the bug, optionally with screenshots**
On mobile, Tlon Internal shows as having unread messages in the group list. 

![image](https://user-images.githubusercontent.com/1903610/206944846-1011f8c4-e7ed-49c1-9115-70cbae2c6c46.jpeg)

When I click into the group, no channels have a blue dot indicating an unread message. 

![image](https://user-images.githubusercontent.com/1903610/206945037-5b0d091a-a707-4596-96e8-74dcb996a9a1.png)

**Expected behavior**
I'd expect to see a blue dot on at least one of the channels. 

**Additional context:**
- Ship type - planet
- Instance type - self-hosted on digital ocean
- OS/browser - Chrome on iOS

**Comment by zalberico** [comment]
I don't think this is #1075 - I think the bug here is it requires a hard refresh to see the blue dots appear for the channels.

**Comment by jamesacklin** [comment]
#1426 as well?

**Comment by zalberico** [comment]
I think #1426 is also a different issue
