### ISSUE TITLE
landscape: system preferences sidebar does not extend to bottom of modal

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1440]
**Describe the bug, optionally with screenshots**
In Groups, the sidebar interface in System Preferences does not appear to automatically resize if the vertical height of the viewport is shifted:

![Screenshot 2022-12-12 at 11 50 45 AM](https://user-images.githubusercontent.com/1195363/207106135-8b44ff2f-9afd-4fee-b0df-ef5b12172401.png)

In addition, it appears as though the sidebar and primary page are linked when scrolled:

https://user-images.githubusercontent.com/1195363/207106533-f672b12e-fa1d-4880-b9bd-ba632919d804.mov

**Expected behavior**
1. The sidebar and primary page should have independent scrolls
2. the sidebar's vertical height should fill 100% of the containing interface

**Additional context:**
- Ship: planet (~tonlur-hidlyn)
- Instance type: Self-hosted (Digital Ocean)

Accessing the above urbit through the following machine, remotely:
- MacOS Ventura — 13.0.1 (22A400)
- Safari — Version 16.1 (18614.2.9.1.12)
- Chromium — Engine Version 106.0.5249.103

**Comment by jamesacklin** [comment]
Fixed by urbit/garden#24
