### ISSUE TITLE
groups: mobile group view shows all channels (including unjoined) briefly on initial load

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1443]
**Describe the bug, optionally with screenshots**
![IMG_2203](https://user-images.githubusercontent.com/441466/207126073-7ba0e500-e5c7-4255-9104-fd48b8d24162.jpeg)

You can see channels I'm not in listed there (not just the King Haskell one which is broken due to #1411 , almost all of those are ones I'm not in).

This is on a fresh load, it hangs there for a bit while loading before hiding those channels.

Relatedly, the Groups 1 UX of seeing grayed out unjoined channels in the same list was pretty nice (also how slack, discord, etc. do it)

**Comment by arthyn** [comment]
This may have changed
