### ISSUE TITLE
chat: backtick code block formatting nigh-unusable

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1444]
![Screen Shot 2022-12-12 at 14.05.18 PM.png](https://images.zenhubusercontent.com/6245cc0024d90711bcf4ea06/79ea0eb7-b6a4-47fe-aa36-ec82d34bf3c5)

**Comment by tinnus-napbus** [comment]
the way backticks are swallowed by the input parser is maddening. Especially in dark mode where the difference between the code background and regular background is is 0.0000001% so you can't hardly tell if you're in code mode
