### ISSUE TITLE
Cannot join ~hiddev-dannut/new-hooniverse 

### ISSUE THREAD

**Issue by elizasviel** [tloncorp/landscape-apps#1448]
**Describe the bug, optionally with screenshots**
When ~hiddev-dannut/new-hooniverse is searched in the groups app using the find groups search bar, the results tell me This ship doesn't host any groups

**To Reproduce**
1. Go to groups app
2. Click on find groups
3. Enter "~hiddev-dannut/new-hooniverse"

**Expected behavior**
I expected to be able to join the group

**Additional context:**
- Ship type (comet/moon/planet/star/galaxy) (using a planet)
- Instance type (Tlon-hosted/self-hosted with Port/CLI) (using port)
- OS/browser (Safari on MacOS, Chrome on Windows, Firefox on Linux, etc.)

**Comment by jamesacklin** [comment]
@elizasviel Do you see anything in your browser console or in the dojo when your urbit finds ~hiddev-dannut?

**Comment by elizasviel** [comment]
Yeah, %groups: on-fail with term %watch-not-unique
error in %groups
%watch-not-unique
! subscribe wire not unique
! %groups
! /gangs/index/~hiddev-dannut
! [p=~hiddev-dannut q=%groups]

**Comment by arthyn** [comment]
this means you sent out a watch already. it's likely that ~hiddev-dannut is still experiencing issues from either the migration or from the contact store issue fixed just now.

**Comment by elizasviel** [comment]
ok got it, apparently other people are still able to use this hooniverse group if they were in it so would there be another way to join the group/anything else to try?

**Comment by elizasviel** [comment]
the join request went through, closing this

**Comment by arthyn** [comment]
@jamesacklin we should probably have better ux here even though this went through. I think it'll require some backend rework, but we can make it nicer for sure.
