### ISSUE TITLE
Cannot join channel in newly created group

### ISSUE THREAD

**Issue by belisarius222** [tloncorp/landscape-apps#1452]
**Describe the bug, optionally with screenshots**
I joined a new group, "UF Inturnal", created today as a fallback since the main UF Internal group is inoperable.  There's only one channel (at least I can only see one channel), called "General".  When I click it, I get "subscribe wire not unique" errors in the dojo, but nothing else happens.

I can `|hi ~bitdeg`, the host, instantaneously, so it doesn't seem like an issue of load on the host ship.

Dojo output:
```
%chat: on-poke with mark %flag
out=[acked=%.y path=/chat/~bitdeg/general/updates]
subscribe wire not unique
%chat
/chat/~bitdeg/general/updates
[p=~bitdeg q=%chat]
%chat: on-fail with term %watch-not-unique
error in %chat
%watch-not-unique
! subscribe wire not unique
! %chat
! /chat/~bitdeg/general/updates
! [p=~bitdeg q=%chat]
```

**Comment by belisarius222** [comment]
The fact that `acked=%.y` indicates the join request succeeded on the publisher and my ship heard the ack.  Not sure what that says about where the bug is.

**Comment by arthyn** [comment]
do you get anything doing `:chat +dbug '(~(get by chats) [~bitdeg %general])']` ?

**Comment by belisarius222** [comment]
That command looks malformed:
```
>   dojo: nest-need
[ *
    args
  ?(
    %~
    [   poke
      ?(
        [%bowl %~]
        [%incoming about=?(%~ [%path path=/] [%ship ship=@p] [%term term=@tas] [%wire wire=/])]
        [%outgoing about=?(%~ [%path path=/] [%ship ship=@p] [%term term=@tas] [%wire wire=/])]
        [%state grab=@t]
      )
      %~
    ]
    [what=?(%bowl %state) %~]
  )
  %~
]
>   dojo: nest-have
[[now=@da eny=@uvJ bec=[p=@p q=@tas r=?([%da p=@da] [%tas p=@tas] [%ud p=@ud])]] [@t %~] %~]
> :chat +dbug '(~(get by chats) [~bitdeg %general])'

```

**Comment by belisarius222** [comment]
fortunately I am leet haxxor

```
%chat: on-poke with mark %dbug
>   [ ~
  [ net=[%pub ~]
    remark=[last-read=~2000.1.1 watching=%.n ~]
    log={}
    perm=[writers={} group=[p=~zod q=%$]]
    pact=[wit={} dex={}]
  ]
]
> :chat +dbug state+'(~(get by chats) [~bitdeg %general])'
>=
```

**Comment by arthyn** [comment]
just looks like the bunt, seems like you subscribed for updates but never got the log from the host
