### ISSUE TITLE
Large notebook only displaying 50 posts

### ISSUE THREAD

**Issue by nodreb-borrus** [tloncorp/landscape-apps#1458]
**Describe the bug, optionally with screenshots**
The Main Index channel on Group Discovery is very long, but it is only displaying the latest 50 posts.  I was able to scry the data and see all the posts still exist but were just not being displayed.  I also recreated it locally with a new notebook as described below.  Perhaps a related issue, when I switch the notebook to "Grid" view, only 16 posts are displayed (17 on my local test).

**To Reproduce**
* Create a notebook on a local ship and add over 50 notes
* Refresh the notebook page
* Count there are only 50 and the earliest ones are missing from the bottom 

**Expected behavior**
For the notebook to scroll through an unlimited number of posts like old groups, or perhaps to have some pagination.

**Additional context:**
- Ship type - Moon ~migtus-faster-dozzod-rondev
- Instance type - Self-hosted Docker on Debian 11
- OS/browser - Brave 1.45.118

**Comment by jamesacklin** [comment]
Paginate this and virtualize with virtuoso, please.
