### ISSUE TITLE
Clicking on thread notification on mobile loads blank screen

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/landscape-apps#1460]
**Describe the bug, optionally with screenshots**
After selecting a notification for a thread reply, a blank screen loads. 

**To Reproduce**
1. Create a thread
2. Second ship posts to thread
3. On mobile view and select notification
4. White screen

**Expected behavior**
Load the thread

**Additional context:**
- Ship type - planet
- Instance type - self-hosted on digital ocean
- OS/browser - Chrome on iOS

**Comment by jamesacklin** [comment]
Fixed by #1574
