### ISSUE TITLE
groups: joining a group inconsistent, 30s lag

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1464]
**Describe the bug, optionally with screenshots**

There are a couple issues:
 - If I try to search for the Tlon Public group via the find groups search (searching ~nibset-napwyn), it times out and says no such group exists.
 - If I log into ~nibset-napwyn I can invite ~dovsem-bornyl
 - If I look back at my ship, I see the incoming invite. If I click join it appears to process it.
 - I see a grayed out group in the left bar saying it's joining and might take a while
 - On refresh that group is gone
 - My ship becomes inoperable due to the spam in the dojo below.
 - Both ships are on an up to date azimuth block

```
%groups
/gangs/~nibset-napwyn/tlon/preview
[p=~nibset-napwyn q=%groups]
%groups: on-fail with term %watch-not-unique
error in %groups
%watch-not-unique
! subscribe wire not unique
! %groups
! /gangs/~nibset-napwyn/tlon/preview
! [p=~nibset-napwyn q=%groups]
```

**Comment by zalberico** [comment]
After restarting my ship it at least quieted down, but I still can't join the group.

**Comment by arthyn** [comment]
Any attempt to join a decent size group with history seems to put us in a resubscribe loop to get the group preview, until the host is able to finish responding.

**Comment by midsum-salrux** [comment]
I was able to reproduce this. Another detail: after the failed join, the group appears in your state as a secret group that you run yourself.

```
> :groups +dbug

[ [ %0
      groups
    { [ p=[p=~bitbet-bolbel q=%urbit-community]
          q
        [ [%sub p=~2022.12.13..22.15.45..9c0e load=%.n saga=[%chi ~]]
          fleet={}
          cabals={}
          zones={}
          zone-ord=~
          bloc={}
          channels={}
          imported={}
          cordon=[%open ban=[ships={} ranks={}]]
          secret=%.y
          meta=[title='' description='' image='' cover='']
        ]
      ]
    }
    xeno={}
    shoal={}
  ]
  0
]
```

**Comment by zalberico** [comment]
@arthyn and I took a look at this and it eventually did join, the subscribe loop is a known bug #1464

**Comment by zalberico** [comment]
Ok - we did a full repro of this
 - I left Tlon Hosting Support
 - I invited myself back to Tlon Hosting Support from our infra ship
 - I saw lots of spam in dojo of the type in my first comment
 - I saw an invite come in missing metadata (group took a while to appear)
 - I clicked join
 - The invite went away and then came back again
 - After waiting for ~30s and not clicking the second invite (that had blank info) I was dropped into the group

**Comment by zalberico** [comment]
@jamesacklin I bumped this to severity 1
