### ISSUE TITLE
refs: secret group content can be seen in other groups

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1465]
**Describe the bug, optionally with screenshots**
- I shared a quoted reference from a secret group (Tlon Hosting Support) in the Tlon group.
- I can still see it (weird UX since others can't), Hunter couldn't see it, **but Mark saw it for a split second before it got replaced (for him) with "This content is unavailable to you" which seems bad** (is it just being hidden in the front-end?)
- I tried to share the group link which showed up as "This content is unavailable to you" which is more correct, but still wrong - should probably say something like "This group doesn't have permission to see this content".
<img width="920" alt="Screenshot 2022-12-13 at 10 48 50 AM" src="https://user-images.githubusercontent.com/441466/207419928-8a6e7d1e-658d-43c2-9619-192716f206e4.png">

**Comment by patosullivan** [comment]
The content can only be seen if you're also in the group afaik. I can see it, for instance.

**Comment by zalberico** [comment]
It's weird Mark could see it briefly, that seems wrong.

Even if people in the group can see it, I think there should be some UI for the user to know that only other people in the secret group will be able to see the reference.
