### ISSUE TITLE
groups: profile color picker is not floated (higher z-index) over form fields

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1467]
**Describe the bug, optionally with screenshots**
This might be a safari-only issue, but I'm currently seeing this in the profile editing view:

![Screenshot 2022-12-13 at 1 58 30 PM](https://user-images.githubusercontent.com/1195363/207423231-833e8023-2b9d-45db-b177-ed6dcad35b5f.png)

**To Reproduce**
1. Go to your profile in either Talk or Groups
2. Click on the color picker

**Expected behavior**
I expect the color picker to "hover" or "float" above all other elements on screen, while it is active.

**Additional context:**
- Ship: planet (~tonlur-hidlyn)
- Instance type: Self-hosted (Digital Ocean)

Accessing the above urbit through the following machine, remotely:
- MacOS Ventura — 13.0.1 (22A400)
- Safari — Version 16.1 (18614.2.9.1.12)

**Comment by jamesacklin** [comment]
Fixed by #1436
