### ISSUE TITLE
groups: "secret group" reference element "flashes" or renders in an unexpected manner after being invited to it

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1469]
**Describe the bug, optionally with screenshots**
I had received an invite to a secret group and checked the chat where the original link was posted, only to view a highly buggy reference element in the chat:

https://user-images.githubusercontent.com/1195363/207427273-89ec1adb-fc80-4dc5-b819-9807eb1b7ca2.mov

**To Reproduce**
1. Ask someone to post a reference to a secret group in a channel you are in
2. It shouldn't appear at first
3. Ask the same individual to invite you to the group
4. Stay in the original chat, and see if you witness the "nonexistent" reference turn into the group invite
5. If the invite appears as buggy as it does in my video, you've replicated the issue

**Expected behavior**
There are two issues with the behavior I witnessed:
1. The obvious flashing shouldn't be happening, period
2. The group link appearing as an invite displays the group's privacy status as "public", which is incorrect

***Additional context:**
- Ship: planet (~tonlur-hidlyn)
- Instance type: Self-hosted (Digital Ocean)

Accessing the above urbit through the following machine, remotely:
- MacOS Ventura — 13.0.1 (22A400)
- Safari — Version 16.1 (18614.2.9.1.12)

**Comment by tomholford** [comment]
Was unable to repro the issue mentioned above, but running into another issue. After being invited to and joining the group, the secret group ref is still shown as follow:

![image](https://user-images.githubusercontent.com/16504501/214321926-0f77a41a-14a4-4252-9173-a329b9767091.png)

Further, the group owner who posted the secret group reference is seeing the same. Looking into this

**Comment by tomholford** [comment]
Was not able to repro the issue mentioned above, but did find and fix two other secret groups ref issues (see #1785)
