### ISSUE TITLE
groups: unreads not appearing

### ISSUE THREAD

**Issue by doswyx-famleb** [tloncorp/landscape-apps#1470]
Yesterday I was getting little dots next to the groups to indicate new messages... today I am not getting any dots to show that. 

Also... not sure if related, I have my groups sorted by "recent" and they don't seem to be changing/updating when new messages happen.

**Comment by patosullivan** [comment]
I have noticed that I have to *not* be looking at the groups home screen (the notification screen) in order for new blue dots to appear next to groups in the sidebar. Looking into this.

**Comment by doswyx-famleb** [comment]
Ok so some more information about what I was seeing... maybe it was a user error on my part... or not. I don't know.  

I had my groups open on two computers, one was a desktop Linux using chrome and the other was a macbook using chrome.  It was on the macbook that I wasn't seeing the blue dots and the sort was weird.  My desktop Linux machine was showing the blue dots and sorting in the right order. 

Today I am just on my macbook and seeing the blue dots again... so not sure if it was cause I had it open in two spots?  whereas today I don't have it open on my desktop.

**Comment by patosullivan** [comment]
Interesting

**Comment by patosullivan** [comment]
It also went away for me after closing some tabs.
