### ISSUE TITLE
chat: reactions take several seconds to appear.

### ISSUE THREAD

**Issue by wbsquared** [tloncorp/landscape-apps#1473]
**Describe the bug, optionally with screenshots**
When I do an icon reaction to a posting, it takes several seconds to appear.  This feels klunky.

**Expected behavior**
I am told that I am making a request for optimistic reactions, though I am unfamiliar with that terminology.

I expect reactions to feel instant on the user side.

While we are at it, it is sensible to point out that a similar delay in the disappearance of the 'unread items' dot for several seconds, even after all items have been read, is similarly unsatisfying.

**Additional context:**
- Ship type (comet/moon/planet/star/galaxy)
- Instance type (Tlon-hosted/self-hosted with Port/CLI)
- OS/browser (Safari on MacOS, Chrome on Windows, Firefox on Linux, etc.)

**Comment by vcavallo** [comment]
@wbsquared, in case you're interested in the terminology:

> I am told that I am making a request for optimistic reactions, though I am unfamiliar with that terminology.

"Optimistic" here refers to showing you a result of your in-browser action _immediately_ (and then processing the action that you've just made on the server/urbit afterwards). The opposite is: "I click a button - but I don't see any change - and this action goes to the server, gets processed, and once the result comes back, I finally see it".

So in this case, it seems like the action "click emoji reaction in the browser" gets sent off to your urbit to process and make sure it's stored and whatnot, then once its done you see the emoji pop up.
