### ISSUE TITLE
Groups list is an infinite skeleton loader - Brave browser only

### ISSUE THREAD

**Issue by vcavallo** [tloncorp/landscape-apps#1496]
**Describe the bug, optionally with screenshots**
When I open Groups **in Brave**, the left bar never moves beyond this state:
![image](https://user-images.githubusercontent.com/3201135/207729741-043908ba-e6e1-44e7-addc-11d3aba9beb0.png)

**If I navigate directly to a group, everything works as expected.**

**To Reproduce**
1. Open /apps/groups
2. See the above
3. Wait infinite time
4. Same :)

**Expected behavior**
Groups to load

**Additional context:**
- Planet (~sogrum-savluc)
- VPS hosted on digital ocean
- Brave 1.45.127, Ubuntu 20.04. Does not happen on Firefox

**Comment by vcavallo** [comment]
Update: very strange - after opening in Firefox and having groups load normally, returning to Brave and reloading the page sees groups load normally.

**Comment by jamesacklin** [comment]
If you're self-hosted, that points to the server-side scries finally resolving. Keep an eye on it, I guess.

We're also pushing an update to our internal moons at the moment, so if you're synced as if you were still in the alpha or beta, you might see some strangeness.

**Comment by vcavallo** [comment]
> that points to the server-side scries finally resolving

Seems reasonable, but for the record it was like this for _hours_. and only "unclogged" when opening in Firefox, which I admit makes no sense / is probably a red herring.
