### ISSUE TITLE
groups: channel with custom write permissions now has unclear status

### ISSUE THREAD

**Issue by hocwyn** [tloncorp/landscape-apps#1504]
It appears that the option from Groups1 to have group channels with a manually curated list of contributors has been removed. Perhaps this is intentional.

Even if this is an intentional change to Groups 2, the status of the channel is now unclear. Groups appears to think it is "Open to all, Anyone can read and write". Nonetheless only I, the group creator, can post. The members who previously had permissions cannot post. The other group admin, ~habsul-rignyr, cannot post (as he should be able to if the settings were "Members can view" or "Admin only"). Neither does he have the option to change the channel permissions.

<img width="1615" alt="Screen Shot 2022-12-14 at 11 48 47 PM" src="https://user-images.githubusercontent.com/98130722/207776646-89788749-5496-46d8-adb0-b6cdd82eb81f.png">
<img width="1606" alt="Screen Shot 2022-12-14 at 11 56 20 PM" src="https://user-images.githubusercontent.com/98130722/207776673-2671c05f-b064-4d27-bf85-5920c0d255c3.png">

I have not yet attempted to flip the permissions around. I'd like an explanation of the bug, and whether custom permissions will ever be restored. (I don't want to wipe out the channel whitelist if it still exists and will function in the future)

The channel in question is ~hocwyn-tipwex/uqbar-event-horizon-forever/channels/chat/~hocwyn-tipwex/vip-lounge-948

**Comment by jamesacklin** [comment]
@hocwyn Looking into the post-migration presence of the writers whitelist, will update here when I have an answer. 

The workaround for the time being is to make these channels admin-write only and assign the writers admin rights. I realize this likely isn't nearly granular enough, we plan on implementing more granular per-channel permissions in the near future.

**Comment by hocwyn** [comment]
Ty James

**Comment by arthyn** [comment]
@hocwyn can you send over the output of `:groups +dbug [%state 'fleet:+:(~(got by groups) [~hocwyn-tipwex %uqbar-event-horizon-forever])']`

**Comment by hocwyn** [comment]
<img width="841" alt="Screen Shot 2023-01-06 at 1 29 19 PM" src="https://user-images.githubusercontent.com/98130722/211075914-f09d6af2-df22-4134-b929-7824dd330230.png">
<img width="900" alt="Screen Shot 2023-01-06 at 1 32 36 PM" src="https://user-images.githubusercontent.com/98130722/211076167-5ce65d10-d596-4bbe-bf48-0af78cfb8883.png">

**Comment by arthyn** [comment]
Thanks, it's hard to tell because I think webterm cut some of the output. There should be more members than that right? Of those listed, should any of those have custom permissions like you were talking about?

**Comment by hocwyn** [comment]
Yeah that  list of \@p's looks like maybe 40 members of the general Uqbar group, including around 5 who were in the VIP lounge. Uqbar group has 600 users total and of those maybe 50 were in the VIP lounge. 

So that list doesn't represent the full membership of any group/channel, as far as I know. Is that what the command was supposed to output?

**Comment by jamesacklin** [comment]
Fixed in v3.4.0; we now allow for custom roles and per-channel permissions.
