### ISSUE TITLE
talk: new, unjoined multi-DMs don’t appear in sidebar

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1505]
**Describe the bug, optionally with screenshots**
When I create a multi-party dm, it disappears until at least one member accepts it.

I think defaulting to requiring accepting dms is bad and we should have the default be accept, but even with that - I should still see it even before others have joined.

**Comment by jamesacklin** [comment]
> disappears
What means? From the sidebar?

**Comment by zalberico** [comment]
Yeah, I can't find it after creating it and before someone else joins (once I navigate away from the chat).

**Comment by arthyn** [comment]
Seems like it gets punted to the bottom of the list

**Comment by zalberico** [comment]
I thought I didn't see it there, either but possible I missed it or didn't load/refresh. Having it at the top of the list would be good though since I just created it.
