### ISSUE TITLE
notebooks: can't update header of pre-migration post

### ISSUE THREAD

**Issue by vvisigoth** [tloncorp/landscape-apps#1522]
**Describe the bug, optionally with screenshots**
When I try to add a banner to a post (which existed pre migration) I get this Error.
```
/app/diary/hoon:<[785 5].[790 12]>
/app/diary/hoon:<[784 5].[790 12]>
/app/diary/hoon:<[198 13].[198 43]>
/app/diary/hoon:<[198 5].[198 43]>
/app/diary/hoon:<[196 5].[198 43]>
/app/diary/hoon:<[195 5].[198 43]>
/app/diary/hoon:<[194 5].[198 43]>
/app/diary/hoon:<[167 3].[203 5]>
/app/diary/hoon:<[166 7].[203 5]>
/app/diary/hoon:<[166 3].[244 5]>
/app/diary/hoon:<[51 12].[51 32]>
/app/diary/hoon:<[51 7].[51 32]>
/app/diary/hoon:<[50 5].[52 17]>
/app/diary/hoon:<[49 5].[52 17]>
/sys/vane/gall/hoon:<[1.239 9].[1.239 37]>
```

**To Reproduce**
1. Go to an existing notebook post
2. Click Edit
3. Try to either upload or insert URL in banner form
4. Press submit
5. Error

**Expected behavior**
Banner updates and saves.

**Comment by arthyn** [comment]
@vvisigoth that line points to you not having write permissions. we just pushed a fix that makes admins able to override any permissions so if you are one you should be able to change it now, but there may be some custom permissions still there from the migration. You can reset them if you want using the notes in #1571

**Comment by arthyn** [comment]
This should be resolved once you follow the steps above, let us know if it isn't.
