### ISSUE TITLE
chat: notified for one's own messages

### ISSUE THREAD

**Issue by tomholford** [tloncorp/landscape-apps#1525]
Have seen this mostly when switching between mobile <--> desktop, but just experienced this when posting a reply to a thread, switching to another group and channel, then switching back. Upon return, it showed as a new message

![image](https://user-images.githubusercontent.com/16504501/207959746-583210f9-9425-41f2-812a-775ab292092d.png)

**Comment by rcrdlbl** [comment]
i think we should mark the channel as read upon posting a message

as much as i hate to be "okay but discord + slack do it this way"

discord + slack do also do it this way

**Comment by jamesacklin** [comment]
@rcrdlbl Fine by me!
