### ISSUE TITLE
groups + talk: layout gets stuck in responsive-small mode

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1529]
**Describe the bug, optionally with screenshots**
- Be in Talk on desktop
- Make the window narrow until it switches to the mobile view
- Observe making the window wide won't switch back without a hard refresh

**Comment by jamesacklin** [comment]
A bigger issue -- our media query listeners aren't continuously listening to the window size. @arthyn suspected he fixed but this also happens with theming.

We should look at which of these layout bugs occur as a result of Tailwind class names and which come from useIsMobile hook (which aren't as performant).
