### ISSUE TITLE
talk: DMing yourself doesn't work

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1539]
**Describe the bug, optionally with screenshots**
- Send a DM to yourself
- Observe lots of spam in the dojo and never seeing the message

Sending messages to yourself is a common behavior in other apps to test formatting and keep reminders, users will probably do it and we should probably support it in some form (or at least not break).

I was specifically trying to do it in order to paste an image in there to get it in s3 and get the link for it easily to use as a group cover image. This was for an infra ship that didn't have s3 so required a link. The link workflow for group images also worries me a bit - are these just hotlinks to random websites?

**Comment by zalberico** [comment]
It'd be cool if the front-end recognized this and maybe did something else? Whatever my channels becomes when it migrates may be a good candidate?

**Comment by tomholford** [comment]
> Apparently this isn't supported by the back-ends and should be guarded against for the time being. @patosullivan has details on why it's not possible at the moment.

@patosullivan What are the details? Considering taking this one on

**Comment by patosullivan** [comment]
Tbh I don't recall what I would have said exactly here. Off the top of my head: dms are ship to ship, so that could be the root of the issue.

**Comment by jamesacklin** [comment]
IIRC it would start a self-acking loop that was impossible to break.

**Comment by patosullivan** [comment]
> IIRC it would start a self-acking loop that was impossible to break.

That sounds right

**Comment by urcades** [comment]
This is related to #1227 — right now it appears that I can DM myself successfully:

<img width="1540" alt="Screenshot 2023-04-28 at 3 33 11 AM" src="https://user-images.githubusercontent.com/1195363/235084051-e29056d4-dc23-4b5a-9a06-ef27ba392dfb.png">

Closing
