### ISSUE TITLE
talk: starting a new DM with existing DMee with should navigate there

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1540]
**Describe the bug, optionally with screenshots**
If you search a patp to dm someone you already have a dm with, it finds the patp and once you enter text on the blank screen it brings you to your existing one.

If your existing one is already in your sidebar, it should bring you there as soon as you search the patp.

**Comment by zalberico** [comment]
There's a little bit to think through with this - since if you immediately navigate there and remove the view to add more participants it can miss the following case:
 - I have an existing DM with James
 - I'm trying to create a new multi-party DM with James and Hunter
 - I type James' planet in the field and hit enter
 - I'm immediately moved to the DM and can't add Hunter/create the multi-party dm now

**Comment by arthyn** [comment]
I'm a little confused this seems to work as is.

**Comment by jamesacklin** [comment]
...perhaps too well, considering #1704
