### ISSUE TITLE
groups: host shows existing members as pending

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1553]
**Describe the bug, optionally with screenshots**
<img width="708" alt="Screenshot 2022-12-16 at 11 11 27 AM" src="https://user-images.githubusercontent.com/441466/208171546-c8d75103-01c9-4c3d-b687-e4dd37ffefe8.png">

Marisa is in the tlon group, but the host (dabben-larbet) shows her as pending.

**Comment by zalberico** [comment]
This can be seen by an admin in the Tlon group if you look at the member list.

**Comment by zalberico** [comment]
Weirdly, canceling the invites for bitbet and dopzod moved them to the members list.

My guess is it failed to update the true state when the invite was accepted, but it does when I hit cancel.

**Comment by zalberico** [comment]
I 'canceled' the others and saw the same behavior.

**Comment by arthyn** [comment]
have we seen this since?

**Comment by jamesacklin** [comment]
Possibly related to #1158, probably just some bad filtering in the pending members manager component or further up the tree in the query.

@dantish Feel free to escalate with @arthyn if it seems like the problem is in the groups back-end.
