### ISSUE TITLE
groups: hard to know who hosts an unmigrated channel if it's a moon

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1558]
**Describe the bug, optionally with screenshots**
<img width="460" alt="Screenshot 2022-12-16 at 11 32 14 AM" src="https://user-images.githubusercontent.com/441466/208174915-195084d5-3262-49f5-8d91-098d287635b7.png">

**Comment by jamesacklin** [comment]
Show the full @p in the ShipName tooltip.
