### ISSUE TITLE
gallery/notebooks: mentions triggered with `~` do not appear to work in comments

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1562]
**Describe the bug, optionally with screenshots**
It appears as though sig-mentions do not work in comment fields for both Gallery and Notebook channels:

https://user-images.githubusercontent.com/1195363/208191281-737cd1ad-4738-45e9-a9b3-60bc0dd3a53b.mov

**To Reproduce**
- Click into any Gallery or Notebook you have comment access to
- Make a comment, and try to use `~` to invoke a mention in the comment field
- If a mention does not form, you've successfully replicated the lack of mentions

**Expected behavior**
Mentions should function in any communications input, which includes comments on notebook posts or gallery items.

**Additional context:**
- Ship: planet (~tonlur-hidlyn)
- Instance type: Self-hosted (Digital Ocean)

Accessing the above urbit through the following machine, remotely:
- MacOS Ventura — 13.0.1 (22A400)
- Safari — Version 16.1 (18614.2.9.1.12)

**Comment by jamesacklin** [comment]
Expected, but relevant

**Comment by jamesacklin** [comment]
This works now, but does not produce a notification.

![image](https://user-images.githubusercontent.com/748181/226487957-c0e9d0b2-ee48-418c-83d4-01b27361179d.png)
