### ISSUE TITLE
chat: appending an exclamation to tilde-prefixed text prevents post

### ISSUE THREAD

**Issue by jtobin** [tloncorp/landscape-apps#1563]
**Describe the bug, optionally with screenshots**
Typing a patp or ~any-text-like-this and appending an exclamation mark to it will prevent 'return' from submitting a post.

**To Reproduce**
1. In a channel, type `~message!` in the input field.
2. Press return.

**Expected behavior**
The message '~message!' should immediately post.

**Additional context:**
- Brave on macOS

**Comment by jamesacklin** [comment]
@jtobin Did you see this in Chat channels and DMs, or other places too?

**Comment by jtobin** [comment]
IIRC it was in a chat channel, but I just confirmed that it occurs in DM's in Talk as well.
