### ISSUE TITLE
talk: need to repeatedly accept group dm `invite`

### ISSUE THREAD

**Issue by rabsef-bicrym** [tloncorp/landscape-apps#1565]
![image](https://user-images.githubusercontent.com/52549148/208216597-f5678d55-610e-4926-920c-626b06b0c4d5.png)

`%talk` hash `0vc.9kn8n.68vo6.v4e7g.4mou1.ekqeg.65ttj.avtlg.02t5l.dts7e.qjfk1` still asking me to accept same group DM roughly every time I open it. This was resolved for a day or so and then re-occurred.

**Comment by rabsef-bicrym** [comment]
for reference, the pinned chat is the same chat as the `?` chat, which I've been in, accepted, and seen many times.

**Comment by arthyn** [comment]
this is due to local storage we need to remove these from saving
