### ISSUE TITLE
intermittently experiencing on-peek ddos 

### ISSUE THREAD

**Issue by thelifeandtimes** [tloncorp/landscape-apps#1568]
**Describe the bug, optionally with screenshots**
I am still getting hit by the `on-peek` ddos/spam issue. It was fixed for a few days, but now is coming back with a vengeance. If there is a manual fix to this (such as moving these groups off my main planet or other similar options, I am not against it, but of course a proper fix would be preferable.

Seems like it is related to https://github.com/tloncorp/landscape-apps/issues/1442 but was not fixed by https://github.com/urbit/urbit/pull/6150...

**To Reproduce**
1. Be on the network for a while, host a variety of groups and group dms directly on your planet.
2. have Tlon do dope overhaul to Groups application so that it is way sicker
3. ???
4. See tons of dojo `on-peek` spam that makes the performance of your ship so bad as to be unusable.
```
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.9.17..06.47.08
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.7.28..04.52.15
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.4.19..20.03.27
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.5.04..04.51.32
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.4.14..06.25.11
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.11.30..17.26.51
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.9.14..18.14.55
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.8.10..04.56.24
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.8.26..22.31.28
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.10.24..18.23.07
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/self
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/human-scale-business
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.7.26..23.01.50
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.10.18..21.18.58
```
Printing at ~20 lines per second.

**Expected behavior**
No dojo spam, fast and snappy performance that occurs when this is not hitting my dojo.

**Additional context:**
- Ship type: planet
- Instance type: self-hosted, Vere v1.13
- OS/browser: experiencing on Safari on iOS, Brave on MacOS, and within Realm.

**Comment by jamesacklin** [comment]
@thelifeandtimes Can you confirm your base hashes via +vats for %landscape and %groups?

**Comment by thelifeandtimes** [comment]
```
> +vat %landscape
%landscape
  /sys/kelvin:      [%zuse 417]
  base hash:        0vp.llhuf.pg57r.5piau.ea5hr.pq5ct.b79c0.3q6hl.g0n6o.n5jlu.jq6nu
  %cz hash:         0vp.llhuf.pg57r.5piau.ea5hr.pq5ct.b79c0.3q6hl.g0n6o.n5jlu.jq6nu
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~lander-dister-dozzod-dozzod]
  updates:          remote
  source ship:      ~lander-dister-dozzod-dozzod
  source desk:      %landscape
  source aeon:      33
  kids desk:        ~
  pending updates:  ~
::
> +vat %base
%base
  /sys/kelvin:      [%zuse 417]
  base hash:        0v1r.0fp5a.98elp.votc5.3ne9d.aei0r.0k1pm.dr69j.iukr2.067p8.2ucn6
  %cz hash:         0v1r.0fp5a.98elp.votc5.3ne9d.aei0r.0k1pm.dr69j.iukr2.067p8.2ucn6
  app status:       running
  force on:         ~[[%dbug %.y]]
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~sartyr
  source desk:      %kids
  source aeon:      14
  kids desk:        %kids
  pending updates:  ~
::
```

**Comment by thelifeandtimes** [comment]
@jamesacklin this seems to have died down; its it because other ships have given up trying to reach me, or has a fix come through for this?

**Comment by jamesacklin** [comment]
You may have finally gotten the fix. I was able to |hi your ship on-network.

@arthyn Is ~4 days expected for the OTA to sneak its way through the loop?

**Comment by thelifeandtimes** [comment]
my desk hashes remain the same as what was listed above, just ftr.

**Comment by jamesacklin** [comment]
Got it, thanks. I believe this was Groups-side; we released `qhhae` late Friday.

**Comment by thelifeandtimes** [comment]
Groups `+vat` output:
```
> +vat %groups
%groups
  /sys/kelvin:      [%zuse 417]
  base hash:        0v12.2omn2.q86go.5dtu8.229kp.fl360.c15kg.vs41k.11e15.3lfec.3shua
  %cz hash:         0v12.2omn2.q86go.5dtu8.229kp.fl360.c15kg.vs41k.11e15.3lfec.3shua
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~sogryp-dister-dozzod-dozzod
  source desk:      %groups
  source aeon:      5
  kids desk:        ~
  pending updates:  ~
::
```

**Comment by arthyn** [comment]
The person spamming you likely needed to get the upgrade first so if their update was delayed that could have been it.

**Comment by thelifeandtimes** [comment]
got it. is there a way to figure out who the spam is coming from? in the future would be helpful for that info to be included in dojo prints.

**Comment by arthyn** [comment]
So the library that prints all this stuff is called verb and as is currently doesn't show which patps things are coming from. It should though. It comes from the kernel so we should just have them change it.

**Comment by thelifeandtimes** [comment]
yup, understood. @belisarius222 perhaps that might be a worthy grant for a new contributor?
