### ISSUE TITLE
Copy and pasting images doesn't work in Talk

### ISSUE THREAD

**Issue by vvisigoth** [tloncorp/landscape-apps#1569]
**Describe the bug, optionally with screenshots**
I copy and paste an image and it just inserts a bad url at "image.png." Seems like it's being uploaded but the url formatting that is inserted is wrong.

![image](https://user-images.githubusercontent.com/1609955/208484996-79fa929f-eb18-4601-803e-ede4a799d7ed.png)

**Comment by vvisigoth** [comment]
SEems to also be broken with normal image uploading.

**Comment by tomholford** [comment]
Thanks for flagging @vvisigoth , can you share more information: what is the expected URL, and what is actually being published?

**Comment by tomholford** [comment]
Followed up with @vvisigoth out of band, confirming that this now works for him after the s3 update (https://github.com/urbit/urbit/pull/6187)
