### ISSUE TITLE
Failed to fetch dynamically imported module: http://100.119.134.30/apps/escape/assets/DiaryAddNote.4dd1650c.js

### ISSUE THREAD

**Issue by bjokthomPersonal** [tloncorp/landscape-apps#1570]
```
TypeError: Failed to fetch dynamically imported module: http://100.119.134.30/apps/escape/assets/DiaryAddNote.4dd1650c.js
```
Error prevented me from editing a notebook entry

**Comment by jamesacklin** [comment]
Is this bug with Escape or Groups?

**Comment by bjokthomPersonal** [comment]
It's escape.

Can I provide anything more? I reacted to the error-message prompting me to
send this.



tir. 20. dec. 2022 13.18 skrev james acklin ***@***.***>:

**Comment by jamesacklin** [comment]
Understood, Escape is a fork of Groups that may or may not be behind on commits from the Groups repository (this one).

Have you tried the same action in Groups?

**Comment by bjokthomPersonal** [comment]
Hi,

I tried it last evening, and thankfully it worked from Groups proper.

Formatting seems completely off thou. But that's another issue.

Thanks for your response 🙂

Best regards,
Bjørn

tir. 20. dec. 2022 19.57 skrev james acklin ***@***.***>:
