### ISSUE TITLE
Ship cannot talk to ~sogryp-dister-dozzod-dozzod, so this ship never got the key apps after the OTA

### ISSUE THREAD

**Issue by wbsquared** [tloncorp/landscape-apps#1573]
**Describe the bug, optionally with screenshots**
I have a moon that cannot |hi ~sogryp-dister-dozzod-dozzod - so after the recent OTA, groups was deleted, but neither new groups nor talk were installed. That ship is now stuck with limited functionality and only two tiles on grid: terminal, bitcoin.

**To Reproduce**

This happened only on this one ship, which is a moon. I am not sure why it cannot |hi the distributor ship. It is on a box with other ships which have no communication issues, and the azimuth block is current, and it seems to be able to communicate with other ships without an issue.

**Expected behavior**
I expect this ship to be able to talk to the distributor ship and get the new apps.

**Additional context:**
- Ship type (comet/moon/planet/star/galaxy): Moon. only thing of notes is that this moon's sponsor planet did have to breach. but other moons have updated fine so I don't think that is the issue.
- Instance type - self hosted on linux, with proper port forwarding and other ships on the box working fine.

If there is a way to jump start ship-ship communications, LMK. I would love to get in touch with ~sogryp-dister-dozzod-dozzod as I think this would resolve the issue right away.

**Comment by jamesacklin** [comment]
If that moon can talk to its peers on the same host box, you can always try re-publishing the treaty and installing from one of them: https://developers.urbit.org/guides/additional/software-distribution#publish

**Comment by jamesacklin** [comment]
@wbsquared Did you ever get this sorted out? This isn't a software issue with Landscape, Groups, or Talk per se, so I'd like to close this out. You can email landscape-dev@tlon.io if you need additional support.
