### ISSUE TITLE
groups: unread markers in sidebar stop updating eventually

### ISSUE THREAD

**Issue by tinnus-napbus** [tloncorp/landscape-apps#1575]
**Describe the bug, optionally with screenshots**
When I leave groups open for a while, I see no unread blue dots on the groups in the sidebar. When I refresh, there are new blue dots. It seems to stop updating after a while.

**To Reproduce**
1. Read all unreads
2. leave it a while
3. see no unreads
4. refresh
5. see a number of unreads

**Expected behavior**
unreads should update live

**Additional context:**
- Ship type: planet
- Instance type: self-hosted
- OS/browser: qutebrowser on arch linux

**Comment by ryjm** [comment]
also seeing this with unreads not being cleared even if you're actively viewing channels - we must be not tracking hark state with the same fidelity of chat et al.

**Comment by belisarius222** [comment]
`~mastyr-bottec` and I have also hit this

**Comment by tomholford** [comment]
So I have experienced this too, happens after leaving the tab idle / backgrounded for some time. Tried to repro it by shutting down fake ships, sending messages, then rebooting. But that would either trigger a refresh, and / or the client subscriptions would reconnect automatically. Any other ideas on how to repro this? Might just have to let it be in the background for awhile
