### ISSUE TITLE
groups: editing channel options permanently displays options button

### ISSUE THREAD

**Issue by ashelkovnykov** [tloncorp/landscape-apps#1578]
**Describe the bug, optionally with screenshots**
The button to edit channel options only appears on a channel when you hover over it. However, if you click the button and edit the channel options, once you exit, the button is now permanently displayed. This can affect multiple channels at one time.

[Screenshot](https://0x0.st/o5We.png)

**To Reproduce**
1. Go to any group that you admin
2. Go to the "member & group info" page
3. Go to channels
4. Hover over a channel to bring up the options on the right-hand side
5. Click the options
6. Click "edit channel"
7. Click cancel in the new pop-up
8. See error

**Expected behavior**
No options buttons should be displayed on the right-hand side, since after clicking cancel the mouse cursor is not covering any channels.

**Additional context:**
- Ship type = planet
- Instance type = self-hosted
- Chormium-based browser on Pop!_OS 20.10

**Comment by jamesacklin** [comment]
We're renovating the channel admin screen shortly anyway, keeping this around so we're aware in the redesign.

**Comment by jamesacklin** [comment]
Still a think @ashelkovnykov ?

**Comment by ashelkovnykov** [comment]
@jamesacklin Currently traveling, will let you know shortly

**Comment by ashelkovnykov** [comment]
@jamesacklin No, the interface has changed to make this no longer relevant
