### ISSUE TITLE
No members visible in group when viewing from mobile

### ISSUE THREAD

**Issue by ashelkovnykov** [tloncorp/landscape-apps#1580]
**Describe the bug, optionally with screenshots**
Cannot see the members of a group when accessing Landscape remotely from a mobile device.

[Screenshot](https://0x0.st/o5W_.png)

**To Reproduce**
1. Login to ship from mobile device
2. Go to group
3. Click on "Group Info"

**Expected behavior**
Expect to see a list of members in the group.

**Additional context:**
- Ship type = moon
- Self-hosted on VPS
- Host VPS running Ubuntu 20.10
- Host VPS running Caddy
- Moon accessed remotely from mobile device
  - Moto E6
  - Android 9
  - Chromium-based browser

**Comment by jamesacklin** [comment]
Related to #1591

**Comment by jamesacklin** [comment]
Fixed by #1663
