### ISSUE TITLE
No channels visible in group when viewing from mobile

### ISSUE THREAD

**Issue by ashelkovnykov** [tloncorp/landscape-apps#1581]
**Describe the bug, optionally with screenshots**
Cannot see channels of a group when accessing from mobile device.

[Screenshot](https://0x0.st/o5W9.png)

When the same group is accessed from the same ship using a desktop web interface, the channels of the group are visible.

Note that this ship is not a member of any channels in the group yet: the ship is attempting to join channels in the group.

**To Reproduce**
1. Leave all channels in a group (or join a new group with no default channels)
2. Access ship from mobile device
3. Go to group
4. Click on "Channels"
5. See error

**Expected behavior**
Should see a list of channels available to join.

**Additional context:**
- Ship type = moon
- Self-hosted on VPS
- Host VPS running Ubuntu 20.10
- Host VPS running Caddy
- Moon accessed remotely from mobile device
  - Moto E6
  - Android 9
  - Chromium-based browser

**Comment by jamesacklin** [comment]
![Screen Shot 2023-01-10 at 13 26 27](https://user-images.githubusercontent.com/748181/211632626-bd665772-173e-4662-b8dd-68656f8394b2.png)

Fixed by #1608
