### ISSUE TITLE
group-store: Existing and new rank-level bans are not enforced.

### ISSUE THREAD

**Issue by litmus-ritten** [tloncorp/landscape-apps#1593]
I have recently noticed that comets are able to join and interact with groups I administer, despite these groups having a previously effective rank-level ban of comets (a.k.a. _'Antikomet Aktion'_) for reasons of accountability. I know that a number of other groups do the same for similar reasons, and I presume that these groups are similarly affected, though I have not seen any other reports of this. This regression is probably associated with Landscape 1. **This regression may represent a privacy and/or security risk, as well as a risk of serious nuisance in light of #1429.**

**To Reproduce**
1. Spawn a comet.
2. Using the comet, join a group with an extant rank-level ban of comets.
3. Observe that you can enumerate channels, read chats, and post chats.
4. Leave the group.
5. As group host, run the previously effective command `:group-store &group-update-0 [%change-policy [~YOUR_GROUP_HOST %YOUR_GROUP_NAME] [%open [%ban-ranks (sy ~[%pawn])]]]` to rank-ban comets.
6. Rejoin the group as the comet.
7. Observe that the command given in step 5 had no effect.

**Expected behaviour**
Rank-level bans should be effective. Banned ranks should not be able to interact with affected groups, and should probably not be enumerated in the search interface. Alternatively, the search interface should indicate that enumerated groups are inaccessible to the searching user based on their rank and rank-level bans (as well as any per-user bans that might be in effect, but that's a different matter).

**Additional context:**
- Ship type: planet
- Instance type: self-hosted, CLI
- OS/browser: Vivaldi on Linux

**Comment by thelifeandtimes** [comment]
Figure i would add this comment here instead of a new issue, but the 'banned' section of the membership management UI in new groups is blank for me.

**Comment by litmus-ritten** [comment]
> Figure i would add this comment here instead of a new issue, but the 'banned' section of the membership management UI in new groups is blank for me.

Can confirm this.

**Comment by litmus-ritten** [comment]
Some more info on this: inspecting the `cordon` field of the groups JSON indicates that the `pawn` rank is indeed banned in the group I am testing, but that this is evidently not being respected somewhere.

**Comment by jamesacklin** [comment]
Rank-level bans exist, we just need to implement them on the front-end.

**Comment by litmus-ritten** [comment]
@jamesacklin Are bans enforced client-side?

**Comment by arthyn** [comment]
@litmus-ritten no they should be enforced hoon-side we may have just missed something here.
