### ISSUE TITLE
Talk: Joining a new group from a reference in a chat channel takes you to a blank page

### ISSUE THREAD

**Issue by thelifeandtimes** [tloncorp/landscape-apps#1596]
**Describe the bug, optionally with screenshots**
I was in a chat where someone shared a link to a new public group for which I was not yet a member, clicking `join` presumably gave me access to a group, but took me to a page with a blank main window and just my standard talk sidebar.

**To Reproduce**
1. Go to a group chat from within Talk
2. Click on the `join` button in a reference to a public group for which you are not a member

**Expected behavior**
A variety of things could happen here:
- automatically open a new browser tab with that group's main channel page
- take me to a chat channel within that group, likely the one with the most recent new messages?
- take me to a dialog box prompting me to open groups?

**Additional context:**
- Ship type: Planet
- Instance type: Self-Hosted on ubuntu
- OS/browser: Brave on MacOS

**Comment by jamesacklin** [comment]
Similar to #1664, address at the same time.

**Comment by arthyn** [comment]
and #1655
