### ISSUE TITLE
Groups: When I join a group I get a notification saying I was invited

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1599]
- Go to Find Groups
- Search ~tirrel
- Join Marketplace
- Get the following notification:
<img width="464" alt="Screenshot 2022-12-29 at 6 09 30 PM" src="https://user-images.githubusercontent.com/441466/210027549-d4680d96-2e8a-45d8-88b1-16d96f9f3059.png">

**Comment by tomholford** [comment]
> Yep - the notification should appear in grid/garden/landscape notification menu after joining.

Just left and re-joined Marketplace, unfortunately no luck in for repro. Is there another group I can try?

**Comment by jamesacklin** [comment]
I got this after joining ~rondev's Group Discovery.

**Comment by tomholford** [comment]
@jamesacklin  Thanks! 

@zalberico And whaddya know, I closed the tab and reopened and there it was! Sorry for the trouble
