### ISSUE TITLE
Landscape: login page in dark mode has unreadable contrast in input fields 

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1602]
- Be in dark mode on iOS
- Logout to see urbit log in screen
- Note that the patp and +code field are not readable

**Comment by jamesacklin** [comment]
Fix is to update /~/login to the latest Indigo spec.

**Comment by jamesacklin** [comment]
For anyone who wants to dig in, the login page is written in sail: https://github.com/urbit/urbit/blob/master/pkg/arvo/sys/vane/eyre.hoon#L239
