### ISSUE TITLE
Groups: Renaming a channel kicks off a notification that a channel has been added

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1604]
I renamed a channel from chat to EM/PM Chat (to get around the UX in talk of everything having the same name) and got a notification which implies a new additional channel was added instead of an existing channel being renamed. This notification should be: "chat was renamed to EM/PM Chat" or something like that.

<img width="795" alt="Screenshot 2022-12-31 at 4 20 23 PM" src="https://user-images.githubusercontent.com/441466/210158123-d696f108-7ecf-4291-962a-38fd63270aa3.png">

**Comment by litmus-ritten** [comment]
This also happens if you remove a channel as a default channel for a group.

**Comment by zalberico** [comment]
Similarly, joining a public group creates a notification that I was "invited" to the group by the host

**Comment by tomholford** [comment]
> Similarly, joining a public group creates a notification that I was "invited" to the group by the host

This issue was resolved in #1629 

The OP issue is resolved in #1645
