### ISSUE TITLE
Interactive Elements Shifting

### ISSUE THREAD

**Issue by minderfolden** [tloncorp/landscape-apps#1609]
<img width="739" alt="Screenshot 2023-01-02 at 20 46 48" src="https://user-images.githubusercontent.com/51895363/210290677-bcf9f475-a62b-4924-a88b-7541507e1ec0.png">
I go to click the "add attachment" plus sign.

<img width="739" alt="Screenshot 2023-01-02 at 20 47 24" src="https://user-images.githubusercontent.com/51895363/210290698-15cc1497-1da0-4cdc-b7a6-7891c0eb24e1.png">
But then the text formatting line disappears and the plus shifts down. Then I have to mouse down to click the plus again before the upload attachment flow starts. 

Same thing happens when the text input area is expanded but I then try to add an emoji react. I'll click the react element, and then the formatting area disappears and I have to click the emoji react element again.

**Additional context:**
- Ship type: planet
- Instance type: Digital Ocean droplet
- OS/browser: Stack Browser https://stackbrowser.com/

**Comment by jamesacklin** [comment]
@minderfolden This is an interesting one—are you on a desktop browser with the mobile layout?

**Comment by minderfolden** [comment]
Here's a screen recording: https://share.descript.com/view/UpxIBwDDt76 

It's on my desktop.

**Comment by minderfolden** [comment]
Nope; not Realm. It's the Stack Browser and I have Grid open in one card, and Groups open in another card.

**Comment by jamesacklin** [comment]
OK, interesting -- will repro and see what's up

**Comment by arthyn** [comment]
hmm shouldn't be getting the mobile UI at the res, interesting
