### ISSUE TITLE
collections: uploading media to a collection appends media to talk message input instead

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1613]
**Describe the bug, optionally with screenshots**
When I attempt to upload media to a collection (via S3), I don't see anything added to the collection's input field/"posting" interface. This seemed to be the only issue until I navigated over to a talk channel afterward, and saw the media attached to the message input.

Check out this video for an example of what I mean:

https://user-images.githubusercontent.com/1195363/210431133-ab6ede54-fab8-409c-a301-f37628318bf5.mov

**To Reproduce**
1. Go to a collection
2. Attempt to upload media to the collection via S3
3. If you don't see anything, you've repro'd the first part of this bug
4. Navigate to a Talk channel
5. If you see the media you had attempted to upload now attached to the message-writing input, you've repro'd the second part of this bug

**Expected behavior**
I expect media uploaded to a collection to be solely scoped to the same collection — the weird bleed-over of media uploading between channels struck me as completely unexpected.

**Additional context:**
- Ship: planet (~fabled-faster)
- Instance type: Tlon-hosted
- MacOS Ventura — 13.0.1 (22A400)
- Safari — Version 16.1 (18614.2.9.1.12)
- Chromium — Engine Version 106.0.5249.103

**Comment by jamesacklin** [comment]
Similar to #1586
