### ISSUE TITLE
notebooks: Syntax highlighting not displayed within notebook codeblocks

### ISSUE THREAD

**Issue by mopfel-winrux** [tloncorp/landscape-apps#1616]
**Describe the bug, optionally with screenshots**
When editing a notebook a bunch of newlines are added to the editor.

Also any meta stored in block comments get lost and the formatting gets all screwy

**To Reproduce**
1. Make a notebook entry that uses block quotes and multiple new lines
2. save it
3. edit it

**Expected behavior**
The formatting and meta data should be saved between saves

**Additional context:**
- planet
- Self Hosted
- Windows Chrome

**Comment by jamesacklin** [comment]
#1357

**Comment by mopfel-winrux** [comment]
@jamesacklin Ahh I didn't look hard enough for a similar bug sorry. The difference is the block code comments both not doing the syntax highlighting when saved and getting messed up when editing.

**Comment by jamesacklin** [comment]
@mopfel-winrux All good, didn't know about the missing metadata so I didn't close as a dupe and just linked for our devs. Thank you!

**Comment by patosullivan** [comment]
the real issue here seems to be that we're losing syntax highlighting.

**Comment by patosullivan** [comment]
Also, editing the note turns it into inline formatted code rather than a code block.
