### ISSUE TITLE
groups: admin channel management is broken

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1618]
- Be a group admin
- Go to Members & Group Info
- Go to Channels
- Attempt to create sections and order channels
- Attempt to set channels to default
- Observe that channels move around randomly while trying to order them, don't move between sections easily, setting a channel as default doesn't always stick, if you have a lot of channels it's hard to organize between sections.

This UI is extremely frustrating to use.

**Comment by zalberico** [comment]
More stuff:
 - If you rename a section and don't make a change it wipes the old name (even if you don't click enter)
 - Setting default channels works 5% of the time?

**Comment by jamesacklin** [comment]
@urcades To consider for redesign.

**Comment by jamesacklin** [comment]
Fixing in #1770

**Comment by jamesacklin** [comment]
@patosullivan See what your index mismatch fix addresses from this issue.
