### ISSUE TITLE
Notebook Misbehaving

### ISSUE THREAD

**Issue by minderfolden** [tloncorp/landscape-apps#1622]
Something is jacked up, and I don't know where. This is the only group on the host moon. The moon was booted specifically to host this group. No clue where the hiccup entered the equation. It's set to allow anyone/everyone to read + write. The permissions are there.

![image](https://user-images.githubusercontent.com/51895363/210606883-a3c09110-8b09-4cb3-826b-5921e8f3432e.png)

Additionally, there's something weird with my planet not being able to see posts in the notebook, either. When I try to use the planet (which is an admin in the group) to make a post in the notebook (which is open to everyone) it just errors out.

**Expected behavior**
Make a post and it goes live. People can comment.

**Additional context:**
- Ship type: planet + moon
- Instance type: Digital Ocean droplet
- OS/browser: Chrome + Brave + Stack on Windows + Mac

**Comment by minderfolden** [comment]
From `~hoster-minder-folden`:
```
>   dojo: nest-need
[ *
    args
  ?(
    %~
    [   poke
      ?(
        [%bowl %~]
        [%incoming about=?(%~ [%path path=/] [%ship ship=@p] [%term term=@tas] [%wire wire=/])]
        [%outgoing about=?(%~ [%path path=/] [%ship ship=@p] [%term term=@tas] [%wire wire=/])]
        [%state grab=@t]
      )
      %~
    ]
    [what=?(%bowl %state) %~]
  )
  %~
]
>   dojo: nest-have
[[now=@da eny=@uvJ bec=[p=@p q=@tas r=?([%da p=@da] [%tas p=@tas] [%ud p=@ud])]] [@t %~] %~]
> :diary +dbug '(~(got by shelf) [~hoster-minder-folden %accountability-jackpot])'
dojo: generator failure
```

**Comment by arthyn** [comment]
ah sorry I messed that command up `:diary +dbug [%state '(~(got by shelf) [~hoster-minder-folden %accountability-jackpot])']`

**Comment by minderfolden** [comment]
https://pastebin.com/4yDrx8hD

**Comment by arthyn** [comment]
Hmm ok so your log matches mine, but the screenshot shared above does not match what is in the state there. Was the above screenshot taken from the group host or just an admin?

**Comment by minderfolden** [comment]
host moon

**Comment by jamesacklin** [comment]
Sounds like your planet is missing a subscription to that channel -- can you try leaving and rejoining?

@arthyn will continue to dig in with you.

**Comment by jamesacklin** [comment]
@minderfolden Any updates to share?

**Comment by minderfolden** [comment]
Things are kind of better; still not great. Groups that I have admin access to (as ~minder-folden) but didn't create the channel or group will not show me updates. Example: I'm an admin in a group so I built out some sections & added channels to each section.

No matter how many times I refresh, leave & rejoin, or what I never see the "arranged" view, even though others do.

**Comment by patosullivan** [comment]
Hey @minderfolden are you still seeing any of the above-mentioned issues?

**Comment by minderfolden** [comment]
Seems like it's behaving now!
