### ISSUE TITLE
groups: see 'reject' in a group link

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1634]
- Be a member of Tlon Public
- Go to Tlon Hosting Support Group
- View Resources Notebook
- Click Read Me First Notebook
- Observe the below
<img width="769" alt="Screenshot 2023-01-05 at 10 48 47 AM" src="https://user-images.githubusercontent.com/441466/210857702-a42a47ad-7468-407b-b98d-8bf80b846842.png">

This is a link in that notebook for people to join Tlon Public. It has a reject option weirdly.

Notably the link to the other group does not.

**Comment by jamesacklin** [comment]
Dupe #1910
