### ISSUE TITLE
chat: prevent paste to upload if s3 is not yet configured

### ISSUE THREAD

**Issue by tomholford** [tloncorp/landscape-apps#1642]
Even if a user does not yet have s3 configured, the paste flow is still enabled. Need to disable this to prevent the following:

![image](https://user-images.githubusercontent.com/16504501/210894790-d3575cc9-f5bc-4aa8-98db-c961e1535721.png)

**Comment by jamesacklin** [comment]
@vvisigoth ran into this as well, I was able to repro. Thanks for logging!
