### ISSUE TITLE
groups: d.replied.at is not a function

### ISSUE THREAD

**Issue by tinnus-napbus** [tloncorp/landscape-apps#1643]
got this error after following mention notification to channel

```
TypeError: d.replied.at is not a function
    at https://u.tinnus-napbus.xyz/apps/groups/assets/index.e70a0985.js:1067:10293
    at VH (https://u.tinnus-napbus.xyz/apps/groups/assets/index.e70a0985.js:93:53297)
    at Wj (https://u.tinnus-napbus.xyz/apps/groups/assets/index.e70a0985.js:93:61439)
    at _ie (https://u.tinnus-napbus.xyz/apps/groups/assets/index.e70a0985.js:97:10816)
    at Pie (https://u.tinnus-napbus.xyz/apps/groups/assets/index.e70a0985.js:97:964)
    at k6e (https://u.tinnus-napbus.xyz/apps/groups/assets/index.e70a0985.js:97:887)
    at Zw (https://u.tinnus-napbus.xyz/apps/groups/assets/index.e70a0985.js:97:737)
    at WG (https://u.tinnus-napbus.xyz/apps/groups/assets/index.e70a0985.js:95:10947)
    at https://u.tinnus-napbus.xyz/apps/groups/assets/index.e70a0985.js:93:39072
    at e.unstable_runWithPriority (https://u.tinnus-napbus.xyz/apps/groups/assets/index.e70a0985.js:82:3899)
```

```
> +vat %groups
%groups
  /sys/kelvin:      [%zuse 417]
  base hash:        0vs.n20oi.r18b8.ruh8k.250eh.iummk.p8udg.8l23j.b9628.n3sao.j2gsd
  %cz hash:         0vs.n20oi.r18b8.ruh8k.250eh.iummk.p8udg.8l23j.b9628.n3sao.j2gsd
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~sogryp-dister-dozzod-dozzod
  source desk:      %groups
  source aeon:      6
  kids desk:        ~
  pending updates:  ~
::
```

**Comment by tinnus-napbus** [comment]
getting this also when just opening certain channels

**Comment by jamesacklin** [comment]
@tinnus-napbus Are you mentioned in those channels?

**Comment by h5gq3** [comment]
i got this too

**Comment by h5gq3** [comment]
ow dang it bork my entire landscape experience. happens now at other channels too

**Comment by patosullivan** [comment]
this is definitely the same issue as #1644

**Comment by patosullivan** [comment]
still can't repro, however I've found a separate issue related to thread reply times being wrong (again).

**Comment by playfulpachyderm** [comment]
I have the same problem (~wispem-wantex).  It happens on nearly every channel I load.  I am using Port as a client to my ship which is hosted remotely.

![image](https://user-images.githubusercontent.com/5721742/211052301-9a8ae3d4-e36a-43b5-9f35-6e60acb0460a.png)

In EScape (which I assume has pretty much rebased on the new Groups), the same error happens except it says "g.replied.at" instead of "d.replied.at".

**Comment by patosullivan** [comment]
> 



> I have the same problem (~wispem-wantex). It happens on nearly every channel I load. I am using Port as a client to my ship which is hosted remotely.
> 
> ![image](https://user-images.githubusercontent.com/5721742/211052301-9a8ae3d4-e36a-43b5-9f35-6e60acb0460a.png)
> 
> In EScape (which I assume has pretty much rebased on the new Groups), the same error happens except it says "g.replied.at" instead of "d.replied.at".

interesting, @tinnus-napbus do you use port as well?

**Comment by playfulpachyderm** [comment]
Just tested in Brave, problem doesn't happen (neither in Groups nor EScape).  Looks like a Port issue!

**Comment by patosullivan** [comment]
Would anyone experiencing this issue be available to pair with me today?

**Comment by playfulpachyderm** [comment]
post `@p` or message me (~wispem-wantex)

**Comment by playfulpachyderm** [comment]
> Would anyone experiencing this issue be available to pair with me today?

post `@p` or message me (~wispem-wantex)

**Comment by patosullivan** [comment]
@playfulpachyderm @tinnus-napbus @h5gq3 could you try installing groups and talk from ~binnec-dozzod-marzod and let us know if the issue still persists?

**Comment by h5gq3** [comment]
should i first nuke or uninstall existing groups/talk? and what's the reason to manually install it from ~binnec-dozzod-marzod? shouldn't they be the same agents across the whole network? might it be that we haven't got OTA some recent update of these and that's causing version incompatibility? my current groups and talk OTA source is ~sogryp-dister-dozzod-dozzod if that matters

**Comment by jamesacklin** [comment]
Don't nuke or uninstall. We have published this specific fix to `~binnec-dozzod-marzod` so you can try to see if your issue is alleviated. We're unable to reproduce this in-house, despite being on the same versions of Port and the agents (like you mentioned).

If you'd like to help, the dojo command is: `|install ~binnec-dozzod-marzod %groups`

**Comment by h5gq3** [comment]
update from `|install ~binnec-dozzod-marzod %groups` did the trick

**Comment by jamesacklin** [comment]
@h5gq3 Excellent, thank you. If we get another confirmation, we'll cut a formal release today and you can re-install the stable build when we announce. Command for that will be `|install ~sogryp-dister-dozzod-dozzod %groups`

**Comment by tinnus-napbus** [comment]
@jamesacklin ok it seems like this has fixed it, I was able to read all channels. Also seems fixed in talk.

ftr I don't use port & the issue would seem to be related to mentions deep in unread backscroll. It cropped up when the subscription fix was deployed, so I suddenly got a month of unread backscroll in a number of channels

**Comment by playfulpachyderm** [comment]
Also confirming that it's fixed for me when I install from ~binnec-dozzod-marzod.

**Comment by arthyn** [comment]
anyone that installed from ~binnec don't change your source back to ~sogryp until we deploy otherwise your groups state will get wiped

**Comment by zalberico** [comment]
I edited James' comment in place to make it really obvious for now.
