### ISSUE TITLE
Groups: Notification not clearing.

### ISSUE THREAD

**Issue by mopfel-winrux** [tloncorp/landscape-apps#1647]
**Describe the bug, optionally with screenshots**
I have a notification from a thread in a group that was delayed in merging over. I can't clear the notification. Other notifications can be cleared

**To Reproduce**
1. Open Groups
2. Go to notifications 
3. Scroll down to bottom
4. Mark Notification as read
5. Doesn't get marked as read

**Expected behavior**
The notification should clear

**Additional context:**
- Planet
- Self-Hosted
- Windows Chrome

**Comment by jamesacklin** [comment]
May be solved eventually by #1638

**Comment by arthyn** [comment]
I think this is the same as #1447. Because hark clears out after a certain time you're just left with the non-functioning duplicate.

**Comment by arthyn** [comment]
Closing in favor of #1447
