### ISSUE TITLE
groups: channels that are "left" after joining persist in sidebar under "arranged" sort

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1648]
**Describe the bug, optionally with screenshots**
In the Tlon Public group, I left each of the 2022-named channels I was subscribed to and discovered that they persist in my sidebar in the "Arranged" sort. They appear to be removed in the sidebar as expected under the "Recent" and "Alphabetical" sort. Refreshing the page doesn't appear to fix this issue.

See video for example:

https://user-images.githubusercontent.com/1195363/211051722-ae82a1a2-40ed-4246-8d85-5d2c1582fdd6.mov

**To Reproduce**
1. Find a group with channels you can leave
2. Ensure the sidebar sort is set to "Arranged"
3. Leave the channels
4. If the channels remain in the sidebar, you've repro'd the bug

**Expected behavior**
No matter the sidebar's sort setting, I always expect to not see channels I have left or unsubscribed from

*Additional context:**
- Ship: planet (~tonlur-hidlyn)
- Instance type: Self-hosted (Digital Ocean)

Accessing the above urbit through the following machine, remotely:
- MacOS Ventura — 13.0.1 (22A400)
- Safari — Version 16.1 (18614.2.9.1.12)

**Comment by jamesacklin** [comment]
This may have been a problem with ~nibset-napwyn, as I am unable to reproduce in any other group (on Safari).
