### ISSUE TITLE
groups: reference to msg in channel you're not a member of goes nowhere

### ISSUE THREAD

**Issue by tinnus-napbus** [tloncorp/landscape-apps#1655]
**Describe the bug, optionally with screenshots**
If someone posts a reference to a message in a group you're a member of but in a channel you've not joined, it takes you to the group but doesn't open any channel, it's just empty

**To Reproduce**
1. follow link to msg in channel you've not joined
2. observe there's nothing

**Expected behavior**
it should probably prompt you to join the channel

**Comment by jamesacklin** [comment]
We might make this implicit -- if you follow the reference, you join the channel. How does that sound @tinnus-napbus?

**Comment by tinnus-napbus** [comment]
that makes sense for groups you're already a member of
