### ISSUE TITLE
talk: visual refactor + improvements to "reference" message types

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1675]
### One-line Summary: 

The "reference" component needs to be polished – while we've implemented its intended _functionality_, we haven't implemented it _precisely_ "to spec", which should help with its functional legibility.

### Issues

As of writing, the "reference" messaging component looks like this:

![References](https://user-images.githubusercontent.com/1195363/211635539-b8242a29-8046-4ebf-a6d4-e5ec7ac17e6a.png)

While references are more or less functioning in an MVP manner, there are a few key optimizations and simplifications we can implement to make them feel a lot more "solid" and meaningful as block-quote-adjacent structures.

The current issues with the component:

<img width="706" alt="Screenshot 2023-01-10 at 1 50 25 PM" src="https://user-images.githubusercontent.com/1195363/211636778-84410cd7-deff-46ea-8f93-c68cb6f12183.png">

1. zero margin between an inaccessible/nonexistent reference and the following message (edit: this "zero margin" issue actually seems to affect any reference that's coupled with nominal message text, when attaching a reference to the message input)
2. an empty (and useless) metadata row that looks buggy/unintentional

<img width="480" alt="Screenshot 2023-01-10 at 1 50 28 PM" src="https://user-images.githubusercontent.com/1195363/211636790-5008bd79-e3ed-4967-b7f3-98d2db3fab77.png">

3. The metadata row, when filled with data, is the same size as normal author rows, which causes them to "fight" for visual dominance, which makes the message feed harder to parse/read
4. there's a huge margin between a fully-rendered reference and a "reply" row appended to it

<img width="426" alt="Screenshot 2023-01-10 at 1 50 32 PM" src="https://user-images.githubusercontent.com/1195363/211636805-55678334-f170-41d0-8ebc-6f732760e6f9.png">

5. There are two "hover" states for a reference row, which decrease the feeling of 'stability' in the interface

With these issues laid out, I'll proceed to write some implementation polish suggestions in a following post.

**Comment by jamesacklin** [comment]
As @patosullivan brought up, let's consider click interactivity for meta information.
