### ISSUE TITLE
notebooks: Editing a post inserts additional line breaks

### ISSUE THREAD

**Issue by thelifeandtimes** [tloncorp/landscape-apps#1680]
**Describe the bug, optionally with screenshots**
If I make a notebook post, publish it, and then return to make edits, upon reopening the editor, additional line breaks will be added. Upon republishing, those additional lines will appear in the updated notebook post.

**To Reproduce**
1. Go to a previously published notebook
2. Click on 'edit'
3. Scroll down to a location which previously had a single linebreak
4. See that there is an additional linebreak
5. Republish the post, receiving additional linebreaks out the wazzoo

**Expected behavior**
Selecting 'edit' along should not modify the state/contents of my notebook post at all.

**Additional context:**
- Ship type: planet
- Instance type: self-hosted
- OS/browser: Brave

**Comment by jamesacklin** [comment]
Fixed by #1662, due out to mainnet tomorrow with v2.4.0

**Comment by patosullivan** [comment]
Thanks for reporting this sarlev, but we beat you to the punch this time: https://github.com/tloncorp/landscape-apps/pull/1662

**Comment by thelifeandtimes** [comment]
ahhh, didn't realize things were logged as `%diary` and `notebooks`, was just reviewing things including `notebooks`. Will search both going forward cuz I'm running into lots of bugs using these and trying to give you guys some good reports...

**Comment by patosullivan** [comment]
> ahhh, didn't realize things were logged as `%diary` and `notebooks`, was just reviewing things including `notebooks`. Will search both going forward cuz I'm running into lots of bugs using these and trying to give you guys some good reports...
> 

It's very appreciated, sarlev. And yeah, the backend vs frontend naming conventions are cumbersome at times.
