### ISSUE TITLE
groups&talk: required manual refresh and long load times when re-accessing old browser tabs

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1684]
- Have groups and talk open in mobile browser tabs on your phone
- Live your life
- Open up groups and/or talk after a few hours
- Observe that the state is old and requires doing a hard refresh manually to update
- Refresh can take up to ~30s, but usually around 10-15s to load

This is most obvious on mobile, but the same thing can also happen in old chrome tabs.

**Comment by zalberico** [comment]
Is it possible this is from having lots of tabs open to groups and talk on different devices? Ship connections or something?

**Comment by jamesacklin** [comment]
Unlikely, I'm a habitual tab-closer/app-quitter and I run into this as well.

**Comment by arthyn** [comment]
This should be fixed since a few releases
