### ISSUE TITLE
Cannot see moon's profile in Groups from planet

### ISSUE THREAD

**Issue by ashelkovnykov** [tloncorp/landscape-apps#1686]
**Describe the bug, optionally with screenshots**
I've setup a moon (which I only access through a mobile device), including it's profile in Groups. However, my primary ship cannot see its profile. The moon's profile is **not** private, and my primary should **does** have profiles enabled.

![example 1](https://0x0.st/o7pc.png)
![example 2](https://0x0.st/o7pT.png)

As a side note, the moon cannot see other ships' profiles either.

**To Reproduce**
1. Make a new moon
2. Setup its profile
3. Have it DM your main ship

**Expected behavior**
Ships should be able to see the moon's profile, and vice-versa.

**Additional context:**
Planet:
- Ship type = planet
- Instance type = self-hosted(Tlon-hosted/self-hosted with Port/CLI)
- Chormium-based browser on Pop!_OS 20.10

Moon:
- Ship type = moon
- Self-hosted on VPS
- Host VPS running Ubuntu 20.10
- Host VPS running Caddy
- Moon accessed remotely from mobile device
  - Moto E6
  - Android 9
  - Chromium-based browser

**Comment by jamesacklin** [comment]
Dupe #1305
