### ISSUE TITLE
landscape: notifications updates

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1689]
Per the [project specification](https://docs.google.com/document/d/1z_qpCWGKv5Muio9P1-uxGnEVOr9_jZ3vQPwsSV10DME/edit?usp=sharing) written out by @jamesacklin, I've arranged a few updates to the notifications interface(s) across landscape and groups.

In this issue, I'll go over Landscape-specific updates, which amount to:

1. Updates to the notification row component towards the ends of increasing legibility and heightening mentions/invites/dms over other notification types
2. Updates to the interface that contains notifications, to make notifications a little easier to filter/parse through

To begin, I've updated the row component's overall structure/IA from this:

![Old Notification Structure](https://user-images.githubusercontent.com/1195363/212113730-fd535a99-4df6-4d50-8a1e-39c1856df459.png)

To this:

![Notification Row](https://user-images.githubusercontent.com/1195363/212113773-15cf3210-d7b0-4159-b7f2-5a7bfdc2e94e.png)

Resulting in notifications that look like this:

<img width="2168" alt="All Notifications" src="https://user-images.githubusercontent.com/1195363/212114457-f27c6589-9d94-41ca-96b3-782be956693e.png">

Notably, I've shifted the overall IA of the component to feel more unidirectional, to be read from top to bottom. The separation of the "Event Trigger" provenance and the "Emanating/App/Resource Context" has been done to emphasize the thing actually sending you the notification (a person, usually), and make it clear where the trigger is coming from (an app, a group resource, etc.)

Additionally, comments and replies are structured such that they are easier to read, and "bundled" notifications have had their copy slightly adjusted to make the mechanics of bundling clearer than before ("the notification message being displayed is the latest of X additional messages").

"Side-effect" notifications such as changes to a group's channels or admin-only role/membership changes have been made more diminutive, towards the ends of lessening the noise of notifications and providing greater emphasis on "social" notifications.

Lastly, the dropdown "options" menu has been given a button-like affordance to make it clearer that notification rows can be individually acted on.

~

In Landscape, the notification rows themselves are situated in the notifications mega dropdown-dialog as usual, which has been restructured to provide additional ways of managing and viewing notifications:

<img width="1540" alt="Landscape Notifications" src="https://user-images.githubusercontent.com/1195363/212117076-1cfe2ea0-c29a-40c3-a9e9-964107e9b36b.png">

<img width="1540" alt="Landscape Notifications2" src="https://user-images.githubusercontent.com/1195363/212118192-ba144eec-fd17-4535-b871-c2c5ecdd9294.png">

<img width="1540" alt="Landscape Notifications3" src="https://user-images.githubusercontent.com/1195363/212118275-327a27e5-9228-4b0e-abba-71f015d8a2d8.png">

Four notable updates:

1. A new segmented navigation which operates as a filtering interface for notifications across all apps — for now, we're only introducing the idea of isolating mentions, but there are a variety of advanced/custom filter types we can imagine being located here
2. A "Mark All as Read" button
3. Per-notification actions granting the ability to mark individual notifications as read without clicking through them, or muting their originating context altogether
4. A slight change in the visual bundling of notifications, to make by-day demarcation of notifications a little clearer. While not shown in the static images above, there are some ideas for on-hover actions for entire days (such as minimizing/expanding them) which we may explore in the future, which will make use of this new visual bundling style

~

These are the high-level notes for initial implementation, more specific design/state details can be found in [Figma](https://www.figma.com/file/luXjuX8fdV2mQrfqCQ4Cr2/2023-Q1-Groups?node-id=2380%3A7835&t=lxBt8HrEvYmnDr8C-1)

**Comment by jamesacklin** [comment]
Reporting some incremental progress:

https://user-images.githubusercontent.com/748181/213017796-923f649a-0a61-416d-9dda-af766a98d05a.mov
