### ISSUE TITLE
groups: newly joined Urbit Community group doesn't render correctly

### ISSUE THREAD

**Issue by mcevoypeter** [tloncorp/landscape-apps#1690]
**Describe the bug, optionally with screenshots**
After breaching my ship, I rejoined the Urbit Community group. In the Groups side bar, the group name doesn't render (see first screenshot), and when I select the empty item in the sidebar, I end up in an empty version of the Urbit Community group (see second screenshot). When I navigate to Urbit Community via a notification, the channel the notification lead me to renders, but the sidebar doesn't render (see screenshot 3).

Screenshot 1:
![groups-sidebar](https://user-images.githubusercontent.com/43772349/212124470-e1565e97-9491-467c-931f-4da45a1fad7d.png)

Screenshot 2:
![uc-group](https://user-images.githubusercontent.com/43772349/212124491-2ac1a755-1756-45e8-9b5f-c75d05afbcc6.png)

Screenshot 3:
![uc-group-via-notification](https://user-images.githubusercontent.com/43772349/212124516-8102087d-e9d1-4509-ab1d-3852975adaa8.png)

**To Reproduce**
1. Breach ship.
2. Join ~bitbet-bolbel/urbit-community.
3. Enter Urbit Community group via Groups sidebar by clicking on the empty item in the sidebar.
4. Observe empty group.
5. Enter Urbit Community group via notification.
6. Observe partially rendered group.

**Expected behavior**
I expect the Urbit Community group to render correctly in the Groups sidebar and to permit me to view the entire contents of the group.

**Additional context:**
- Ship type: planet
- Instance type: self-hosted on an M1 Mac Mini via the command line.
- OS/browser (Safari on MacOS, Chrome on Windows, Firefox on Linux, etc.): macOS 12.5.1 + Firefox 108.0.2. I also see the same behavior when attempting to access my ship remotely via Tailscale on a Linux 6.1.2-arch1-1 machine running Firefox 108.0.1.

**Comment by mcevoypeter** [comment]
When I navigate to the Urbit Community group through a notification, I've also noticed I'm unable to send messages to the Help channel once I'm there. I can type the message out, but when I hit send, it disappears. I've confirmed it actually didn't send by checking the same thread I attempted to post to from a moon. Related may be the fact that if I type a message without attempting to send, then either toggle full screen or switch focus away from my browser, the unsent message disappears. My window manager is [Sway](https://swaywm.org/).

**Comment by jamesacklin** [comment]
Essentially, if you have a duplicate subscription from the host, things will look strange until something else happens (someone else joins, channel gets renamed, someone else posts a message, etc.). Will dig into this further with some breached moons.
