### ISSUE TITLE
Talk: Text entry field wiped when new messages arrive

### ISSUE THREAD

**Issue by vcavallo** [tloncorp/landscape-apps#1696]
Identical to https://github.com/tloncorp/landscape-apps/issues/1404

I haven't noticed this in a while, but started to notice it again today.

**Comment by rabsef-bicrym** [comment]
This one is real egregious in clubs for some reason. it makes it so everyone has to like signal that they're going to type a large paragraph, whereupon everyone else must not talk for a while so as to avoid risking deleting the writers post. Further, the writer signaling this might delete their own post in getting the various `ack`s they get on the message saying "I'm about to wriiiiiite"

**Comment by vcavallo** [comment]
or worse: they don't care to do that and just stop writing in the club.
and furthermore, they don't open an issue for it nor comment on this one :laughing:
