### ISSUE TITLE
contact-store: Can't edit multiple profile fields at same time

### ISSUE THREAD

**Issue by JohnRillos** [tloncorp/landscape-apps#1699]
**Describe the bug, optionally with screenshots**
When poking `%contact-store` with updates to two different profile fields, if the pokes have the same timestamp, only one of them will actually apply. 

I noticed this because I'm working on an app that sends multiple pokes to `%contact-store` in one event, however I also noticed the same thing happen when editing my profile like normal in the Groups UI.  I think it may be inconsistent though, depending on if the requests occurred at the same millisecond or not (according to the React app).

**To Reproduce**
1. Go to your Groups profile page.
2. Edit your Display Name and your Bio
3. Click "Save"
4. See that only one of those fields has actually updated, even if you refresh the page.

(alternatively, send two `%contact-update-0` pokes in one event)

**Expected behavior**
I would expect that I can edit multiple fields on my profile at the exact same timestamp, regardless of whether it's through the Groups UI or Gall.

**Additional context:**
- Ship type: moon
- Instance type: self-hosted, local
- OS/browser: Linux, Vivaldi (Chromium-based)

**Comment by jamesacklin** [comment]
Doesn't look like we have an easy solution for this. We'll be changing this behavior very soon, but I'm tagging in @arthyn to stay in touch with you (you're already in touch with @Fang-, so you may hear soon).

**Comment by jamesacklin** [comment]
Fixed by #2189
