### ISSUE TITLE
notebooks: undefined is not an object (evaluating 'n[i-1].content')

### ISSUE THREAD

**Issue by KeepCreatingOnline** [tloncorp/landscape-apps#1710]
**Describe the bug, optionally with screenshots**
A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.

**To Reproduce**

**Expected behavior**

**Additional context:**
- Ship type (comet/moon/planet/star/galaxy)
- Instance type (Tlon-hosted/self-hosted with Port/CLI)
- OS/browser (Safari on MacOS, Chrome on Windows, Firefox on Linux, etc.)

**Comment by tomholford** [comment]
@KeepCreatingOnline Thanks for reporting. What flow or action triggered this error? Which browser?

**Comment by KeepCreatingOnline** [comment]
> @KeepCreatingOnline Thanks for reporting. What flow or action triggered this error? Which browser?

Using Safari on iPhone. When I try to edit a notebook post in New Groups I get this error. 

It seems to happen on every notebook that was ported over from old Groups.
