### ISSUE TITLE
perms: unable to save group info when multiple admins

### ISSUE THREAD

**Issue by tomholford** [tloncorp/landscape-apps#1713]
![image](https://user-images.githubusercontent.com/16504501/212603170-ccd7d51c-a63b-4e08-8add-8ece0008e575.jpeg)

**Comment by arthyn** [comment]
> Doing this locally with good state gives me the correct effect. Checking bolbex it shows a subscription to your ship. Can you double check that you have a subscription to it? You can do so by entering :groups +dbug [%outgoing %ship ~bolbex-fogdys]
>
> Other than that is it possible that tab had stale subscriptions? Can you try doing something similar immediately after a refresh?
>
> Seems like this and https://github.com/tloncorp/landscape-apps/issues/1713 are probably the same issue

**Comment by jamesacklin** [comment]
Closing in favor of #1730
