### ISSUE TITLE
chat: thread unread count and indicator discrepancies

### ISSUE THREAD

**Issue by tomholford** [tloncorp/landscape-apps#1723]
**edit**: *see [the comment below](https://github.com/tloncorp/landscape-apps/issues/1723#issuecomment-1403916503) with a better example of the issue*

---

1. Visit a chat channel that has unreads
2. While the X New Messages Below banner is showing, open a thread
3. Observe that the banner is rendered in both the main chat window and the thread

Here's a screenshot from internal Tlon chat showing the thread with the banner; it dismissed before I could get a screencap of both banners.

![new_messages_banner](https://user-images.githubusercontent.com/16504501/213068477-e430e4d7-cdac-40a7-9ed0-f290d038454b.png)

**Comment by jamesacklin** [comment]
Behaviorally strange but somewhat expected? Marking this as "UX" to think about.

**Comment by tomholford** [comment]
@jamesacklin Okay here's a better example to help narrow down the issue. Note that the thread opened to the right is from an older reply to the bottom message. But then 5 replies were added to an earlier message above. Note how the 5 new messages counter is showing in the open thread, and how the unread dot is shown inline next to the older thread. These elements should instead be on the other newer thread above.

![Screenshot from 2023-01-25 08-44-35](https://user-images.githubusercontent.com/16504501/214624904-17bf0e6f-ae52-4f64-8f39-86dcf36d38e9.png)

**Comment by jamesacklin** [comment]
@patosullivan @arthyn Did we fix this? Everything seems fine to me now.

**Comment by arthyn** [comment]
This will get fixed when we revamp threads
