### ISSUE TITLE
groups: admins that are not hosts can't set default or kick users

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1730]
I've seen this, but not sure it's always the case.

- Be an admin of the Tlon + UF group
- Attempt to set a channel as default (nothing happens) or kick a user (nothing happens)
- Attempt a few more times
- Log into the host of the group
- Attempt to set channels as default
- Observe it works

**Comment by jamesacklin** [comment]
Tlon+UF might have had custom permissions. @arthyn don't we have a special one-liner for this?

**Comment by arthyn** [comment]
lemme investigate not sure the one liner will apply here

**Comment by arthyn** [comment]
Doing this locally with good state gives me the correct effect. Checking bolbex it shows a subscription to your ship. Can you double check that you have a subscription to it? You can do so by entering `:groups +dbug [%outgoing %ship ~bolbex-fogdys]`

Other than that is it possible that tab had stale subscriptions? Can you try doing something similar immediately after a refresh?

Seems like this and #1713 are probably the same issue

**Comment by jamesacklin** [comment]
Additional info: 

![](https://user-images.githubusercontent.com/16504501/212603170-ccd7d51c-a63b-4e08-8add-8ece0008e575.jpeg)
