### ISSUE TITLE
talk: add capability to edit messages sent to a talk channel

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1740]
When an erroneous/misspelled message has been sent to a Talk channel (or a DM/Group DM), the only option for recourse is to send another message with a correction, or to delete the message and send it again. 

I'd like to introduce the capability to edit one's own sent messages:

<img width="5580" alt="Editing a Message" src="https://user-images.githubusercontent.com/1195363/213530471-3449a310-3931-4555-9a98-2fe5015be073.png">

This image illustrates two methods of editing a message:

1. Tapping the "Up Arrow" on a computer with a keyboard attached, prompting the last-sent message to enter an inline editing state
2. Using the message row's "Action Bar" interface to surface an explicit "Edit Message" button, which switches the message row to an inline editing state
3. Related to point 2, we'd need to accommodate this action on mobile, and should use long taps to surface a bottom-shelf menu that approximates the actions available in point 2.

Editing a message should result in a visual indicator noting the message has been edited. There are two suggested means of highlighting this state:

1. In the message row itself, in the rightmost space we currently dedicate to "sent" markers
2. In the message row's Action Bar overflow menu, where we can append a receipt-like interface indicating whether a message is signed, edited, when it was sent, etc. This type of interface has plenty of prior art in many mainstream messaging applications.

The designs above are located in Figma: https://www.figma.com/file/bjNXjCnz10COnLs49ClQ6p/2023-Q1-Talk?node-id=2604%3A3507&t=hMBmjyExYrCsSDDW-1

**Comment by litmus-ritten** [comment]
Responding to the mockup by @urcades: Should edited chat messages really not indicate that they have been edited unless inspected? This can be a mischief vector in low-trust environments.

As a suggestion, consider a mild tint or pip to designate messages that have been edited.

**Comment by urcades** [comment]
This flow is intended to be read left-to-right as a path with two forks — the last two images on the rightmost edge of the image above, stacked on top of one another, indicate two distinct possibilities: 

1. Possibility a: We explicitly note an "Edited" state in the right-hand gutter where "unsent message" arrows currently reside
2. Possibility 2: The "Edited" state of a message rests within the receipt-like form within the message's action menu

I was always in favor of implementing the first of these, but offered the second one as food for thought — this state is semi-adjacent to the receipt screen in Signal, which shows whether a message has been opened or not, etc.

**Comment by litmus-ritten** [comment]
@urcades I'm a doofus: I missed that you provide two alternatives because I was looking at the figure fully zoomed in, sorry.

**Comment by urcades** [comment]
@litmus-ritten no problemo, I'm always happy to clarify decision trees or ambiguity in these issues, I'm often writing them in semi-shorthand
