### ISSUE TITLE
groups/talk: reply to message without thread

### ISSUE THREAD

**Issue by tinnus-napbus** [tloncorp/landscape-apps#1747]
oftentimes I don't wanna start a thread when I reply to a message, I just wanna quote-reference it inline. Currently I have to copy the message link and add it as an attachment. This is kinda annoying. It would be nice if there was a direct quote-reply button

**Comment by jamesacklin** [comment]
Thanks, we have a feature for this designed and planned. The reference-quote thing we did in Groups 1 always felt kludgy to me as well.

**Comment by jamesacklin** [comment]
@urcades Something to think about here: if someone else "replies" to the same message, would you expect a thread to be automatically created under the original message?
