### ISSUE TITLE
groups: renaming a channel in groups doesn't rename the url

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1756]
- Have a channel named content distribution
- Rename the channel in groups to kernel
- Observe post rename that the url still has content-distribution in it instead of kernel

**Comment by arthyn** [comment]
This is a fundamental way that channels were designed unfortunately so changing this would require significant re-architecture, but it can be done. There may also be a way to fake it, but it would be less reliable in that way.

**Comment by jamesacklin** [comment]
No reason to fix this, this would require a major refactor.

**Comment by zalberico** [comment]
What about not having the name in the url at all? I'd rather an ID than an incorrect name.
