### ISSUE TITLE
text wrapping in threads may interact strangely with scrollbar

### ISSUE THREAD

**Issue by Fang-** [tloncorp/landscape-apps#1758]
Bit of an oddball here. I opened a thread, and this is what I saw in the sidebar:

![basedjump](https://user-images.githubusercontent.com/3829764/213801921-83372a79-7e21-4d32-9821-d31cec790fa2.gif)

The scrollbar is trying to appear, reduces the width of the sidebar's contents, then wraps the url, massaging things in such a way that the scrollbar no longer appears... and then we repeat. Or something like that. Not actually sure what's going on here.

I can reproduce consistently in this thread, and have never seen it in others. Note that the "toggling" happens as fast as draw calls can happen, but the limited framerate of the gif makes it appear slower.

**Comment by jamesacklin** [comment]
Thanks. I think we need a bit more padding on the right side of the main chat window and threads in general.

**Comment by Fang-** [comment]
For the record I'm seeing this somewhat often now. Also for threads with only plaintext messages, so it's not a url-specific thing.
