### ISSUE TITLE
groups: group links don't work in threads

### ISSUE THREAD

**Issue by tinnus-napbus** [tloncorp/landscape-apps#1761]
**Describe the bug, optionally with screenshots**

if you're in a thread and you paste in a group link like `/1/group/~matwet/networked-subject` it swallows the link but doesn't show as an attachment

**To Reproduce**
1. paste group link in thread
2. nothing happens

**Expected behavior**
should be able to paste references into threads

**Additional context:**
- Ship type: planet
- Instance type: self-hosted
- OS/browser: qutebrowser and chromium on linux

**Comment by tinnus-napbus** [comment]
hmm it seems it actually *is* attaching stuff but it's just not showing the "1 attachment" thing when you're in a thread. Also a weird thing is when you X the attachment and leave the thread back to the main channel and try attach something again, it'll now say there are 2 attachments. If you repeat the process it'll say there are 3, 4, etc attachments

**Comment by jamesacklin** [comment]
Fixed by #1760
