### ISSUE TITLE
groups: channel permissions slightly ambiguous

### ISSUE THREAD

**Issue by tinnus-napbus** [tloncorp/landscape-apps#1762]
**Describe the bug, optionally with screenshots**

The "members can view" option in the channel permissions is a little ambigous, it took me a second to understand it meant "read only"

Edit: also "open to all" is also unclear. It implies non-members of a group could somehow read/write but that's not the case

![2023-01-21_12h56m45s](https://user-images.githubusercontent.com/77721746/213825472-0204a622-cdea-4e2c-b4cc-eed84d2cb0cd.png)

**Expected behavior**
should be clearer that it's readonly

**Additional context:**
- Ship type: planet
- Instance type: self-hosted
- OS/browser: qutebrowser / chromium on linux

**Comment by jamesacklin** [comment]
@e-shee Want to take a crack at this?

**Comment by e-shee** [comment]
Proposed copy channel permission changes below.

Current: Open to All
Edit: Open to All Members
Current: Anyone can read and write
Edit: Everyone can read and write

Current: Members Can View
Edit: Members Can Read Only
Current: Members can only view
Edit: Only admins can write

Current: Admin Only
Edit: No edit
Current: Only Admin can read and write
Edit: Only admins can view and write
