### ISSUE TITLE
groups & talk: apps do not have a source on first boot

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1771]
- Boot a new identity
- Observe that talk and groups have no upstream source
- Old ships also have their source set to their sponsor instead of the proper moon `sogryp-dister-dozzod-dozzod`
- I noticed this because users in UC help had their sponsor set to source for both of these (and as a result were not getting updates and were behind on kelvins)

@philipcmonk is working on a PR to fix this and we'll release it via `tloncorp/landscape`

**Comment by jamesacklin** [comment]
Sounds good, thank you. Will get this out with v2.5.0.
