### ISSUE TITLE
diary: note refs can be arbitrarily long

### ISSUE THREAD

**Issue by arthyn** [tloncorp/landscape-apps#1778]
> Going to mention here since this seems to be an issue for references to notebook posts. The reference that I experience when looking at a notebook post that is just plain text (because it is pure markdown that isn't being parsed, see #1610), the reference is to the entire notebook post and that makes the 'continue reading' button redundant. 
basically channel has a nearly endless scroll that looks like this for a recent post: 
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/82244264/210299446-d5d7dfc6-674c-4c11-a126-4c7e51a19c76.png">

_Originally posted by @thelifeandtimes in https://github.com/tloncorp/landscape-apps/issues/606#issuecomment-1369381508_

**Comment by tomholford** [comment]
Addressing this as part of #1664
