### ISSUE TITLE
notebook: encountering a gall error when I try and post to a notebook

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1790]
**Describe the bug, optionally with screenshots**
I'm currently encountering a bug that is preventing me from posting to a notebook in a group. After formatting some text and pressing the "Post" button, I see the following error in the devtools console:

```
gall: poke-as cast fail :diary [a=%json b=%diary-action-0]
[%bad-key 'listing']
/lib/diary-json/hoon:<[485 5].[508 7]>
/lib/diary-json/hoon:<[484 5].[508 7]>
/lib/diary-json/hoon:<[483 5].[508 7]>
/lib/diary-json/hoon:<[482 5].[508 7]>
[%key 'blockquote']
/lib/diary-json/hoon:<[485 5].[508 7]>
/lib/diary-json/hoon:<[484 5].[508 7]>
/lib/diary-json/hoon:<[483 5].[508 7]>
/lib/diary-json/hoon:<[482 5].[508 7]>
[%key 'inline']
[%key 'content']
[%key 'edit']
[%key 'delta']
[%key 'notes']
/lib/diary-json/hoon:<[360 12].[360 40]>
/lib/diary-json/hoon:<[360 5].[360 41]>
/lib/diary-json/hoon:<[359 5].[360 41]>
/lib/diary-json/hoon:<[358 5].[360 41]>
[%key 'update']
/sys/vane/gall/hoon:<[756 27].[756 45]>

onmessage @ index.88c2dd90.js:116
(anonymous) @ index.88c2dd90.js:115
(anonymous) @ index.88c2dd90.js:115
h3e @ index.88c2dd90.js:115
```

The visual state looks like this:

<img width="515" alt="Screenshot 2023-01-25 at 2 25 04 PM" src="https://user-images.githubusercontent.com/1195363/214666702-66a3f06a-a682-491e-b2c6-d8e31eae4ae3.png">

For some reason, I can write a single line of text to the post, but can't write out some structured text which includes lists, mentions, and imagery:

<img width="549" alt="Screenshot 2023-01-25 at 2 27 34 PM" src="https://user-images.githubusercontent.com/1195363/214667338-73571538-663a-4882-8945-c061be173b04.png">

**To Reproduce**
1. Go to a notebook you have write access to
2. Add an entry and format it with at least the following elements
    - Nested Unordered list
    -  Mention
    - image link
3. Attempt to post it
4. If you see an error, you've reproduced the bug

**Expected behavior**
I expect to be able to post a normally-formatted entry to a notebook without the interface blocking me

**Additional context:**
- Ship: planet — `~tonlur-hidlyn`
- Instance type: Self-hosted (Digital Ocean)
- MacOS Ventura — 13.0.1 (22A400)
- Safari — Version 16.1 (18614.2.9.1.12)
- Chromium — Engine Version 109.0.5414.87

**Comment by patosullivan** [comment]
@urcades can you produce the output for `+vat %groups`? I'm unable to repro this.

**Comment by jamesacklin** [comment]
@urcades Which one of your ships was this on? I see you listed both.

**Comment by urcades** [comment]
@jamesacklin updated the text to only list `~tonlur-hidlyn`

**Comment by urcades** [comment]
@patosullivan this is what I see:

```
> +vat %groups
%groups
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415]
  base hash:        0v1i.haeq1.catgc.rbk3e.dog5c.5godm.tpd5l.t9rla.81idi.hapm7.phgep
  %cz hash:         0v1i.haeq1.catgc.rbk3e.dog5c.5godm.tpd5l.t9rla.81idi.hapm7.phgep
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~sogryp-dister-dozzod-dozzod]
  updates:          remote
  source ship:      ~sogryp-dister-dozzod-dozzod
  source desk:      %groups
  source aeon:      10
  kids desk:        ~
  pending updates:  ~[[%zuse 416] [%zuse 415]]
::
```
