### ISSUE TITLE
find: link to FAQ when group is not found

### ISSUE THREAD

**Issue by tomholford** [tloncorp/landscape-apps#1796]
*originally posted by @urcades in the comments of #1794*

---

Any suggestion for improvement I'd have is dependent on copy recommendations from @e-shee , but my gut instinct is to render this as a single line of discretionary text. I sketched this out -really- quickly here:

<img width="832" alt="Screenshot 2023-01-26 at 12 12 07 AM" src="https://user-images.githubusercontent.com/1195363/214763062-28c004f4-c3f7-4393-ac69-77b3179f14fe.png">

https://www.figma.com/file/sCFYLlAGjehlYXUkT2rarg/branch/yonw9FxqhTxghFHdjHkLBH/Product-Handoffs-(Locked)?node-id=2638%3A95369&t=Y7zMQLvWKMEbX23q-1

Ideally, if we had robust FAQ/Support capability, I'd also recommend a "Learn more" link, for people who are curious about the edges of p2p networking and its implications on product design.

**Comment by e-shee** [comment]
This copy is clear to me. "Learn more" link makes sense in theory. What would it link to? Should have a period after it if we include.

**Comment by urcades** [comment]
@jamesacklin making a note/mention here that with the arrival of #2361 , issues like this might become easier to address/build
