### ISSUE TITLE
find: offer suggestions when no groups found

### ISSUE THREAD

**Issue by tomholford** [tloncorp/landscape-apps#1797]
*originally posted by @urcades in the comments of #1794*

---

Lastly, if you look to the frames below the linked one above, there are some additional search states that might be worth considering that we have yet to implement — in some cases (like a search that may have been mis-spelled, but comes close to a match in your network), I think the best outcome would be to find -something- we could recommend to people.

<img width="566" alt="Screenshot 2023-01-26 at 12 12 25 AM" src="https://user-images.githubusercontent.com/1195363/214763097-a18b0307-1ae2-4018-82a0-cd88a819b1f5.png">

<img width="621" alt="Screenshot 2023-01-26 at 12 12 22 AM" src="https://user-images.githubusercontent.com/1195363/214763099-c816fc68-56a1-49b3-93d1-c586f36bd2c4.png">

**Comment by urcades** [comment]
@jamesacklin making a note/mention here that with the arrival of #2361 , issues like this might become easier to address/build

**Comment by jamesacklin** [comment]
@dantish A relatively low-lift solution for users who don't get the path quite right when searching for a group. Return all groups hosted by the ship (`~sampel-palnet` in the case of *~sampel-palnet*/group)
