### ISSUE TITLE
contact-store: moons do not send or receive contacts

### ISSUE THREAD

**Issue by JohnRillos** [tloncorp/landscape-apps#1805]
**Describe the bug, optionally with screenshots**
I have two moons, `~mister-rivmud-fabwen` and `~topdev-rivmud-fabwen` that are able to DM each other, but neither can view profile info from the other (by profile info I mean nicknames, avatars, sigil colors, etc).
I added `~mister-rivmud-fabwen` to an existing group hosted by `~rivmud-fabwen`, but the moon and the planet also could not see each other's profile info.
I then joined Urbit Community as `~mister-rivmud-fabwen`, and was not able to see profile info for any other members.

If I run `:contact-store +dbug` it returns only the contact info for the moon itself, nobody else.

**Expected behavior**
I expect to be able to see other ships' nicknames, colors, bios, etc when using a moon.
I expect that when I join a group or DM as a moon, the other members can see my public profile.

**Comment by jamesacklin** [comment]
Currently doesn't work for new ships. Working on #1305 ASAP
