### ISSUE TITLE
groups: channel hosts should not be able to be kicked or banned

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1807]
Related: https://github.com/tloncorp/landscape-apps/issues/1765

It's a little weird that a channel host needs to be an admin to create the channel, but can then be removed as admin.

I think the whole channel hosts separate from group hosts in the current UX doesn't make sense (for it to make sense, groups would have to operate as a different type of abstraction?) - but as it is, probably if you're a channel host you should also be a group admin? Something about this is weird.

**Comment by jamesacklin** [comment]
It's weird but there's nothing inherently buggy or wrong about this. If they're demoted, they won't be able to make a channel again. 

Rephrasing to catch a more egregious case.

**Comment by zalberico** [comment]
What if they’re the only admin? Also weird they’d lose admin when they’re the host? They could just kill their ship or w/e. Seems like they shouldn’t be able to be non-admin.
