### ISSUE TITLE
gallery: twitter embeds do not render in safari

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1809]
**Describe the bug, optionally with screenshots**
What it says on the tin. Check out the video below for a better look at this bug:

https://user-images.githubusercontent.com/1195363/215001157-a42e28da-be78-4108-88d9-bc76efeb8982.mov

**To Reproduce**
1. Obtain a macOS device, and use safari to access a group with a collection within it. 
2. Click on a collection block containing a tweet
3. If the block does not render, you've duplicated the bug

**Expected behavior**
I expect twitter embed blocks to render as quickly as my networking allows.

**Additional context:**
- Ship: planet — `~tonlur-hidlyn`
- Instance type: Self-hosted (Digital Ocean)
- MacOS Ventura — 13.0.1 (22A400)
- Safari — Version 16.1 (18614.2.9.1.12)

**Comment by patosullivan** [comment]
This also applies to the twitter embeds in lightboxes in chat.
