### ISSUE TITLE
heap: unable to refresh curio detail view

### ISSUE THREAD

**Issue by tomholford** [tloncorp/landscape-apps#1811]
This is happening on master (unreleased); perhaps related to the heap state changes in #1784

![image](https://user-images.githubusercontent.com/16504501/215040141-69ceced7-a1ca-420f-a5f3-4f014d9fd499.png)

1. Navigate to a curio detail view
2. Refresh the page

**Comment by patosullivan** [comment]
Same thing is happening with diaries. Looking into it.
