### ISSUE TITLE
talk: messages disappear after receipt (or send)

### ISSUE THREAD

**Issue by Fang-** [tloncorp/landscape-apps#1815]
I've observed this with annoyingly high frequency in Talk. Most recently, I saw an incoming DM on-screen for a split-second, enough for me to start typing a response to it, and then the next moment I look and the incoming message is nowhere to be found. I send my response, and it never even shows up on my end. We continue chatting for a bit, I eventually refresh the page, and now both the missing messages show up.

Unclear yet under what conditions this happens, I cannot reliably reproduce it, but it's very much real. The other party in my DMs has reported a similar experience, but not always concerning the same messages.

**Comment by rabsef-bicrym** [comment]
I have experienced this situation as well. For what it's worth, my common chat modality is to write several, brief messages in a row.

**Comment by Fang-** [comment]
Some vague patterns of this I've noticed: messages disappearing briefly after showing up, but then re-appearing in the log once more new messages come in. Occasionally whole sequences of them will not show up, but then re-appear one-by-one in swift (~half-second) succession after some delay.

**Comment by jamesacklin** [comment]
Is this still occurring?

**Comment by rabsef-bicrym** [comment]
I'll keep an eye out for it. I think I had a disappearing message the other day but it's possible the interlocutor deleted, and I didn't ask.

**Comment by Fang-** [comment]
Seeing this again today, in combination with general slowness (and with it, more frequent disconnect banner) that may or may not be related. Certainly does hint at this being timing-sensitive in some way.
