### ISSUE TITLE
chat: clicking group/channel metadata on a ref doesn't do anything.

### ISSUE THREAD

**Issue by patosullivan** [tloncorp/landscape-apps#1817]
It should either navigate you to that channel/group or show a join modal afaik. @urcades @jamesacklin am I right?

![image](https://user-images.githubusercontent.com/1221094/215204729-a11d760f-a9af-4946-9bb0-36469348efab.png)

**Comment by jamesacklin** [comment]
Maybe, maybe not. If you expected it to, then maybe? 

We can handle this in #1675.
