### ISSUE TITLE
Clicking a group "Tirrel Support" from the sidebar makes the screen go black and never load

### ISSUE THREAD

**Issue by tacryt-socryp** [tloncorp/landscape-apps#1821]
<img width="1327" alt="Screenshot 2023-01-28 at 8 49 18 AM" src="https://user-images.githubusercontent.com/1377557/215273013-97d99cff-6e8d-4261-8348-4023bf69554a.png">

**Comment by lycurgus** [comment]
I'm seeing something similar when clicking on the `~lanlyd/terminal` group; the page spends a long time trying to load and then I get something like this on the load of `index.10df79c8.js`:

![image](https://user-images.githubusercontent.com/8443742/215323771-78f911b6-70a3-465a-aeae-5b380fdd384f.png)

If I try to reload it I seem to get `TypeError: Error in body stream` instead/as well?

Not sure if this is the exact same error but it seems to be the same behaviour - the screen goes white (light theme user) and never loads.

**Comment by patosullivan** [comment]
I can't repro this with that group. @tacryt-socryp what's your base hash for %groups?

@lycurgus your issue appears to be different, but I also can't repro it. What's your base hash?

**Comment by lycurgus** [comment]
```
> +vat %base
%base
  /sys/kelvin:      [%zuse 416]
  base hash:        0vm.3e4jl.d3dce.o5bhm.aavnu.obac8.8hc46.i06ur.31ge3.1jm15.f65bp
  %cz hash:         0vm.3e4jl.d3dce.o5bhm.aavnu.obac8.8hc46.i06ur.31ge3.1jm15.f65bp
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~wanzod
  source desk:      %kids
  source aeon:      129
  kids desk:        %kids
  pending updates:  ~
::
```

Which I think is the latest?

**Comment by lycurgus** [comment]
I tried to get a "cleaner" error by opening `~tirrel/the-marketplace` in a new tab with the browser tools already open (rather than clicking the link and letting it open a tab of its own) and it looks like the core is a 404 on `/~/scry/hark/group/~tirrel/the-marketplace/latest.json`. The page appeared to load for a moment, before redirecting as above.

I grabbed a HAR trace, if that helps diagnose?

**Comment by jamesacklin** [comment]
I also see a 404 for that scry, and 500s on a smattering of other groups.


Thanks, we'll take a look (and at least not crash the front-end if that scry doesn't come back).

**Comment by patosullivan** [comment]
I think this is a permissions issue, and will be fixed with: https://github.com/tloncorp/landscape-apps/pull/1832

**Comment by patosullivan** [comment]
I should clarify: the blank screen you're seeing will be fixed, I'm not sure what the underlying permissions issue is.

**Comment by jamesacklin** [comment]
Did this ever get resolved?
