### ISSUE TITLE
notebooks + gallery: comments cannot be deleted or have other secondary actions performed on them

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1825]
It appears as though comments added to gallery items or notebook posts are not able to be interacted with in a manner exposed by Talk replies/messages:

Galleries:

https://user-images.githubusercontent.com/1195363/215549030-c2e52953-5291-46c8-b732-eb7ed5f977e6.mov

Notebooks:

https://user-images.githubusercontent.com/1195363/215549050-4ec98cf4-b71a-45c9-8fd9-96e589a844fc.mov

While the omission of the "Message action bar" isn't critical to everyday usage, it still prevents "nice to have" secondary actions from being performed on messages, such as copying their location, or referencing them in other contexts.

More critically, comments that are unable to be deleted prevent an admin from being able to moderate their groups to their fullest potential. Right now, if someone were to issue profanities or other negative material on a notebook post, or gallery item, an admin couldn't address it at all.

**Comment by urcades** [comment]
While I've written this bug down on paper, I recognize that it requires a little bit of design input on how to gracefully display the action bar on space-constrained comments.

**Comment by jamesacklin** [comment]
IMO these should take the exact same visual form and styling as chat messages, with the same affordances. Let's keep things consistent. 

Whoever is working on this, see #1381 while you're here.
