### ISSUE TITLE
groups: in mobile viewports, un-anchor the list of "pinned" groups from the top of viewport

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1826]
While using the Groups webapp on a mobile device, I run into issues with the "All Groups" list:

https://user-images.githubusercontent.com/1195363/215556595-97923851-554e-41da-a89d-b726a1a68c00.MP4

Scrolling on this interface is hamstrung by a list of pinned groups staying "static", which reduces the scroll area for unpinned groups significantly.

In order to fix this, we should ensure that the list of pinned groups scrolls alongside the list of unpinned groups, as one large scrollable list, similar to how we implement the list of "All messages" in Talk.

See: #1185 which had similar implications for Talk.

**Comment by zalberico** [comment]
I think this is a dupe of #1824

**Comment by urcades** [comment]
@zalberico correct! Closing
