### ISSUE TITLE
groups: while using a mobile device, tapping notifications yields no redirect

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1827]
While using the Groups webapp on a mobile device, attempting to tap into a notification does not redirect me to its trigger:

https://user-images.githubusercontent.com/1195363/215558767-c4676bef-1eab-414f-9777-c6c2a432ed82.MP4

It's hard to see in this video, but I have a series of blue notifications that I'm tapping one at a time to see where they lead me. None of them appear to function correctly. The experience I'm witnessing on mobile essentially renders the notifications interface completely unusable.

**Comment by jamesacklin** [comment]
Address while completing #1691.
