### ISSUE TITLE
groups: info editor needs to give better feedback about errors

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1833]
- Be a group admin of a public group
- Have a bad value in icon field
- Change privacy to secret and click save
- Observe nothing happen (no response from button, nothing in the console, nothing after refresh).

Specifically I was trying to set remote life to secret on nibset-napwyn.

**Comment by tomholford** [comment]
Per the attached clip, unable to repro. Changed it from Public --> Secret, hit Save, there was a loading spinner until it finished. Then I hit refresh and it showed the group as Secret. 

https://user-images.githubusercontent.com/16504501/216012964-8be4797e-3dd0-493e-8696-9e9d86149d0a.mov

I then spinned up another fake ship and searched `~zod`:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/16504501/216013350-e0a4b354-44d8-4045-ae82-37956c275045.png">

Here are the subscription updates in the console, per the final one (secret: true) it appears to be working 

<img width="447" alt="image" src="https://user-images.githubusercontent.com/16504501/216012275-e1d3c3f5-8323-49a5-bd1a-2d168548bf80.png">

@zalberico Is it possible one of the other fields in the Group Info form has some data that is causing the save to fail?

**Comment by tomholford** [comment]
@jamesacklin FYI unassigned myself and moved this ticket to Awaiting Info in light of the findings in the previous comment.

**Comment by jamesacklin** [comment]
Cool, thank you

**Comment by arthyn** [comment]
So this was actually just an issue in the fields of the form above, somehow it got a bad value in the icon field. Going to change the issue info.

**Comment by tomholford** [comment]
> So this was actually just an issue in the fields of the form above, somehow it got a bad value in the icon field. Going to change the issue info.

@arthyn What was the bad value?

**Comment by arthyn** [comment]
it was like some whitespace and then a hash

**Comment by zalberico** [comment]
Nice - thanks for looking (and setting it to secret for me) CC: @e-shee for context
