### ISSUE TITLE
talk: ui shows pinned when no channel is pinned

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1835]
- Pin a group in groups, but don’t pin anything in talk 
- On mobile go to talk
- Observe there’s an empty pinned section at the top

![61780603-C5D5-4F9F-A545-6D7BD56FB6CB](https://user-images.githubusercontent.com/441466/215806641-36a3dc5d-a34b-4d91-b5e4-53b19615e737.jpeg)

There should only be a pinned section if channels in talk are pinned. Only pinning a group shouldn’t add it.

**Comment by jamesacklin** [comment]
See while addressing #1824.
