### ISSUE TITLE
Groups Left Nav: Long list of Pinned Groups makes full list of groups unusable (little scroll space)

### ISSUE THREAD

**Issue by marisarow** [tloncorp/landscape-apps#1836]
**Describe the bug, optionally with screenshots**
I have a lot of pinned groups. Because the pinned section is static (it should by dynamic - scrollable) it is very difficult to scroll through other groups.

**To Reproduce**
<img width="250" alt="Screen Shot 2023-01-31 at 11 40 13 AM" src="https://user-images.githubusercontent.com/10634823/215827447-973bb346-555a-4f0f-86c7-370f5a6ed1a6.png">

**Expected behavior**
Pinned and All Groups should scroll in tandem. Aka pinned and all groups should act as one list as opposed to stack lists.

**Comment by jamesacklin** [comment]
Related to #1836, just wrap this entire list in the virtualizer
