### ISSUE TITLE
landscape&groups: mark all unread takes multiple attempts to work

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1846]
- Have unread notifications
- Click mark all unread
- Observe really nice spinner! (https://github.com/tloncorp/landscape-apps/issues/1731)
- Observe spinner resolve quickly and nothing happen
- Click mark all unread again
- Observe spinner take longer to resolve and then unreads become read

This is typically me clicking this in long running tabs.

**Comment by jamesacklin** [comment]
This works very reliably now in Groups. We have tloncorp/landscape#75 to fix the spinnerless button in Landscape.
