### ISSUE TITLE
groups: can't invite to secret group

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1847]
- Be in a secret group as a non-admin (this was the guild)
- Attempt to invite someone (either from the group invite menu pop up or from the group member page)
- Observe the failure below

<img width="1341" alt="Screenshot 2023-02-01 at 8 35 30 AM" src="https://user-images.githubusercontent.com/441466/216105241-c3469bfa-2248-4352-8232-d541daae1137.png">

**Comment by zalberico** [comment]
Turned out Luke was already in the group and I didn't notice, but the error doesn't tell me that it just shows an exclamation point.

<img width="550" alt="Screenshot 2023-02-01 at 8 35 00 AM" src="https://user-images.githubusercontent.com/441466/216105535-ebac7d57-9dba-4a31-bd2c-32dcabf516a2.png">

**Comment by jamesacklin** [comment]
This is a simple case of the Invite button appearing for non-admins.

Would you expect to be able to do this? Or would you expect secret invitations to be relegated to admins only?

**Comment by zalberico** [comment]
I'd probably expect to be an admin config (and I hate config), but something like: allow members to invite others to group.

If I had to choose, I'd probably allow members to invite by default since the group is 'secret' from public discovery but if you're a member it seems reasonable you can add others? There's the first rule of fight club, but they do get new members somehow. Admins can always kick, seems better for it to be a cultural norm vs. default restriction imo.

**Comment by jamesacklin** [comment]
Fixed in the latest version; non-admins can't invite people on-network or via Lure links to private or secret groups.
