### ISSUE TITLE
talk: clicking into a DM does not redirect/link to correct DM

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1848]
**Describe the bug, optionally with screenshots**
I'm encountering a rather serious(?) issue in which I see that an urbit is DMing me, it has a blue unread dot, and when I click into it to read it, I'm redirected to a completely unrelated DM. Watch this video to see what I mean:

https://user-images.githubusercontent.com/1195363/216106463-e64cba9d-aa54-46cc-b516-13335b41ae21.mov

I click to chat with ~solfer-mafed, and am redirected to a DM with ~simfur-witwed, when I leave this latter chat, and try to access the first DM, I'm redirected to a chat with ~wicdev. I'm unable to click into the initial DM and view it.

**Expected behavior**
I expect to click on a DM and be brought to the DM in question, not an unrelated one

**Additional context:**
- Ship: planet — `~fabled-faster`
- Instance type: Tlon-hosted
- MacOS Ventura — 13.0.1 (22A400)
- Safari — Version 16.1 (18614.2.9.1.12)
- Chromium — Engine Version 109.0.5414.87

**Comment by philipcmonk** [comment]
This is also happening for me since yesterday.  Happens when clicking on any non-group dm, I'm on hash blu1o for %talk
