### ISSUE TITLE
groups&talk: deleting a message sometimes appears to hang

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1851]
- Write and send a message
- From the hover menu select the red X to delete it
- Observe it sometimes appear to do nothing before it eventually deletes

We should have some way to communicate in-progress state to the user (for sends we do the `>>` arrows, for others we use a spinner, not sure the proper answer for this case - maybe grey out the message and then remove?).

**Comment by jamesacklin** [comment]
See #1852. Please locate the in-progress spinner in the red confirmation button in the dialog.
