### ISSUE TITLE
[groups]: whole sidebar should be scrollable container, not just the "unpinned" groups

### ISSUE THREAD

**Issue by tacryt-socryp** [tloncorp/landscape-apps#1857]
Unpinned groups are unusable because the container is so small.
<img width="258" alt="Screenshot 2023-02-02 at 7 56 05 AM" src="https://user-images.githubusercontent.com/1377557/216343918-493d4fcc-23ca-47f2-9950-5555aa061293.png">

**Comment by jamesacklin** [comment]
Thanks. We're working on this: #1836, #1824, #1835
