### ISSUE TITLE
Failed to fetch dynamically imported module: <redacted>/apps/groups/assets/DiaryAddNote.fbf168ef.js

### ISSUE THREAD

**Issue by belisarius222** [tloncorp/landscape-apps#1858]
```
TypeError: Failed to fetch dynamically imported module: https://r<redacted>/apps/groups/assets/DiaryAddNote.fbf168ef.js
```

This happens each time I try to edit a particular notebook post.

**Comment by belisarius222** [comment]
groups desk hash: 0v14.uaijd.99pd5.ro0ip.l52b8.0jipd.4dcak.9ksp7.ql6ep.v4v5u.s1dop

**Comment by patosullivan** [comment]
Dupe of #1733 

It's an issue with janeway not globbing files with filenames that were not all lowercase letters. We've stopped using janeway, so this should be fixed on the next release.
