### ISSUE TITLE
groups: no invites sent during group creation

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1867]
**Describe the bug, optionally with screenshots**
You can successfully invite people to a group after it's created, so we know invitations work. However, the final (confusing: #1365) step of the group creation process implores you to invite some people to your new group. They will never get that invitation.

**To Reproduce**
1. Create a new group and don't immediately dismiss the final Invite step.
2. Invite some ships you have the keys to.
3. Watch those invites never land.
4. Click through to the new group and invite some other ships you have the keys to.
5. See invites.

**Expected behavior**
Both actions should work identically.

**Comment by arthyn** [comment]
this actually does work but the actions required here are dumb. for some reason you have to hit enter twice, but if you do that it will actually send the invites.

this does nothing:
![Screen Shot 2023-02-03 at 10 21 54 AM](https://user-images.githubusercontent.com/5466421/216654205-65e4e24c-5650-4ac7-b48e-02e73a97bdd7.png)

this actually does invites:
![Screen Shot 2023-02-03 at 10 22 17 AM](https://user-images.githubusercontent.com/5466421/216654257-0d20df1b-a656-4ac4-9564-3cba54300ca1.png)

**Comment by jamesacklin** [comment]
Our work is clear.
