### ISSUE TITLE
perf: Talk maxing out CPU

### ISSUE THREAD

**Issue by tomholford** [tloncorp/landscape-apps#1870]
Noticed that my battery drained rapidly. Not the first time I've seen this, or that it's been reported #1617.

<img width="299" alt="image" src="https://user-images.githubusercontent.com/16504501/216556687-79c4f2da-c8dc-4beb-a50d-3476c635062b.png">

This time I was able to record a performance profile in devtools, uploaded [here](http://0x0.st/oCot.json)

**Comment by philipcmonk** [comment]
Saw this today as well, but it went away when I changed to the tab, so I wasn't able to get a performance profile

**Comment by tomholford** [comment]
Just saw it again. Seems to be happening after a network disconnect / extended idle

<img width="297" alt="image" src="https://user-images.githubusercontent.com/16504501/221682350-a3c8c2fa-2d3c-4868-9f87-1e8a2e2bcc5d.png">

**Comment by arthyn** [comment]
I think we fixed most instances of this let us know if it crops up
