### ISSUE TITLE
groups: user does not receive notifications for comments on gallery items

### ISSUE THREAD

**Issue by patosullivan** [tloncorp/landscape-apps#1872]
**Describe the bug, optionally with screenshots**
If a user makes a gallery item and later receives a comment, the user that posted it will not be notified.

**To Reproduce**
1. Create a gallery item.
2. Have another user create a comment on it.
3. Notice that you don't receive a notification.

**Expected behavior**
User should received a "commented on:" notification, similar to notes.

**Comment by jamesacklin** [comment]
See also: https://github.com/tloncorp/landscape-apps/issues/1718
