### ISSUE TITLE
groups&talk: data retention and deletion

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1877]
- The major source of loom usage is from historical chats.
- As time goes on chat history fills up loom space and OTAs fail due to running out of memory
- We have pack, meld, 4gb loom (and soon 8gb loom) all to give us some more space but that's just fighting the inevitable, without the ability to delete old chats it'll eventually fill up.

The true fix for this is 64bit loom which can use massive amounts of memory, but that also requires faster nock execution (new mars) to be practical.

If we can allow the user to delete historical chat data (some subset of which most users don't care about anymore) we can restore a lot of loom space in the short term. This is ultimately a product feature around setting data retention policies for chats and groups (in addition to allowing users to delete old local history outside of retention policy). It may also be good to allow users to download an archive in some form too.

Note that `chop` (the one-off event log truncation tool) doesn't help this because that reduces the size on disk of the pier and this is about the loom (memory) size.

**Comment by patosullivan** [comment]
I could see a user setting for "store x months/years" of chat data from groups, and anything older than that they'd have to request from the group host. Could also see group hosts setting a hard cap on what they're willing to store.

**Comment by zalberico** [comment]
Yeah - I'd let the user have the option to store it forever if they want to, but also set retention. Same for the group hosts. Outside of retention I think you should also be able to delete old data too.

**Comment by tomholford** [comment]
Open questions to keep in mind while speccing this feature:

- How will search performance be affected by a large archive (e.g. infinite retention)?
- Will there be a "sensible default" retention window?
- How should the retention window be communicated? Will new users expect to find old messages before the retention window?
