### ISSUE TITLE
Uploading new avatar/header image sets it as both

### ISSUE THREAD

**Issue by jrrmyr** [tloncorp/landscape-apps#1880]
**Describe the bug, optionally with screenshots**
Uploading a new avatar image sets it as both the avatar *and* the header, and vice versa.

**To Reproduce**
1. Open Groups
2. Go to your user profile
3. Click Upload Image to upload a new avatar image
4. Image gets set as both the avatar and the header!

**Expected behavior**
Uploaded image should become the avatar and *not* the header. 

**Additional context:**
- Ship type: Planet
- Instance type: Self hosted with CLI, digitalocean S3 instance
- OS/browser: Firefox on Linux

**Comment by jamesacklin** [comment]
Still around.
