### ISSUE TITLE
groups: invites to secret groups show no metadata

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1881]
**Describe the bug, optionally with screenshots**
Invites to secret groups--even those issued by an administrator (see #1847)--don't show any metadata whatsoever on the receiver side. Secret groups are, in fact, quite secret.

![image](https://user-images.githubusercontent.com/748181/217012972-48277b54-2c17-4512-81bc-1a015f138071.png)

Manifests in tloncorp/lure#37

**To Reproduce**
1. Make a new Secret group on Ship A.
2. Invite Ship B.
3. Observe the above--no name or metadata, just Acccept/Reject.

**Expected behavior**
By invitation, I should see the metadata for the group on Ship B.

**Comment by patosullivan** [comment]
Can't repro via a normal invite, probably need to invite through %lure, but it's currently broken for me (see: https://github.com/tloncorp/lure/issues/40)

**Comment by jamesacklin** [comment]
This wasn't through Lure, it was through the mainnet Groups UI with two ships that know about one another.

**Comment by patosullivan** [comment]
Ah ok, well I can't repro it on current master (either through lure or through a normal invite).

**Comment by jamesacklin** [comment]
Works now?
