### ISSUE TITLE
Attempting to message someone in a multiparty DM has inconsistent behavior

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/landscape-apps#1882]
**Describe the bug, optionally with screenshots**
DMing individual retrieves multiparty DM individual is also in when the multiparty DM is more recent. 

**To Reproduce**
1. Have multiparty DM with someone in it that you haven't messaged since the multiparty DM was created
2. Attempt to message individual using 'New Message' flow. Enter @p, hit enter.
3. Multiparty DM loads instead of individual DM
4. Using left nav list of DMs, scroll to individual DM with @p entered, message individual
5. Repeat step 2.
6. Individual DM loads

**Expected behavior**
I would expect the individual DM to be loaded. 

**Additional context:**
- may be related to [this issue](https://github.com/tloncorp/pocket/issues/240).

**Comment by jamesacklin** [comment]
@patosullivan has a repro--he has never DM'd with @sigilante but is in a multi-DM with him; entering Neal's @p into a new DM routes Pat to the multi-DM.

**Comment by sigilante** [comment]
sneaky!
