### ISSUE TITLE
feature request: pipe generator output to chat

### ISSUE THREAD

**Issue by belisarius222** [tloncorp/landscape-apps#1887]
It would be very convenient for support to be able to run something like this:
```
~zod:dojo> talk|post [our %my-channel] +vats
```
or
```
~zod:dojo> talk|post [our %my-channel] +vat %base
```

and have the result be copied into a new post in a chat channel.  I *think* dojo syntax supports this sort of thing -- if not, we should think hard about how to make that work.

(Maybe I got the syntax wrong and it would be more like `talk!post ...`, I don't remember offhand)

**Comment by jamesacklin** [comment]
Cosigned. I'll track down some estimates.
