### ISSUE TITLE
groups&talk: never show blue dot for join/leave notifications 

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1888]
- see a blue dot at the group level on mobile
- Click the group 
- Observe no blue dots in any channels
- Be confused
- Look at notifications panel on mobile
- Observe someone joined the group

Blue dots for these seem like bad UX. I interpret it to mean there’s an unread message when there’s not and to clear it I have to go to a separate menu and hit the mark as read button.

**Comment by jamesacklin** [comment]
Should have been fixed with #1795?
