### ISSUE TITLE
groups: group ref spacing in threads hurts

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1897]
The host ship runs into the "Join" button, there's an extra space between the name and "by", and there's no spacing between adjacent refs.

![Image](https://user-images.githubusercontent.com/748181/217619973-d211f663-ce04-429b-b10d-f6733fdfae6d.png)

**Comment by patosullivan** [comment]
This one was fixed with #1998 

![image](https://user-images.githubusercontent.com/1221094/223105853-7d51547d-39e1-4e7f-9857-9deb83ffea03.png)
