### ISSUE TITLE
Easy to accidentally delete a message

### ISSUE THREAD

**Issue by marisarow** [tloncorp/landscape-apps#1904]
<img width="1020" alt="Screen Shot 2023-02-09 at 11 57 49 AM" src="https://user-images.githubusercontent.com/10634823/217884359-7931d832-d32a-4d7d-bf1a-cbfe67fec5f5.png">

Might be worth revisiting the design so that users don't accidentally delete a message when they are trying to copy, thread, etc.

**Comment by marisarow** [comment]
<img width="1018" alt="Screen Shot 2023-02-09 at 12 00 24 PM" src="https://user-images.githubusercontent.com/10634823/217884899-4b85f0b9-4697-40ad-93f0-870ae668b086.png">

**Comment by jamesacklin** [comment]
Check it out: #1892
