### ISSUE TITLE
groups, talk: group refs show a reject button

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1910]
![DB872BC7-A7A5-4882-8D77-DAD7D67EF612](https://user-images.githubusercontent.com/441466/218110231-f5ec9d0d-49dd-4084-95c8-d458170807a3.jpeg)

Reject in that image is weird, there’s no need for it.

**Comment by jamesacklin** [comment]
Fortunately, clicking it doesn't do anything destructive.
