### ISSUE TITLE
Group load is slow. Caused spontaneous refresh.

### ISSUE THREAD

**Issue by marisarow** [tloncorp/landscape-apps#1913]
**Describe the bug, optionally with screenshots**
First load of a group is very slow. When he opened Tlon Public, gallery and notebooks weren't loading content, but were showing the ability to add content (which is wrong based on our permissions). Eventually, the window actually hard refreshed itself and then galleries and notebooks were showing appropriately (with no ability to add content).

**Comment by jamesacklin** [comment]
Should be fixed with #1902, but keeping around for a test case.

**Comment by jamesacklin** [comment]
Fixed by #2100
