### ISSUE TITLE
Certain lengths of text in threads make rendering twitchy

### ISSUE THREAD

**Issue by ashelkovnykov** [tloncorp/landscape-apps#1919]
**Describe the bug, optionally with screenshots**
Certain "perfect storm" lengths of text appear to make the thread view rendering twitchy:
<img src="https://0x0.st/Hrqq.gif" alt="example" width="400"/>

(Ignore the other visual oddities - those are artifacts from recordig/`gif` conversion)

**To Reproduce**
1. Not sure - could try to reproduce the error by making a thread with the exact same conversation?

**Expected behavior**
Thread view should be rendered without twitching.

**Additional context:**
- Ship type = planet
- Instance type = self-hosted
- Chromium-based browser on Pop!_OS 22.04

**Comment by jamesacklin** [comment]
Duplicate of #1750

**Comment by patosullivan** [comment]
I think it's actually a duplicate of #1758

**Comment by jamesacklin** [comment]
That's what I meant. :)
