### ISSUE TITLE
groups: when a channel is down, inform the user

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1920]
- UC Help goes offline
- Lots of people attempt to post in the channel and are confused
- I realize dopzod is down and fix it
- All the comments stream in

We should notify loudly in the UI when the group host is offline.

This will both help us bring the host back online, and help users know what's going on.

**Comment by jamesacklin** [comment]
This would be a good feature.

**Comment by arthyn** [comment]
Something like online, busy, offline/unknown would be good. We just need an innocuous subscription here to try and then time it.

**Comment by jamesacklin** [comment]
Can we do this in Chat channels with one of our system chat message types? e.g. "~sampel has joined the chat" in Talk.

Better yet, we could replace the message input placeholder.

**Comment by arthyn** [comment]
I was thinking more of a steady state kind of colored dot or something

**Comment by jamesacklin** [comment]
Either way, if it manifests as a hook, we can do whatever we want. I support it

**Comment by jamesacklin** [comment]
https://github.com/tloncorp/landscape-apps/issues/2414#issuecomment-1524715912
