### ISSUE TITLE
talk: help + support menu occludes text input in chat

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1924]
![Screenshot 2023-02-13 at 11 30 59 AM](https://user-images.githubusercontent.com/441466/218555762-5e97fb12-c610-4953-9545-4b506c037244.jpeg)

**Comment by jamesacklin** [comment]
As designed.

**Comment by zalberico** [comment]
@arthyn There's a lot of space on the bottom right area on both mobile and desktop where the question menu would maybe fit better?

![Screenshot 2023-02-15 at 9 57 06 AM](https://user-images.githubusercontent.com/441466/219113389-b369d6d9-e2ef-4cbc-a7ed-c74e2607dd24.jpeg)

**Comment by arthyn** [comment]
I feel like it would be somewhat distracting there. I don't think we've truly found the best place for this and ultimately I think it will evolve as we develop the idea of global "system" chrome.
