### ISSUE TITLE
talk: text in chat gets wiped

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1925]
- Be writing a message in a dm
- Take longer than 10s to send it
- Observe it get wiped

This was an issue I think was solved but appears to have been reintroduced in a regression as of this morning (Feb 13th)

**Comment by Fang-** [comment]
I saw it get wiped when the "you are offline" (aka lag indicator) popped up, so probably has to do with re-rendering, which I vaguely recall hearing was the issue previously as well.

**Comment by tomholford** [comment]
Also just encountered this, luckily I did not lose too much of a draft. Marking sev 1
