### ISSUE TITLE
New DM breaks on first message

### ISSUE THREAD

**Issue by galenwp** [tloncorp/landscape-apps#1927]
**Describe the bug, optionally with screenshots**
When I go to create a fresh DM with an unknown ship, my first message doesn't seem to go through. 

**To Reproduce**
1. Create a DM with some @p
2. Send a message
3. See an error in the console.

**Expected behavior**
A message going through

**Additional context:**
- OS/browser: Safari on MacOS

<img width="983" alt="Screen Shot 2023-02-13 at 1 43 25 PM" src="https://user-images.githubusercontent.com/1467211/218581784-1ca1c034-9909-4861-83bd-c9bb59ba2068.png">

**Comment by jamesacklin** [comment]
I reproduced in Chrome with the following steps:

1. Open Talk
2. DM ~nec
3. Get gall error in the browser console:

```
gall: poke-as cast fail :chat [a=%json b=%dm-action]
syntax error
{1 5}
[%key 'ship']
/sys/vane/gall/hoon:<[771 27].[771 45]>
```

**Comment by patosullivan** [comment]
I'm not seeing the gall error, I see a 404 for a scry.

**Comment by patosullivan** [comment]
Looks like that 404 is not the issue, though.

**Comment by patosullivan** [comment]
I see what it is, changes around making DMs optimistic.
