### ISSUE TITLE
chat: emoji modal won't stay open on subsequent messages from the same user

### ISSUE THREAD

**Issue by patosullivan** [tloncorp/landscape-apps#1950]
If a user sends more than one message in sequence and you try to react to one of the subsequent messages the emoji modal will close as soon as you move your mouse away from the chat message options.

Certainly related to changes with handling hover state on ChatMessageOptions.

**Comment by arthyn** [comment]
I've actually seen this way back, but forgot to put up an issue. There's a lot of high level rerenders likely causing this.

**Comment by patosullivan** [comment]
Have you seen it consistently? I do remember it happening a long time ago, but it seems to be happening very consistently since we deployed internally yesterday.

**Comment by arthyn** [comment]
from what I remember it was consistent, but it was also a while ago so not sure
