### ISSUE TITLE
groups: thread notifications lead to unexpected double state

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1951]
- Get notification in Groups Home like below
![Screenshot 2023-02-15 at 9 39 32 AM](https://user-images.githubusercontent.com/441466/219109536-ee46c094-fd88-4ade-8090-7d98ae94c764.jpeg)
- Click it and see this thread (which has nothing on the left panel that it's threading off of visible)
![Screenshot 2023-02-15 at 9 39 37 AM](https://user-images.githubusercontent.com/441466/219109618-5be1e52b-1ae1-4b4b-bd4c-6516dccefd3a.jpeg)
- Search around and find that thread with extra content and missing my reply?
![Screenshot 2023-02-15 at 9 39 43 AM](https://user-images.githubusercontent.com/441466/219109630-6c93eaba-f955-4259-a218-96ccc099855c.jpeg)

**Comment by arthyn** [comment]
think this is fixed as of a few releases ago
