### ISSUE TITLE
groups, talk: group links render with overlapping text

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1966]
![Screenshot 2023-02-16 at 4 55 16 PM](https://user-images.githubusercontent.com/441466/219522036-fd8f7ac7-92e1-43fe-8179-30e81fd19907.jpeg)

I'm not sure these have to be as small as they currently are - if we made them more like apple iOS references in text (more like a large rectangle) we could have a nice group image and all the info without it being squished like this.

**Comment by jamesacklin** [comment]
You saw this in the Gallery context, yes?

**Comment by zalberico** [comment]
I've seen it in gallery and in threads

**Comment by jamesacklin** [comment]
Fixed in #1991
