### ISSUE TITLE
Wayfinding help and support links to Tlon public notifications

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/landscape-apps#1979]
**Describe the bug, optionally with screenshots**
When already a member of Tlon Public, clicking Help and Support in the Wayfinding bug menu you navigate to to the notifications screen for Tlon Publoc

**Expected behavior**
You should be invited to join Tlon Public if not already a member, and dropped in to the support channel if already a member. 

**Additional context:**
- self-hosted planet
- chrome on iOS

**Comment by patosullivan** [comment]
This is a good idea, but we don't really have a way for group admins to say "always show this screen by default". Should we? Otherwise we're going to be hardcoding this for *just* tlon public somewhere.
