### ISSUE TITLE
chat: unable to leave emoji reaction on mobile web

### ISSUE THREAD

**Issue by alecananian** [tloncorp/landscape-apps#1980]
**Describe the bug, optionally with screenshots**
Unable to leave emoji reaction on mobile web, the emoji selection box is auto-dismissed just after it appears

**To Reproduce**
1. Go to any channel
2. Tap on a message to get context menu to show
3. Tap on emoji reaction item

**Expected behavior**
Emoji selection box appears and allows me to select an emoji reaction

**Additional context:**
- Tlon-hosted planet
- Firefox on Android

https://user-images.githubusercontent.com/1013230/220159391-6da0a16e-9de7-418f-8a1d-6ab6e501bd7a.mp4

**Comment by patosullivan** [comment]
I can repro. This seems to be a firefox specific issue.

**Comment by patosullivan** [comment]
I repro'd this on my ship that's using the ~binnec version of the app earlier today, but after the latest update to binnec I'm not seeing it anymore. @alecananian are you still seeing this?

**Comment by patosullivan** [comment]
Confirmed with alec that this issue has been fixed.
