### ISSUE TITLE
groups, talk: pasting two references has unexpected behavior

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1987]
- Copy a group link
- Paste it in a chat
- Copy a second group link
- Paste it in a chat
- Observe that it appears like the second copy didn't work
- Send the chat
- Observe the second copy did work, but overwrote the first one

This is unexpected imo, we should show more metadata about the reference, allow multiple references or some combination of both.

**Comment by patosullivan** [comment]
Afaict this actually does work. Just tested:



![Image](https://user-images.githubusercontent.com/1221094/224825019-5ab052cd-4224-4af4-8ed3-ba209fbe1bc8.png)
