### ISSUE TITLE
groups: new channel manager bugs

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#2000]
Renaming a section shuffles it to the beginning of the list. I'd expect the section to stay in place.

![rename-reorder](https://user-images.githubusercontent.com/748181/221012738-6ff58f31-e592-40a3-b67b-6078eacc2869.gif)

Changing permissions on a channel appears to never update after the modal closes. A refresh fixes this. Changing the name or default-join status behaves as expected.

![perms](https://user-images.githubusercontent.com/748181/221013074-902d157b-47da-47e6-a299-fe98fe4bd4a1.gif)

_Originally posted by @jamesacklin in https://github.com/tloncorp/landscape-apps/issues/1995#issuecomment-1442331768_

**Comment by patosullivan** [comment]
Changing the name of a section also causes the channels in that section to re-arrange. I've got a fix coming for that along with these other fixes.
