### ISSUE TITLE
Permission denied to access property "getAttribute"

### ISSUE THREAD

**Issue by pvblick-vniversal-friend** [tloncorp/landscape-apps#2008]
### Context

Got this while on Talk, with the following error:

```
u/<@https://taglys-mocmun.tlon.network/apps/talk/assets/index.801d2f9e.js:136:40255
u@https://taglys-mocmun.tlon.network/apps/talk/assets/index.801d2f9e.js:136:40199
gP@https://taglys-mocmun.tlon.network/apps/talk/assets/index.801d2f9e.js:136:40486
uxe</<@https://taglys-mocmun.tlon.network/apps/talk/assets/index.801d2f9e.js:176:15639
jpe@https://taglys-mocmun.tlon.network/apps/talk/assets/index.801d2f9e.js:97:6696
e.unstable_runWithPriority@https://taglys-mocmun.tlon.network/apps/talk/assets/index.801d2f9e.js:82:3886
A0@https://taglys-mocmun.tlon.network/apps/talk/assets/index.801d2f9e.js:93:38710
Hh@https://taglys-mocmun.tlon.network/apps/talk/assets/index.801d2f9e.js:97:6157
eD@https://taglys-mocmun.tlon.network/apps/talk/assets/index.801d2f9e.js:95:10817
NY/<@https://taglys-mocmun.tlon.network/apps/talk/assets/index.801d2f9e.js:93:38933
e.unstable_runWithPriority@https://taglys-mocmun.tlon.network/apps/talk/assets/index.801d2f9e.js:82:3886
A0@https://taglys-mocmun.tlon.network/apps/talk/assets/index.801d2f9e.js:93:38710
NY@https://taglys-mocmun.tlon.network/apps/talk/assets/index.801d2f9e.js:93:38881
zc@https://taglys-mocmun.tlon.network/apps/talk/assets/index.801d2f9e.js:93:38814
XK@https://taglys-mocmun.tlon.network/apps/talk/assets/index.801d2f9e.js:97:18389
Ohe@https://taglys-mocmun.tlon.network/apps/talk/assets/index.801d2f9e.js:93:17671

```

But I had a similar error pop up constantly. It has showed up at least 150 times today.

**Comment by jamesacklin** [comment]
@pvblick-vniversal-friend Thanks for reporting. Do you happen to remember what you were doing when you encountered this error for the first time? Also, what browser and OS are you using?

**Comment by jamesacklin** [comment]
@pvblick-vniversal-friend Thanks, getting it through the pipeline now.

Additional context, possibly to narrow down root cause: this happens when @pvblick-vniversal-friend clicks "Create a Group" in Firefox.

**Comment by pvblick-vniversal-friend** [comment]
> Additional context, possibly to narrow down root cause: this happens when @pvblick-vniversal-friend clicks "Create a Group" in Firefox.

Here's a screenshot I get before the error window:

![image](https://user-images.githubusercontent.com/83452350/222531624-aac687a7-1449-4429-a8f0-04888750e9b5.png)

**Comment by pvblick-vniversal-friend** [comment]
## UPDATE

Seems like there might be some Firefox privacy setting that causes the problem.

I haven't faced the same issue using Landscape on Chrome.
Brave also seems to work.

I will try to figure out what causes this on Firefox from my end too.

**Comment by jamesacklin** [comment]
@pvblick-vniversal-friend Thanks for the update. We're unable to reproduce with your setup (Win11 / FF / Mullvad VPN / uBlock Origin) but we'll keep trying. 

Keep us updated with what you find; good to hear you're on and everything is working.
