### ISSUE TITLE
Duplicate %facts arrive after sending a %club-action poke

### ISSUE THREAD

**Issue by polrel-witter** [tloncorp/landscape-apps#2009]
**Describe the bug, optionally with screenshots**
If an external agent is subscribed to a given `/club/<club-id>/ui` wire and sends a message via a `%club-action` poke with `$echo:club` set to `0`, we receive duplicate messages in return. If we set `$echo:club` to `1`, we receive a single message in return. 

**To Reproduce**
This is the card which produces the duplicate %facts:
```
:-  %club-action
!>  ^-  action:club:chat
=/  memo:chat [~ our.bowl now.bowl %story ~ msg]
[club-id *echo:club:chat %writ [our now]:bowl %add memo]
```

**Expected behavior**
We only expect one fact in return; the message we sent without a duplicate. 

**Additional context:**
- Fake ~zod
- CLI
- This was discovered in the process of expanding `%talk-cli`'s features.

**Comment by arthyn** [comment]
I think this is fixed in latest if I understand correctly.
