### ISSUE TITLE
emoji picker: move up into some global state

### ISSUE THREAD

**Issue by patosullivan** [tloncorp/landscape-apps#2015]
Right now the picker will go away any time the message or options themselves remount (or lose focus). It's annoying. Would be better if we tracked this globally so it could stay open regardless.

**Comment by urcades** [comment]
Adding a comment from an internal discussion, so it's on the record:

<img width="630" alt="Screenshot 2023-04-04 at 12 19 37 PM" src="https://user-images.githubusercontent.com/1195363/229854979-c57181bd-a229-4671-8b0d-2a0f5d020900.png">

**Comment by jamesacklin** [comment]
@patosullivan Fixed?

**Comment by patosullivan** [comment]
Yes.
