### ISSUE TITLE
latest.json responses for talk sometimes really big

### ISSUE THREAD

**Issue by Fang-** [tloncorp/landscape-apps#2022]
Occasionally I get into a state (not clear to me yet how) where my ship spends large amounts of time spinning on `<<http>>`. I suspect the Talk frontend is the one making requests that cause that, because:
1) Closing the tab with Talk in it usually alleviates the issue.
2) Looking in the networking tab for Talk when the problem occurs, requests for `latest.json` receive a response that's a couple of _megabytes_ in size. Latest I saw was 3.8mb.

If the backend is trying to serialize that much chat data, no wonder it's taking some time. Whatever "latest" we're scrying could probably get a more tightly-scoped response from the backend.

**Comment by arthyn** [comment]
Paired with latest changes to the way that we fetch updates this is really painful, especially if you're getting tons of notifications from a dm/group-dm. Also since we're not actually surfacing notifications in talk we should probably just not start hark in talk frontend.

**Comment by tomholford** [comment]
Could this be the culprit for #1870?
