### ISSUE TITLE
chat: embed weirdness

### ISSUE THREAD

**Issue by arthyn** [tloncorp/landscape-apps#2029]
seems like embeds are maybe breaking out of their box somehow? also we probably need something underneath the click to play text to make it visible on certain images like this one

<img width="775" alt="image" src="https://user-images.githubusercontent.com/5466421/222014892-3899b857-4050-4a08-ac8d-4b8657ca2dbe.png">

**Comment by jamesacklin** [comment]
DUPLICATE

OF

#2019
