### ISSUE TITLE
"Edit Note" for notebook post produces blank screen 

### ISSUE THREAD

**Issue by emceetee** [tloncorp/landscape-apps#2038]
Attempts to edit a new notebook entry (Landscape Pilot Program) in the group, ETHDenver, result in a blank screen. I tried four times with the same result. Refresh has no effect, can only exit the page/go back. 

The issue doesn't appear to be affected by browser (used Arc + Chrome).

![Screenshot 2023-03-01 at 9 36 06 AM](https://user-images.githubusercontent.com/100450974/222218451-d3317596-0554-45fe-bbf8-dbd56e94c36a.png)

**Comment by emceetee** [comment]
Ok actually - when you click into the post it's possible to edit. But when you attempt to edit using the kebab menu that produces the blank screen.

**Comment by jamesacklin** [comment]
Good catch, thank you!
