### ISSUE TITLE
chat: change data structure to allow better querying

### ISSUE THREAD

**Issue by arthyn** [tloncorp/landscape-apps#2042]
We currently use a `mop` to store chats, notes, and curios. If you look at the way we've implemented the `older`/`newer`/`newest` scries in `dm.hoon`, `notes.hoon`, `curios.hoon` it's clear that we're not using these efficiently because we're missing some more ergonomically useful functions.

For chats this is especially bad because we have huge logs. This means when we reverse the log it takes forever. Also to do the "click to view last unread message" correctly we need to be able to arbitrarily jump back to a point in time and provide the surrounding context we can get one direction of messages using `tab` but not the preceding direction.

For this to work we need a few extra functions on mops:
- top/bottom X items
- a function similar to tab except going in the opposite direction

Once we have these we should replace the implementations of the scries mentioned above using these and should see better performance for all of them.

**Comment by jamesacklin** [comment]
All for it. Sounds like 3.0.0?

**Comment by arthyn** [comment]
I think this would still be just a minor version because we're not changing the actual interfaces of those calls just making them perform better and then adding one new scry. 3.0 feels more significant than that to me haha

**Comment by jamesacklin** [comment]
How else are we going to get to Perfect Groups 49?
