### ISSUE TITLE
groups: can't insert hyperlink on gallery comments

### ISSUE THREAD

**Issue by emceetee** [tloncorp/landscape-apps#2045]
Made it to 'Enter URL' but the typebox glitches from gray to white and is unable to link successfully. Formatting is also off and text overflows the text box.

<img width="468" alt="Screenshot 2023-03-01 at 10 11 31 PM" src="https://user-images.githubusercontent.com/100450974/222346727-a7323a5e-bda6-43cc-b151-cb15c7bba825.png">

**Comment by jamesacklin** [comment]
Partially fixed, behavior still wacky
