### ISSUE TITLE
Onboarding thread (groups + talk)

### ISSUE THREAD

**Issue by emceetee** [tloncorp/landscape-apps#2063]
Ran an onboarding with @zalberico earlier today. Hosting issues are logged in [tloncorp/ylem/issues/896.](https://github.com/tloncorp/ylem/issues/896). We ran into the following bugs in group creation and Talk:

**Group Creation**
- [ ] - Editing a notebook section title took a second time to save, unsuccessful first try
- [ ] - Creating galleries with images was disorienting - when he clicked into the tile the image appeared but not in gallery tile preview
- [ ] - He tried twice unsuccessfully to post a video in the gallery channel. The 'post' button appeared to have no effect, but ~3minutes later the video posted 14 times (see attached image)
- [ ] - Very slow load for add note - unsuccessful first time (404 message), long wait time that led him to abandon. He tried a third time and was able to create a note
- [x] -  General feedback: back to groups button is confusing and buried

**Talk**
- [x] - Double render of first message (visible to him, but not me as the receiver)
- [x] - He struggled with finding my profile. Attempted to click the large sigil. Eventually found through clicking smaller chat avatar. Not intuitive.

![Screenshot 2023-03-01 at 12 20 38 PM](https://user-images.githubusercontent.com/100450974/222293961-0a910e50-a66c-41c7-91b2-bf66e10bb4af.png)

**Comment by urcades** [comment]
The first four issues listed here share some behavior with the observations made in #2241 — will be good to tackle the moments described here during any betterment of loading/processing/updating states
