### ISSUE TITLE
Groups: Frequent disconnects, broken visual assets on e1abg

### ISSUE THREAD

**Issue by litmus-ritten** [tloncorp/landscape-apps#2071]
Since `e1abg`, I've seen the "You are currently offline" banner pop up every few minutes, and many messages I have posted have vanished even during periods when the offline banner was not present. When the "You are currently offline" banner appears posting is impossible. Group avatars, hero images, and user avatars are also inconsistently broken (showing a broken image link placeholder) across `groups`.

**This issue is reported by at least two other users in UC/help.**

Member listing (note that sigil avatars render correctly):
![Screenshot from 2023-03-04 12-05-55](https://user-images.githubusercontent.com/62781197/222864350-cd96e244-7cb6-4b4a-a8fe-e6643973dbf7.png)

Group hero image:
![Screenshot from 2023-03-04 12-05-20](https://user-images.githubusercontent.com/62781197/222864391-807a59c6-6ae3-4562-b259-290593397b76.png)

Group avatars:
![Screenshot from 2023-03-04 12-04-53](https://user-images.githubusercontent.com/62781197/222864405-bf2820a5-f3d0-4dca-8bc8-c4d4b31e6baf.png)

Getting suspicious terminal spam:

```
hear: bail: %exit

[%poke %hear]
bar-stack=[i=[i=//ames t=~] t=~]
call: failed
/sys/vane/ames/hoon:<[1.193 3].[1.227 20]>
/sys/vane/ames/hoon:<[1.195 3].[1.227 20]>
/sys/vane/ames/hoon:<[1.196 3].[1.227 20]>
/sys/vane/ames/hoon:<[1.198 3].[1.227 20]>
/sys/vane/ames/hoon:<[1.199 5].[1.225 7]>
/sys/vane/ames/hoon:<[1.202 5].[1.225 7]>
/sys/vane/ames/hoon:<[1.208 5].[1.225 7]>
/sys/vane/ames/hoon:<[1.210 14].[1.210 53]>
/sys/vane/ames/hoon:<[1.710 5].[1.710 43]>
/sys/vane/ames/hoon:<[1.716 5].[1.736 17]>
/sys/vane/ames/hoon:<[1.717 5].[1.736 17]>
/sys/vane/ames/hoon:<[1.719 5].[1.736 17]>
/sys/vane/ames/hoon:<[1.721 5].[1.736 17]>
/sys/vane/ames/hoon:<[1.725 5].[1.736 17]>
/sys/vane/ames/hoon:<[1.819 5].[1.871 62]>
/sys/vane/ames/hoon:<[1.820 5].[1.871 62]>
/sys/vane/ames/hoon:<[1.826 5].[1.871 62]>
/sys/vane/ames/hoon:<[1.830 5].[1.871 62]>
/sys/vane/ames/hoon:<[1.835 5].[1.871 62]>
/sys/vane/ames/hoon:<[1.836 5].[1.871 62]>
[%ames-crash-on-packet-from ~marzod]
/sys/vane/ames/hoon:<[1.837 5].[1.871 62]>
/sys/vane/ames/hoon:<[1.841 5].[1.871 62]>
/sys/vane/ames/hoon:<[1.870 5].[1.871 62]>
/sys/vane/ames/hoon:<[1.871 5].[1.871 62]>
/sys/vane/ames/hoon:<[1.871 10].[1.871 62]>
/sys/vane/ames/hoon:<[2.670 7].[2.699 69]>
/sys/vane/ames/hoon:<[2.673 7].[2.699 69]>
/sys/vane/ames/hoon:<[2.675 7].[2.699 69]>
/sys/vane/ames/hoon:<[2.677 7].[2.699 69]>
/sys/vane/ames/hoon:<[2.678 9].[2.683 65]>
/sys/vane/ames/hoon:<[2.683 9].[2.683 65]>
/sys/vane/ames/hoon:<[3.008 7].[3.203 9]>
/sys/vane/ames/hoon:<[3.009 7].[3.203 9]>
/sys/vane/ames/hoon:<[3.012 7].[3.203 9]>
/sys/vane/ames/hoon:<[3.015 7].[3.203 9]>
/sys/vane/ames/hoon:<[3.016 7].[3.203 9]>
/sys/vane/ames/hoon:<[3.017 7].[3.203 9]>
/sys/vane/ames/hoon:<[3.018 7].[3.203 9]>
/sys/vane/ames/hoon:<[3.021 7].[3.203 9]>
/sys/vane/ames/hoon:<[3.021 11].[3.030 37]>
/sys/vane/ames/hoon:<[3.022 11].[3.030 37]>
/sys/vane/ames/hoon:<[3.023 11].[3.030 37]>
/sys/vane/ames/hoon:<[3.024 11].[3.030 37]>
/sys/vane/ames/hoon:<[3.025 13].[3.029 15]>
/sys/vane/ames/hoon:<[3.026 22].[3.026 63]>
/sys/vane/ames/hoon:<[3.093 9].[3.115 21]>
/sys/vane/ames/hoon:<[3.094 9].[3.115 21]>
/sys/vane/ames/hoon:<[3.100 9].[3.115 21]>
/sys/vane/ames/hoon:<[3.100 24].[3.100 66]>
/sys/vane/ames/hoon:<[3.100 30].[3.100 45]>
/sys/vane/ames/hoon:<[2.878 7].[2.880 50]>
/sys/vane/ames/hoon:<[2.879 7].[2.880 50]>
[%dangling-bone ~marzod 1.672]
/sys/vane/ames/hoon:<[2.880 7].[2.880 50]>
crud: bail: %exit
ames: packet failed (100 total)
ames: packet dropped (6000 total)
ames: packet dropped (7000 total)
%group-store: on-peek on path /x/wait
%group-store: on-watch on path /wait
eyre: canceling [i=//http-server/0v17.5djtl/111/8 t=~]
ames: packet dropped (8000 total)
ames: packet dropped (9000 total)
ames: packet dropped (10000 total)
ames: packet dropped (11000 total)
ames: packet dropped (12000 total)
ames: packet dropped (12000 total)
ames: packet dropped (13000 total)
ames: packet dropped (14000 total)
ames: packet dropped (15000 total)
ames: packet dropped (16000 total)
ames: packet dropped (16000 total)
ames: packet dropped (17000 total)
ames: packet dropped (18000 total)
ames: packet dropped (19000 total)
```

~marzod is my present sponsor and OTA source.

**To Reproduce**
1. Upgrade `groups` to e1abg.
2. Note that things are screwy.

**Expected behaviour**
Graphics render correctly and users are not disconnected constantly.

**Additional context:**
- Ship type: Planet
- Instance type: CLI self-hosted
- OS/browser: Vivaldi on Linux

**Comment by bonbud-macryg** [comment]
I'm also seeing the frequent disconnects bug on macOS Safari, connected to a self-hosted ship running on an old MacBook Pro via Tailscale.

**Comment by litmus-ritten** [comment]
To expand on this, my pier is currently on localhost. In the terminal, whenever I interrupt with ctrl-c I get a bit of a seeming backlog of various stack traces, e.g.:

```
~litmus-ritten:dojo> 
recover: dig: intr

interrupt
crud: %ames-wake event failed
[%poke %wake]
wire=/pump/~raphut-fantun/1.693
bar-stack=[i=[i=/ames t=~] t=[i=[i=//behn t=~] t=~]]
take: failed
/sys/vane/ames/hoon:<[1.232 3].[1.252 20]>
/sys/vane/ames/hoon:<[1.233 3].[1.252 20]>
```
[...]

**Comment by ImmanuelKant** [comment]
I'm experiencing the same issue running on a VPS. CPU usage of the urbit process is running abnormally high (>=96%)

**Comment by ImmanuelKant** [comment]
![image](https://user-images.githubusercontent.com/28705048/222959163-ab2fbf23-179f-49c2-ac46-093e2c07e1fc.png)


See CPU usage for the past 24 hours (GMT). Shortly before 15:00 on Saturday, cpu usage increased dramatically and then dropped off to normal level after about 3 hours. This morning cpu usage was high again. I then updated to v1.22 and am still seeing high cpu levels

**Comment by patosullivan** [comment]
I'm seeing the same thing since Tuesday. I suspect it has to do with the recent base OTA. I have the ames spam as well.

**Comment by litmus-ritten** [comment]
This looks fixed in 8j82a. Thanks all.
