### ISSUE TITLE
talk: visual glitches on hover/text highlighting

### ISSUE THREAD

**Issue by bonbud-macryg** [tloncorp/landscape-apps#2072]
When I hover over pinned messages and chat posts in pre-release Talk (desk hash ending `ardq2`), the channel appears as if rapidly moving in and out of the selected status. I get very similar behaviour hovering over messages in a thread, and similar behaviour prevents me from highlighting text. Groups seems fine.

Video: https://0x0.st/Hzv1.mov

**To Reproduce**
1. Follow what I do in the video on Safari.

**Expected behavior**
The same behaviour as Talk had in previous releases.

**Additional context:**
- Planet
- Self-hosted on an old MacBook Pro, accessed via Tailscale
- macOS Ventura 13.1, Safari 16.2

**Comment by patosullivan** [comment]
Can't repro in either Safari or Chromium-based browsers.

**Comment by patosullivan** [comment]
Tried again this morning to repro this, thought it might be caused by the disconnected state. Still couldn't repro on safari or chromium.

**Comment by bonbud-macryg** [comment]
Talk `0v1r.ma8fg.ad3fm.oimr3.6oglt.irepe.dr3ri.lsn79.9nnq6.v6u9k.bhhm2` seems to have fixed this.

https://0x0.st/Hz7S.mov

**Comment by patosullivan** [comment]
May have been related to the container queries issue.
