### ISSUE TITLE
landscape: remote content still loads after turning it off

### ISSUE THREAD

**Issue by bonbud-macryg** [tloncorp/landscape-apps#2082]
**Describe the bug, optionally with screenshots**
I switched on "Disable remote content" to help with performance issues. After having done so, I'm still actually seeing remote content like overlay avatars and group icons until Talk finally finishes loading, at which point they all disappear and Talk looks as it should without remote content. Similar behaviour in Groups, as seen with group cover images.

I assume that remote content is cached somewhere in my browser and that's where Talk is loading it from. It's sort of jarring the first time it happens, and other times it's just an inconsistent experience. If I turned off remote content for good (idk, I could get used to this!) I don't know how long I'd still be seeing the icons and avatars.

**To Reproduce**
1. Turn on "Disable remote content", having seen overlay avatars and group icons before
2. Open Talk/Groups
3. See remote content
4. See remote content disappear when Talk/Groups finishes loading

**Expected behavior**
As soon as I turn on "Disable remote content", I should never see remote content.

**Additional context:**
- L2 Planet
- Self-hosted on a MacBook, accessed via Tailscale
- macOS Ventura 13.1, Safari 16.2

**Comment by jamesacklin** [comment]
It takes a second to scry into %settings-store and update the UI - the delay is in waiting for the scry to resolve. We could do a better job of this:

A) assume you don't want remote content, read the setting, and progressively enhance
B) read the setting from %settings-store in Landscape and store it locally, defer to the local setting on load, and then update the flag necessary

**Comment by patosullivan** [comment]
this was fixed in https://github.com/tloncorp/landscape-apps/pull/2345
