### ISSUE TITLE
Delete always available, even when you cannot delete

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/landscape-apps#2095]
**Describe the bug, optionally with screenshots**
You cannot delete a message in a DM you did not start, but the option is available. 

**To Reproduce**
1. Send message in a DM started by someone else
2. Click on delete button for DM
3. Nothing happens, delete remains available

**Expected behavior**
We should not be given the option to do something we cannot do. Can we actually delete a message from a DM not owned by us? If not, do not give users the option.

**Comment by jamesacklin** [comment]
There isn't any "ownership" of DMs, it's just a log on your ship, like SMS.

Are you clicking delete on your own DM or someone else's?

**Comment by jamesacklin** [comment]
Manifests as #2375
