### ISSUE TITLE
chat: indicate which emoji reactions were sent by me

### ISSUE THREAD

**Issue by alecananian** [tloncorp/landscape-apps#2098]
UX suggestion: there's currently no indication which emoji reaction was left by me and which was left by someone else, until I hover over and see my name and the X icon. Having a separate color background for reactions I have added to, and removing the (+) icon to the right if I've already reacted should provide a clearer experience here.

Example: in the screenshot below, the top reaction is one someone did on my post while the bottom is one I did - they look the same at a glance.

<img width="134" alt="Screenshot 2023-03-08 at 10 46 46 AM" src="https://user-images.githubusercontent.com/1013230/223807052-aca554a7-b1f3-4556-8ca5-86d06ef59aa6.png">

**Comment by jamesacklin** [comment]
Definitely, thanks!
