### ISSUE TITLE
chat: emoji picker impossible to hit with mouse

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#2108]
The emoji picker for reactions is nigh impossible to use in Groups and frequently does not appear reliably in Talk (I think this is something to do with how we're handling the mouse-out/close event).

No reproduction other than "play with it and see."

**Comment by marisarow** [comment]
https://user-images.githubusercontent.com/10634823/224443778-0d8f4b38-6461-45be-8484-ce9a81e9cde3.mov
