### ISSUE TITLE
chat: New DM invites don't show up anywhere

### ISSUE THREAD

**Issue by philipcmonk** [tloncorp/landscape-apps#2117]
I received a DM from someone I hadn't DM'd with before, and I noticed it in the grid notifications section, but it didn't show up anywhere in talk.  After seeing it once in the grid notifications it also disappeared from there, so I couldn't click on it.  I remembered the name, so I created my own DM to them, and after sending the first message it showed the page asking me if I wanted to accept their DM invite.  @galenwp reported the same issue.

Ubuntu/Chrome/syncing %talk, %groups, and %base from ~binnec

**Comment by philipcmonk** [comment]
This happened again today.  It's making me paranoid that I'm missing all new DMs, not sure how long this has been the case.

**Comment by patosullivan** [comment]
Were you able to see the DM they originally sent after you sent yours and got past the "Accept" page?

**Comment by philipcmonk** [comment]
Yes
