### ISSUE TITLE
Refresh on mobile loses context at groups root

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/landscape-apps#2140]
**Describe the bug, optionally with screenshots**
When using Groups on mobile web and viewing the groups list, if the view refreshes for any reason, the notifications screen is loaded

**To Reproduce**
https://user-images.githubusercontent.com/1903610/225678907-44476f84-460b-417d-83ed-f024e185adc8.mp4

**Expected behavior**
I'd expect to stay on the screen I was viewing after a refresh. 

**Additional context:**
- self-hosted DO planet, Chrome on iOS

**Comment by patosullivan** [comment]
I can't repro this by just hitting the refresh button (i.e., the correct page is showing on refresh). Did you do anything else with the URL bar? Is this issue still occurring?

**Comment by jamesacklin** [comment]
I've noticed that the `/apps/groups/` path resolves flawlessly; refreshing strips the trailing `/`, which fails.
