### ISSUE TITLE
Groups frontend fails to load or display groups data

### ISSUE THREAD

**Issue by Fang-** [tloncorp/landscape-apps#2149]
Attempting to load the groups web UI results in a screen that sits like this forever:

![image](https://user-images.githubusercontent.com/3829764/225876369-317980d2-45ee-4f3e-86ea-4bef67268a89.png)

The browser still think it's loading the page. Inspecting the networking tab, we see it indeed still has a bunch of requests open:

![image](https://user-images.githubusercontent.com/3829764/225876539-2b2351da-0093-4300-bcfb-f589c79181d1.png)

The first bunch of these resolve swiftly on refresh, but then eventually a bunch of them get stuck. The ship is not spinning `<<http>>`, and handles new/other events just fine.

Web console displays only a couple of warnings about cookies and whitelist options, but iirc those have been there for some time already. There are no errors or logs.

```
> +vat %base
%base
  /sys/kelvin:      [%zuse 415]
  base hash:        0va.mn6n0.2ni3n.vpr1r.9b98s.q2jve.4osvm.g4hvn.magll.uqoll.3jbrb
  %cz hash:         0va.mn6n0.2ni3n.vpr1r.9b98s.q2jve.4osvm.g4hvn.magll.uqoll.3jbrb
  app status:       running
  force on:         ~[[%shoe %.y]]
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~binnec-dozzod-marzod
  source desk:      %kids
  source aeon:      60
  kids desk:        %kids
  pending updates:  ~[[%zuse 414]]
::
> +vat %groups
%groups
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415]
  base hash:        0v6.ft3j1.dvmj1.26tfq.bkugs.ei2va.lkeg3.ku6sr.2jlmn.olepc.8j82a
  %cz hash:         0v6.ft3j1.dvmj1.26tfq.bkugs.ei2va.lkeg3.ku6sr.2jlmn.olepc.8j82a
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~sogryp-dister-dozzod-dozzod]
  updates:          remote
  source ship:      ~marnec-dozzod-marzod
  source desk:      %groups
  source aeon:      53
  kids desk:        ~
  pending updates:  ~
::
```

I first noticed this sometime last night, after #2121 forced me to refresh. Unclear to me at this time what could've caused this. I'm open to this being a local setup-dependent bug, but there too nothing has changed recently.

Talk loads fine for me.

**Comment by Fang-** [comment]
Installing from the binnec prerelease moon partially resolves the problem. The frontend loads/renders the data now, and seems to operate fine.

However, some requests still never finish loading. This accumulates, eventually hitting the max pending requests limit of the browser, and because of that eventually fails to establish a new eyre channel, triggering the "you are offline" banner.

![image](https://user-images.githubusercontent.com/3829764/225899144-1475a643-6dcc-4905-94a4-c29087c04338.png)

**Comment by jamesacklin** [comment]
@arthyn Are our new scry methods safe for non-https?

**Comment by jamesacklin** [comment]
@Fang- Resolved, yes?

**Comment by Fang-** [comment]
Oh, yes, this just... magically resolved itself before we could find a root cause. Spooky.
