### ISSUE TITLE
groups: clicking "Reject" on a (secret) group invite blanks out the screen

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#2156]
**Describe the bug, optionally with screenshots**
If I attempt to reject a group invite (in this case, a secret group invite), my screen blanks out. Refreshing the browser causes me to end up at an endpoint that doesn't appear to render anything to the screen. I need to manually backtrack in order to reset the state of Groups.

The invite is unable to be rejected, and remains in the invite list.

Repro recorded here:

https://user-images.githubusercontent.com/1195363/226175550-05cf929b-3ed3-4929-a547-3062083a902d.mov

**To Reproduce**
1. Get someone to invite you to a group — you should see a resulting invite in your "Find Groups" interface
2. Click "Reject"
3. If your screen blanks out, you've successfully reproduced the bug

**Expected behavior**
I expect clicking "Reject" to simply disappear the invite from the Find Groups interface, with no reloading of the interface or navigating to anywhere else occurring.

**Additional context:**
- Ship: planet — `~fabled-faster`
- Instance type: GCP
- MacOS Ventura — 13.2.1 (22D68)
- Safari — Version 16.1 (18614.2.9.1.12)
- Chromium Engine Version 111.0.5563.64

**Comment by alecananian** [comment]
Also logged in #2041

**Comment by jamesacklin** [comment]
Duplicate
