### ISSUE TITLE
leap: recursive app-launching possible

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#2173]
**Describe the bug, optionally with screenshots**
Our new app launcher in Leap makes it possible to recursively open Groups and Talk within one another.

**To Reproduce**
1. Go to Groups and open Leap.
2. Select "Apps," then open Talk.
3. In the windowed version of Talk, open Leap.
4. Select "Apps," then open Groups.
5. Repeat.

**Expected behavior**
The portaled application should know it's open in an embedded context and prohibit me from opening other apps from within it.

https://user-images.githubusercontent.com/748181/226690771-d4df39ed-4bed-4e44-b32a-9429cfdfbaf1.mov

**Comment by jamesacklin** [comment]
Don't need to attack this right away (can wait until after v2.9.0) since it's fairly harmless and, frankly, amusing.

**Comment by urcades** [comment]
@dnbrwstr this might be an interesting thing to consider re: some of the systems chrome/nav work in store for us soon
