### ISSUE TITLE
talk: loads to blank screen

### ISSUE THREAD

**Issue by eamsden** [tloncorp/landscape-apps#2193]
Navigating to the talk app produces a blank screen and a 'loading...' title indefinitely with no dojo activity

![image](https://user-images.githubusercontent.com/54573/227726225-7d1e9acf-f12d-45dc-b641-f0f1046a6ea2.png)

**To Reproduce**
Navigate to talk app

**Expected behavior**
The talk app interface loads

**Additional context:**
- Ship type: planet
- Instance type: self-hosted x86_64 linux
- OS/browser: Brave on x86_64 Linux, Brave on Android mobile

**Comment by eamsden** [comment]
![image](https://user-images.githubusercontent.com/54573/227727065-13aa742a-4700-4392-97bd-81e0b13673fc.png)

**Comment by alecananian** [comment]
I'm seeing the same on Firefox for Android

**Comment by patosullivan** [comment]
Where are you syncing groups from?

**Comment by alecananian** [comment]
I'm on ~wannec-dozzod-marzod for Talk and Groups

**Comment by eamsden** [comment]
~marnec-dozzod-marzod here (as seen in the +vats screenshot above)

**Comment by patosullivan** [comment]
> ~marnec-dozzod-marzod here (as seen in the +vats screenshot above)

Right, but is groups coming from the same ship?

**Comment by patosullivan** [comment]
What happens if you add a trailing slash?

I think I know what this is.

**Comment by eamsden** [comment]
Trailing slash makes it load.

**Comment by jamesacklin** [comment]
Trailing slash works.

**Comment by eamsden** [comment]
@patosullivan is there already an issue open for this?

**Comment by patosullivan** [comment]
> @patosullivan is there already an issue open for this?

No, but I'll fix it
