### ISSUE TITLE
talk/groups: expanded images in chat sometimes don't embiggen

### ISSUE THREAD

**Issue by tinnus-napbus** [tloncorp/landscape-apps#2195]
**Describe the bug, optionally with screenshots**

sometimes when I click on an image in chat it's still the same tiny size when expanded. If I open source it's much much bigger so it's not actually that small:

![2023-03-26_19h39m03s](https://user-images.githubusercontent.com/77721746/227759757-4536d86a-ea6e-412d-b511-d5d0664b4eab.png)

this seems to be consistent with the particular images that don't embiggen, but other images embiggen correctly. Maybe the type of image?

**To Reproduce**
1. click to expand image
2. sometimes not any bigger

**Expected behavior**
should be enbiggened

**Additional context:**
- Ship type: planet
- Instance type self-hostedch
- OS/browser qutebrowser / chromium

```
> +vat %groups
%groups
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415] [%zuse 414]
  base hash:        0v4.nsfam.srqbc.p002p.q0ham.f0fqd.gg4gi.bqtu9.p6245.b49ch.hk0d2
  %cz hash:         0v4.nsfam.srqbc.p002p.q0ham.f0fqd.gg4gi.bqtu9.p6245.b49ch.hk0d2
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~sogryp-dister-dozzod-dozzod]
  updates:          remote
  source ship:      ~binnec-dozzod-marzod
  source desk:      %groups
  source aeon:      114
  kids desk:        ~
  pending updates:  ~[[%zuse 414]]
::
> +vat %talk
%talk
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415] [%zuse 414]
  base hash:        0ve.3r4jj.n5ish.n63h8.1qu3o.vkodt.dvhm9.4aisd.opm40.pub9c.5a1p3
  %cz hash:         0ve.3r4jj.n5ish.n63h8.1qu3o.vkodt.dvhm9.4aisd.opm40.pub9c.5a1p3
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~sogryp-dister-dozzod-dozzod]
  updates:          remote
  source ship:      ~binnec-dozzod-marzod
  source desk:      %talk
  source aeon:      107
  kids desk:        ~
  pending updates:  ~[[%zuse 414]]
::
```

**Comment by arthyn** [comment]
Images posted from Escape are having their dimensions set incorrectly so they show up small everywhere. This was fixed in Groups/Talk, but won't go away until people posting switch from Escape.
