### ISSUE TITLE
channels: joined channel missing from sidebar

### ISSUE THREAD

**Issue by tomholford** [tloncorp/landscape-apps#2232]
Some conversation in Star Squawk observed that the Rules notebook is visible and joinable in All Channels, but does not render in the sidebar and / or redirects to a different notebook

![image](https://user-images.githubusercontent.com/16504501/229215654-cfd75da6-12c4-4fc2-80e7-b5ae4f77e1d3.png)

![image](https://user-images.githubusercontent.com/16504501/229215210-25028aa3-72b8-4fc5-a208-ab6774203675.png)

**Comment by tomholford** [comment]
Looks like it's a permissions issue. Will defer to @jamesacklin on whether this should be closed or iceboxed

<img width="541" alt="image" src="https://user-images.githubusercontent.com/16504501/229258905-dc8b1c2c-9c65-4d6c-b922-e9b508d61f3d.png">

**Comment by jamesacklin** [comment]
This was a migrated group but might be good to dig in on.
