### ISSUE TITLE
i.seal.quips.get is not a function. (In 'i.seal.quips.get(pn(n))', 'i.seal.quips.get' is undefined)

### ISSUE THREAD

**Issue by vvisigoth** [tloncorp/landscape-apps#2239]
**Describe the bug, optionally with screenshots**
A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.

**To Reproduce**

**Expected behavior**

**Additional context:**
- Ship type (comet/moon/planet/star/galaxy)
- Instance type (Tlon-hosted/self-hosted with Port/CLI)
- OS/browser (Safari on MacOS, Chrome on Windows, Firefox on Linux, etc.)

**Comment by jamesacklin** [comment]
@vvisigoth Did you see this in a notebook? Do you remember which one / what you were doing?

**Comment by vvisigoth** [comment]
Yeah sorry to be cryptic. I saw this on the Galaxy Attestation notebook on
MObile Web (safari).
A
