### ISSUE TITLE
groups: invite people and lure link hidden behind menu on mobile

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#2254]
In mobile, the invite person (for patp and lure links) is hidden behind the bottom right three button menu.

This isn't a great spot for it, we probably want it somewhere on the root level.

I also noticed the lure link copy doesn't seem to work - when you open the modal the lure link text is already highlighted.

**Comment by zalberico** [comment]
@jamesacklin only assigning to you for triage/handling

**Comment by urcades** [comment]
As part + parcel of a more general refactor of our mobile app layout, I'm recommending that we more or less adhere to the existing sidebar structure as a full-screen mobile experience:

<img width="484" alt="Screenshot 2023-04-27 at 10 28 16 PM" src="https://user-images.githubusercontent.com/1195363/235039819-18a59cbb-86ad-419e-b8b4-3e325f595e2d.png">

This would end up situating "Inviting people" visible once any group is tapped on. The same action is duplicated in the group's "Action menu" (the dropdown for a group on desktop, turned into a "drawer" on mobile) available as the last item in the bottom row nav:

<img width="492" alt="Screenshot 2023-04-27 at 10 31 59 PM" src="https://user-images.githubusercontent.com/1195363/235040304-bc224301-2e65-4aea-8435-4addba0f539f.png">

The exact typographic + visual design is still pending, and will be expanded upon in another issue, but the coarse placement of these items will remain the same.
