### ISSUE TITLE
chat: refs aren't properly cleared

### ISSUE THREAD

**Issue by arthyn** [tloncorp/landscape-apps#2283]
Whether it's an image or reference of some type, the chat input seems to hold on to it even after send. After sending when visiting other chats you'll see the same attachment sitting there.

**Comment by patosullivan** [comment]
Also not able to repro this one. Tried with both groups and talk, with both image attachments and refs, on both desktop and mobile.

**Comment by patosullivan** [comment]
Saw this today but now I can't reproduce it

**Comment by urcades** [comment]
Have seen this too, intermittently.

**Comment by jamesacklin** [comment]
Will try in earnest to reproduce this.
