### ISSUE TITLE
Stuck on Installing for %talk and %groups

### ISSUE THREAD

**Issue by mopfel-winrux** [tloncorp/landscape-apps#2294]
**Describe the bug, optionally with screenshots**
I am updating from ~binnec-dozzod-marzod and both my %talk and %groups are stuck on installing. In addition %pongo is also stuck. Additionally, the %talk and %groups web endpoint aren't loading. My logs do not have anything in them. 

![image](https://user-images.githubusercontent.com/223191/231582512-53c82f05-ca7c-4530-bcb0-ee3a423d4b45.png)

**To Reproduce**
1. Go to landscape home
2. See above

**Expected behavior**
Being able to access my apps

**Additional context:**
- planet
- GroundSeg
- Windows Chrome

**Comment by arthyn** [comment]
have you tried running install from the terminal?

**Comment by mopfel-winrux** [comment]
I think I got pongo'd but it showed up in a weird way. I uninstalled it and %talk and %groups are working. I'm currently syncing back to ~binnec to make sure it was that. I'll close when the sync is complete

**Comment by mopfel-winrux** [comment]
Got pongo'd. talk and groups is working. closing

**Comment by arthyn** [comment]
good to hear
