### ISSUE TITLE
gallery: cannot open curio detail

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#2302]
**Describe the bug, optionally with screenshots**
Opening a gallery item results in an endless loop of scries for 50 of the latest gallery items and never shows the curio.

**To Reproduce**
1. Go to a collection.
2. Open an item.
3. Observe spinner.

Happening on latest from `master`, `0v1l.fq5gm.8idn9.1seig.82qq6.2qunj.p3c71.gdm5c.fcf2t.ihsg9.p90d7`

https://user-images.githubusercontent.com/748181/231910186-6ff4feb5-a414-4509-a9f1-8837c20ad2d1.mov

**Comment by patosullivan** [comment]
Fixed by #2309
