### ISSUE TITLE
gallery: references to gallery item in chat don't preview correctly

### ISSUE THREAD

**Issue by vvisigoth** [tloncorp/landscape-apps#2305]
![Screen Shot 2023-04-14 at 10 12 12 AM](https://user-images.githubusercontent.com/1609955/232087283-cecfc4ea-26fc-4c6a-a367-b0135a54cb5a.png)

The referenced item is not an empty screen.

**Comment by vvisigoth** [comment]
Chrome, latest

**Comment by patosullivan** [comment]
Fixed by #2286

**Comment by patosullivan** [comment]
(will be out with 3.0 release)
