### ISSUE TITLE
groups: joining a group has no loaders

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#2306]
**Describe the bug, optionally with screenshots**
A feeling of helplessness and confusion accompanies joining a new group, even if the group "join" succeeds. Most of this boils down to the following conditions:
(A) you've joined the group
(B) you've navigated to the new group
(C) you're waiting for more content to fill itself in

![image](https://user-images.githubusercontent.com/748181/232113228-922b5de1-c6ea-4075-9b6d-cf8eadb4fc1d.png)

Sometimes, the group name populates here. Sometimes, it doesn't. We should fix this.

**To Reproduce**
1. Join a new group
2. Allow yourself to be navigated to the group
3. Observe empty/questionable group state while content gets downloaded from the host

**Expected behavior**
I would expect some kind of loading indicator. A centered spinner in the main stage at the very least would be appropriate here. Lots of apps generate some silly technobabble "Reticulating splines..." to keep you around while waiting -- we could do something more straightforward "Downloading group data from host..." _or_ we could fake out the actual dojo response one would expect to see when transferring this data across the network. Up to us, really -- anything but a blank screen.

**Comment by urcades** [comment]
Lucky for you, we actually have this in the Handoffs file as an experience that should def be part of the canonical experience. I've communicated the states in a more concise manner here:

<img width="3260" alt="Channel Loading" src="https://user-images.githubusercontent.com/1195363/232119376-fd462154-60b6-4200-95a3-ea9680c6e357.png">

More context here: 
https://www.figma.com/file/QMM0PcJyuKWrXY2n4VpQp1/2023-Q2-Groups?node-id=130%3A27847&t=c4fjDn9gD0VhyrBK-1

**Comment by urcades** [comment]
Alternative approach to group loading that I support:

<img width="1440" alt="Initial Load" src="https://user-images.githubusercontent.com/1195363/232123256-ada513e3-bc02-4d76-b2ba-0634cf74104c.png">
