### ISSUE TITLE
Text in a gallery doesn't seem to load (in list view)

### ISSUE THREAD

**Issue by galenwp** [tloncorp/landscape-apps#2317]
**Describe the bug, optionally with screenshots**
If a Gallery item is text it appears to load forever. 

**To Reproduce**
1. Go to any gallery
2. Post an item as 'Text'
3. Click on that item

**Expected behavior**
Just seeing the text (and a comment thread)

**Additional context:**
- OS/browser Safari on MacOS

**Comment by patosullivan** [comment]
Fixed by #2309
