### ISSUE TITLE
groups: tracker for stuck group joining

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#2322]
I'm reporting this issue on behalf of three people so far who are running into group joining issues.

What we know so far: 

1. Sometime over the weekend, romina's ship went offline, preventing people from joining a group she hosts (door) for the first time
3. Romina's being offline was notified to Tlon, who booted up her ship again
4. A few people who noticed the ship being offline are now having trouble accessing the group period, seeing indeterminate loading states while accessing the group, or following references to its contents
5. Apparently after attempting to leave the group, these folks can no longer join the group

As far as I'm aware, three people are affected by this issue, signaling it might be more general than just one person's connectivity being the issue.

Some telltale states:

Seen after pressing "Join" on a group reference:

<img width="720" alt="Screenshot 2023-04-17 at 4 07 23 PM" src="https://user-images.githubusercontent.com/1195363/232598685-d93d37bf-4f91-4700-ae38-f3c75663bb10.png">

Group reference, when clicked (this should be the group detail/preview):

<img width="723" alt="Screenshot 2023-04-17 at 4 07 17 PM" src="https://user-images.githubusercontent.com/1195363/232598690-9e93b756-8a85-44d8-a43f-168e9a06fcb1.png">

Presumably the state of the group-being-joined's row in the sidebar:

<img width="426" alt="Screenshot 2023-04-17 at 4 07 07 PM" src="https://user-images.githubusercontent.com/1195363/232598691-9b0aa3b6-ecb8-42b4-ba31-3a4062451148.png">

Group reference appearance in chat:

<img width="514" alt="Screenshot 2023-04-17 at 4 06 58 PM" src="https://user-images.githubusercontent.com/1195363/232598692-bcaf134d-97e1-49d8-bb9f-a7e6dc2252f8.png">

**Comment by mnrrxyz** [comment]
I can also add this image. This is while trying to look for ~natnex-ronret on the “Find groups” tab. It is stuck loading.
![SC 2023-04-17 at 22 31 44](https://user-images.githubusercontent.com/34553383/232646416-7b619888-a397-4ab8-a892-9a110e164fc5.jpg)
