### ISSUE TITLE
talk/groups: getting "has been updated in the background please reload" very frequently

### ISSUE THREAD

**Issue by tinnus-napbus** [tloncorp/landscape-apps#2328]
**Describe the bug, optionally with screenshots**
I get the "talk/groups has been update in the background" banner very frequently, at least every day and often multuple times per day. I doubt there have actually been that many updates, even if I'm on the dev stream. Also it's happening when I first open it which shouldn't be necessary - I assume it only happens if the update occurs while it's already open

**To Reproduce**
1. Go to talk/groups
2. wait ???? time
3. see update/reload banner

**Expected behavior**
should only see that banner when it's actually been update & only when it's happened while it's open

**Additional context:**
- Ship type: planet
- Instance type: self-hosted
- OS/browser: qutebrowser/chromium on linux

```
> +vat %groups
/sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415] [%zuse 414]
base hash:        0v5.eqi5j.j2ije.8s8s2.35vc0.p9ac0.io4jn.c00sv.0j1td.72b2g.vfgku
%cz hash:         0v5.eqi5j.j2ije.8s8s2.35vc0.p9ac0.io4jn.c00sv.0j1td.72b2g.vfgku
app status:       running
force on:         ~
force off:        ~
publishing ship:  [~ ~sogryp-dister-dozzod-dozzod]
updates:          remote
source ship:      ~binnec-dozzod-marzod
source desk:      %groups
source aeon:      129
kids desk:        ~
pending updates:  ~
> +vat %talk
/sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415] [%zuse 414]
base hash:        0v1u.uft2u.3dp8d.26t7o.3bqgs.0b0h9.g3p9a.7fsa7.v8tfr.8m2lh.ufd18
%cz hash:         0v1u.uft2u.3dp8d.26t7o.3bqgs.0b0h9.g3p9a.7fsa7.v8tfr.8m2lh.ufd18
app status:       running
force on:         ~
force off:        ~
publishing ship:  [~ ~sogryp-dister-dozzod-dozzod]
updates:          remote
source ship:      ~binnec-dozzod-marzod
source desk:      %talk
source aeon:      121
kids desk:        ~
pending updates:  ~
```

**Comment by arthyn** [comment]
we actually do deploy this much lol. however, something that exacerbates it is that you have to hit it twice because of the service worker and we need to fix that.
