### ISSUE TITLE
chat: Ability to restrict scrollback for new users based on join date/time.

### ISSUE THREAD

**Issue by patosullivan** [tloncorp/landscape-apps#2330]
Right now, all new users have access to the full scrollback for a chat as soon as they join the channel. This is not ideal for situations where scrollback could include sensitive information. We should allow admins to set whether or not new users will get access to the full scrollback for chat channels or just new messages going forward from the time they joined.

This could be set on either the group level or the channel level, I imagine.

**Comment by urcades** [comment]
@patosullivan I've provided 2¢ on how to surface this feature at the group level (#2348) if we end up deciding this is an important feature to implement. My visualization of it is contingent on updates to the overall Group Settings interface.

I think we can keep it simple for now, but I can totally see this feature adopting more granular control in the future.
