### ISSUE TITLE
Copy Group Link broken in Groups UI

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/landscape-apps#2346]
**Describe the bug, optionally with screenshots**
The copy group link action in the upper left Groups nav is not populating the copy-paste buffer. 

**To Reproduce**
1. Copy text into copy-paste buffer
2. Click upper left Groups nav to open menu
3. Click "Copy Group Link"
4. Paste in a DM
5. Previously copied text from step 1 is still in buffer

**Expected behavior**
The Landscape-friendly Group link should be pasted.

**Additional context:**
Currently synced to marnec

**Comment by patosullivan** [comment]
Which browser was this in?

**Comment by lukestiles** [comment]
I can repor on Safari on Mac. But not Chrome.
