### ISSUE TITLE
talk: unread message/thread-reply bugs

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#2349]
I'm observing some persistent issues with how we render/calculate unread messages and replies, particularly with respect to the behavior of the "unread messages banner" and inline time/new message separator(s).

These issues come most frequently in the form of confusing semantic collisions between a) the **labeled** number of "new messages" (5) that have been recorded, b) the **actual** number of messages that have been written to a talk channel (10+), and c) the **total count of replies** to a thread (13), of which only a) labeled number (5) are actually unread:

<img width="1089" alt="Screenshot 2023-04-19 at 9 36 10 PM" src="https://user-images.githubusercontent.com/1195363/233236144-e7a362ef-7e96-4074-b63d-0e6f8b5273fd.png">

and plainly incorrect "new message" counts:

<img width="1050" alt="Screenshot 2023-04-19 at 9 37 00 PM" src="https://user-images.githubusercontent.com/1195363/233236295-0f5c70ca-1f80-4e93-9c2e-9257bf7f0c0c.png">

I've already recorded the issues I have with date/time/new message separators and how to fix them here: #2217 

In evaluating the issues with our approach for a few weeks, I've concluded that we need to first **completely omit** thread replies/comments from the "unread messages" banner being rendered at the root channel level.

The primary intent for the "New Message" banner was to cleanly/simply represent the number of messages posted to a **linear channel** that you've missed since last visiting the channel. Originally, this feature was designed to account for the **explicitly linear** quality of Talk channels, which Threads break completely.

As non-linear + arbitrarily branched structures, it's incredibly difficult to represent the number of threads that might be offshooting from a primary scroll, and this makes representing the nature of "what's linearly unread" difficult. Should threads you haven't participated in be incrementing your unread messages count? If you've read an entire channel, but someone's started a thread 500 messages back, does it make sense to render a "1 message unread" notification against a massive backscroll?

I think we need to surface an explicit interface for triaging unread threads or other branching/recursing message types. We might need an explicit "Threads Inbox", or surface a new section in "Group Activity" dedicated to grouping threads I've participated in, but to start, we just need to omit replies/threads from rendering in talk channel unread banners.

**Comment by patosullivan** [comment]
+1 threads inbox, definitely needs to happen. me, james, and hunter were talking about making this part of the threads/replies overhaul.

**Comment by jamesacklin** [comment]
Additionally, from @lukestiles:

The new message notification banner scrolls indefinitely. This is intermittent. 

https://user-images.githubusercontent.com/1903610/234132857-e53a4ea0-fbc8-46ff-9c1c-7eb4434d6056.MOV

**To Reproduce**
Steps to reproduce the behavior:
1. Go to a channel that has unread messages. 
2. Click on blue notification banner 
3. Scroll up. Click again, and again. 
4. Never make it to the message 

**Expected behavior**
Clicking the notifications banner should take you the unread message and no farther.

**Comment by patosullivan** [comment]
Similar to #1723 , this most likely can't be fixed until we revamp the way threads/replies work on the backend.

As for the issue you posted @jamesacklin , we should probably split that out into a separate issue.

**Comment by urcades** [comment]
This issue is also related to the problems observed in #1075
