### ISSUE TITLE
talk: update message row components in DMs to support all actions

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#2360]
Currently, direct messages and group direct messages only support the following message actions:

1. Reacts
2. Threads

![Screenshot 2023-04-21 at 5 14 00 PM](https://user-images.githubusercontent.com/1195363/233735701-eae9383c-f565-4320-ada7-4fb2539a1c99.png)

We should update these messages to afford for the entire breadth of actions available to Talk messages:

![Screenshot 2023-04-21 at 5 14 29 PM](https://user-images.githubusercontent.com/1195363/233735761-06f3b074-3cf3-448e-a7c4-62824798b7f1.png)

1. Reacts
2. (Direct) Replies
3. Threads
4. Copy Reference

**Comment by jamesacklin** [comment]
We don't support replying (quick copy/insert) or copying a reference in a DM won't work because nobody hosts the DM, so there's no canonical endpoint for it. It lives on your ship.

@arthyn Am I correct?

**Comment by urcades** [comment]
Hm, that makes sense conceptually — would it be possible to "fake" the copying of a reference in a chat, in the sense that we change the underlying functionality of DM message rows to reference data on your own ship?

Even if this is weird in practice (from a technical POV), I think in this case it's important to keep that conceptual parallelism between all instances of Talk intact: I don't think the average person will care that DMs are "true" p2p and thus replying doesn't work as it does in Group Talk channels, they'll just observe that the ability to reply to someone's post in a DM is unavailable for no apparent reason.

**Comment by urcades** [comment]
fwiw, I don't think this is necessarily a high-leverage or "broken" thing we need to fix asap, it's just an observation that we can stand to smooth over some of the moments of technical implementation that end up producing gaps in the total experience of our products

**Comment by jamesacklin** [comment]
Understood. We do want to refactor the message type to accommodate better thread structuring. We will likely bake "reply" associations in to the message type and therefore make top-level replies work as expected in DMs (without the present-day reference quick-paste hack).
