### ISSUE TITLE
groups new message notification banner scrolls indefinitely

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/landscape-apps#2373]
**Describe the bug, optionally with screenshots**
The groups new message notification banner scrolls indefinitely. This is intermittent. 

https://user-images.githubusercontent.com/1903610/234132857-e53a4ea0-fbc8-46ff-9c1c-7eb4434d6056.MOV

**To Reproduce**
1. Go to a channel that has unread messages. 
2. Click on blue notification banner 
3. Scroll up. Click again, and again. 
4. Never make it to the message 

**Expected behavior**
Clicking the notifications banner should take you the unread message and no farther. 

**Additional context:**
- planet
- digital ocean 
- chrome on iOS

**Comment by jamesacklin** [comment]
Captured in #2349
