### ISSUE TITLE
Receiving 'Groups updated please refresh' on new launch

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/landscape-apps#2374]
**Describe the bug, optionally with screenshots**
After launching Groups fresh from grid I saw 'Groups updated please refresh'. I refreshed, and got the banner a second time. After refreshing once more I no longer saw the banner. 

This is a self-hosted planet synced to marzod on iOS chrome.

**Comment by jamesacklin** [comment]
Should be fixed by #2344. Pre-v3.0.0, you had to update once for the service worker and once more for the bundle.
