### ISSUE TITLE
lure: links for private and secret groups fail to join

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#2385]
- Enable lure links for a private or secret group
- Attempt to join the group via the link (either with a new ship or with an existing patp)
- Observe that you get the invite
- Observe that clicking join on the invite causes an infinite spinner with "wait a sec"
- Observe the group appear in the sidebar with an error about being unable to join possibly due to incompatible versions.

@jamesacklin and @arthyn suspect they know the reason for this failure, there's an extra step required of lure for private and secret groups, CC: @midsum-salrux.

This may also be related to #2384

**Comment by midsum-salrux** [comment]
https://github.com/tloncorp/landscape-apps/pull/2387
