### ISSUE TITLE
groups: notify user on completion of long-running join action

### ISSUE THREAD

**Issue by dnbrwstr** [tloncorp/landscape-apps#2412]
We should send a notification when long-running group joins complete in order to re-engage users if they've gotten distracted or lost interest in the interim.

Implementation is up for grabs, but the heuristic for "long-running" could be any or all of:

- Installation has taken more than 1 minute
- Tab has entered background
- User has navigated away from dashboard

**Comment by patosullivan** [comment]
Hard to see how we could do this without adding some new state on the backend, unless we just always notify a user when a group join is successful. Do we want to go through the former or just do the latter? @arthyn @jamesacklin

**Comment by arthyn** [comment]
if we only did a timer then this could be done without state, but per phil's explicit state jihad, we probably should just make state for this anyway so we could do it with timers or other conditions.

**Comment by jamesacklin** [comment]
What's available to modulate the frequency of this notification? It might get annoying if the timeout threshold is set too low or our conditions are too liberal. I agree that it's worth doing in general.
