### ISSUE TITLE
groups: initial load improvements

### ISSUE THREAD

**Issue by dnbrwstr** [tloncorp/landscape-apps#2413]
### Collapse differences between "waiting for host" and "downloading content"

Right now, groups whose hosts cannot be contacted are grayed-out in the sidebar and cannot be opened, while groups that can be contacted but are still loading can be opened, but to a blank group.

Instead, in either state, a group that is not fully initialized should be grayed out in the sidebar, but openable.

### Add loading indicator to initial group state

Right now, it's not clear what's happening while a group is loading. We should add a loader and status text to indicate what's going on.

![Image](https://user-images.githubusercontent.com/357216/234681370-2f539311-4a95-4a16-9aba-d0781cd3abc2.png)

https://www.figma.com/file/lPb6AIjQbg6ECbhxc6vXer/2023-Q2-Onboarding?node-id=184-19781&t=My1PDbEoTnS6S6yn-11

**Comment by patosullivan** [comment]
Part two of this one is done
