### ISSUE TITLE
groups: "host offline" state for join flow

### ISSUE THREAD

**Issue by dnbrwstr** [tloncorp/landscape-apps#2414]
> Requires peer availability implementation

If we're unable to contact a group's host, or to finish loading its content because the host is offline, we should reflect that in the load state.

Host availability unknown:

![Image](https://user-images.githubusercontent.com/357216/234691182-3c44d8e5-e87f-4608-b342-f883f0c2aae5.png)

Host offline:

![Image](https://user-images.githubusercontent.com/357216/234691183-c007b96b-de4e-4af6-bf47-1603524fb2fb.png)

For discussion: how's this copy? Do we want to cover other states here?

**Comment by urcades** [comment]
One additional state we might want to cover: 

If your urbit has received/synced the contents of a group prior to its host/owner going offline, you may be able to see the contents of a group, without being able to post new content to any of a group's channels.

We might need to consider a channel header or group sidebar state that indicates that the host is offline, even if you can see a group's contents.

**Comment by urcades** [comment]
The problems surfaced in issue #1920 are intertwined with this issue — they should be considered jointly + as one cohesive design pass.
