### ISSUE TITLE
apps: copying  references to messages appears to be broken

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#2417]
Check the video for a reproduction of this issue:

https://user-images.githubusercontent.com/1195363/234759818-9c43471e-bbe7-44f9-b755-725dafb3e613.mov

I'm not able to copy references of notebook posts or gallery blocks as well.

Seeing this on `Chromium Engine Version 112.0.5615.137`

Edit: This is broken on Safari `Version 16.4 (18615.1.26.11.23)` as well: 

https://user-images.githubusercontent.com/1195363/234760639-09a1dfbb-947e-449d-ab7d-9c1ab81850eb.mov

**Comment by patosullivan** [comment]
Are you still able to repro? I remember seeing this at some point but can't repro now.

**Comment by bonbud-macryg** [comment]
I'm seeing this too on:

macOS Ventura 13.3.1
Arc Version 0.101.2 (38549) (Chromium Engine Version 112.0.5615.137)
Safari Version 16.4 (18615.1.26.11.23)

**Comment by urcades** [comment]
I'm still seeing this issue, when I check out devtools, I see this:

<img width="202" alt="Screenshot 2023-05-09 at 1 57 32 PM" src="https://github.com/tloncorp/landscape-apps/assets/1195363/bdce891c-dd82-4cc4-ba92-0b4a5a856fad">

<img width="532" alt="Screenshot 2023-05-09 at 1 57 40 PM" src="https://github.com/tloncorp/landscape-apps/assets/1195363/e89b7f83-f775-4b69-8bc0-d57f4bf455a5">
