### ISSUE TITLE
lure: group host should check connectivity to lure service when creating lure link

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#2425]
If a group host cannot communicate with the lure service, the following can happen:
 - Group host creates lure link for their group
 - They share that link to users
 - Users click that link and end up at a "group not found page"

This happens because the lure service (currently hosted by us on ~loshut-lonreg) does not have the metadata for the lure link because the user's group host ship cannot communicate with it (recently this was because a bunch of galaxies were offline).

Proposal:
 - When a user enables the lure link, the system should check for connectivity to the lure service (which is set in the landscape settings).
 - If the group host cannot contact the lure service, it should throw a red warning in the UI and tell the user the lure link could not be created because the lure service was not accessible.

@midsum-salrux I though you'd be a good candidate for this one, but feel free to pull @tomholford in for any help with the UI warning bit.

Also if you have a better proposal for this that's great too (this was just my first thought).

This was one of the things that came out of the discussion about how to avoid edge cases with lure failures (we'll share the doc broadly).

**Comment by midsum-salrux** [comment]
This all makes sense. We track whether we've gotten a poke-ack from the bait service already, so we can just expose this in the UI.

**Comment by jamesacklin** [comment]
Happy to pull this in for 3.1.0 if it's not a lot of investigative effort

**Comment by zalberico** [comment]
Reopening this since we've seen it not work.

**Comment by zalberico** [comment]
Latest is in https://github.com/tloncorp/landscape-apps/pull/2444 - it sounded like it was on binnec/marnec but not yet deployed? I asked some questions on that PR

**Comment by zalberico** [comment]
I think we're good - closing out based on the questions answered in the PR.
