### ISSUE TITLE
Channel list blank on mobile web

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/landscape-apps#2440]
**Describe the bug, optionally with screenshots**
https://user-images.githubusercontent.com/1903610/235325270-e8390e72-a7ef-4fd7-b70f-8580777a38e5.MOV

**To Reproduce**
1. Load Groups Channels view in Talk on mobile web
2. Click on a channel
3. Exit channel back to list view
4. View is blank

**Additional context:**
- self-hosted planet
- chrome on iOS

**Comment by jamesacklin** [comment]
Unable to reproduce, are you sure you're running the latest with a clear cache?

https://user-images.githubusercontent.com/748181/235327395-c49ac849-c31b-4467-a676-54eb927d82a4.MOV

**Comment by lukestiles** [comment]
I can't repro reliably. I'll update or re-ticket if I can.
