### ISSUE TITLE
Suggested groups not rendering properly in group selection menu

### ISSUE THREAD

**Issue by ashelkovnykov** [tloncorp/landscape-apps#2449]
**Describe the bug, optionally with screenshots**
Sometimes, the entries in the groups selection menu for the suggested groups won't render correctly:
![example](https://0x0.st/HPxE.png)
If I click on those three blank entries, I'll be taken to the UF, door.link, and Tlon Local groups, respectively.

**To Reproduce**
1. Sync to `%group` `soon` (aka from `~marnec-dozzod-marzod`)
2. Go to `%groups`
3. See error

**Expected behavior**
All groups in the menu should render correctly.

**Additional context:**
- Ship type = planet
- Instance type = self-hosted
- Chromium-based browser on Pop!_OS 22.04

**Comment by jamesacklin** [comment]
Still seeing this?
