### ISSUE TITLE
chat: expand bio shows on profile modal even when bio is not truncated

### ISSUE THREAD

**Issue by alecananian** [tloncorp/landscape-apps#2451]
**Describe the bug, optionally with screenshots**
"Expand Bio" button shows on a user's profile modal even if the bio text is short enough to not be truncated

<img width="262" alt="Screenshot 2023-05-01 at 8 54 15 PM" src="https://user-images.githubusercontent.com/1013230/235579040-220b8352-1e94-471b-84e4-d53452d11902.png">

**To Reproduce**
1. Click on a user with a short bio (e.g. Galen) to open their profile modal
2. Observe "Expand Bio" button is still visible

**Expected behavior**
"Expand Bio" button is only visible if bio was long enough to be truncated

**Additional context:**
- Tlon-hosted planet
- macOS 13.3.1, Chromium

**Comment by jamesacklin** [comment]
Thank you!
