### ISSUE TITLE
groups: group creation UX maladies

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#2455]
From #2023:

> When you ask a user to create a group they see this screen: (create group dialog) There's lots of problematic stuff here, the hex color selector, the paste/image, switching back and forth between those, the behavior without s3 support etc. This needs attention.

**Comment by jamesacklin** [comment]
@urcades Care to link the details in https://www.figma.com/file/QMM0PcJyuKWrXY2n4VpQp1/2023-Q2-Groups?type=design&node-id=376-43501 ?

**Comment by urcades** [comment]
I think this particular breakout from zach's initial issue is addressed here:

https://github.com/tloncorp/landscape-apps/issues/2466

**Comment by jamesacklin** [comment]
Closing in favor of #2466
