### ISSUE TITLE
groups: proliferate contact updates

### ISSUE THREAD

**Issue by arthyn** [tloncorp/landscape-apps#2467]
We need to add more ways that people can become subscribed to one another for contact updates. Additionally we probably should change the `%meet` action in %contacts to actually grab a one off version of someone's profile.

Potential places to add `%meet`:
- On group join
- On profile view, (changing from `%heed`)
- On discovery/search, like through find groups or rendering a reference from that particular ship
- On new post/message/etc from a ship

Potential places to add `%heed`:
- Group chat messages
- When I mention said person
- Small group joins? Maybe under 100 people? Unsure about this one.
- Adding or being added as a pal

FWIW it was intended for us to be subscribing to everyone that we can, but I'd like us to be cautious. Additionally it would be nice if we could come up with contact 'levels' and for now I feel that meet vs heed gives us a good differentiator.

**Comment by joemfb** [comment]
These profiles are public, for people on the network. Would it be viable for them to be public on the wire? If so, it'd be interesting to experiment with putting them in the new agent-scoped namespace in %gall (via `%grow`), and then retrieving them via over the new *fine* protocol (via `%tune`) -- both additions in 413. I'd be happy to help if that sounds viable.

**Comment by joemfb** [comment]
Right now `fine` is completely unencrypted, that's why I ask if it's ok for profiles to be *really* public. Seems like most usage patterns will have to wait for encrypted remoted scry.

**Comment by arthyn** [comment]
the biggest offenders right now are public group/channel previews which seem like they'd be ok being unencrypted but idk maybe worth discussion.
