### ISSUE TITLE
groups: blog post crashing tab

### ISSUE THREAD

**Issue by dnbrwstr** [tloncorp/landscape-apps#2532]
The "A Guide to Tlon Local" blog post in Tlon Local gets stuck in an infinite loop and crashes my browser tab. 

**To Reproduce**
1. Load the note `/1/chan/diary/~nibset-napwyn/getting-started/note/170141184506222794168127277754421870592` in Groups. On my hosted ship, the url is `https://solfer-magfed.tlon.network/apps/groups/groups/~nibset-napwyn/tlon/channels/diary/~nibset-napwyn/getting-started`
2. Scroll down
3. Observe that the browser tab freezes and eventually crashes.

**Additional context:**
- Tested on my hosted ship, synced from marnec
- Observed the same behavior in both Chrome and Safari.
- Tried poking around a bit, and it was hard to get introspection once the tab was stuck, but with some random sampling via pausing in debugger and looking at the call stack, it looks like it's stuck in a loop that involves `react-beautiful-dnd`.

**Comment by jamesacklin** [comment]
Duplicate #2526
