### ISSUE TITLE
chat: message metadata cramped in threads

### ISSUE THREAD

**Issue by alecananian** [tloncorp/landscape-apps#2575]
**Describe the bug, optionally with screenshots**
The message metadata row has become extra cramped in threads now when the author also has a role badge applied to them. See the screenshot for reference. The role badge also gets a scrollbar added to it when it shrinks:

<img width="365" alt="Screenshot 2023-06-01 at 7 47 02 PM" src="https://github.com/tloncorp/landscape-apps/assets/1013230/e28641c7-3bc5-40d5-b345-44f1d28494ba">

**To Reproduce**
1. Go to a threaded reply posted by an admin (e.g. /1/chan/chat/~nibset-napwyn/support/msg/~nocsyx-lassul/170.141.184.506.246.922.914.222.855.715.130.896.809)
2. Hover on the message metadata
3. Observe row doesn't have enough room for all the info in it

**Expected behavior**
Info is rendered in a line, or has some different design applied to it when in a thread

**Additional context:**
- Tlon-hosted planet
- macOS 13.3.1, Chromium

**Comment by jamesacklin** [comment]
It may be time to shuffle some of this extra metadata off into the hover state.

**Comment by alecananian** [comment]
The provided screenshot is of the hover state. There's some redundant info in there that could likely be adjusted ("Today" and the full date), and maybe role badges could be rendered on a different line. GitHub mobile example:

![Screenshot_20230602_074933_GitHub~2.jpg](https://github.com/tloncorp/landscape-apps/assets/1013230/55e1f309-81b0-405b-8aab-cec86c0ca817)
