### ISSUE TITLE
Roles: Channels that you don't have access to can still be seen if you don't have the requisite permissions

### ISSUE THREAD

**Issue by thelifeandtimes** [tloncorp/landscape-apps#2583]
**Describe the bug, optionally with screenshots**
Currently if you do not have a given role, you can still be aware of the existence of a channel to which you do not have access. This means that channel names and quantities are potentially leaked out to those who perhaps shouldn't know that said channel exists, or is named something that leaks info out beyond the walls of the channel. Limits the use cases of channel permissions.

**To Reproduce**
1. Go to Groups
2. create a group with custom roles and a bunch of channels
3. invite someone as a base level member
4. the first thing they see is all of the channels, even the ones for which they don't have read/write perms.

**Expected behavior**
I would expect one of the following:
1. (Acceptable) For channels that require a specific role to read/write, they should not be known/visible to users lacking a role with read permissions
2. (Ideal) Channels should optionally be able to be marked as secret/private/public same as how groups currently function.

**Additional context:**
- Ship type: all
- Instance type: all
- OS/browser: all

cc: @urcades re: role discussion stuff.

**Comment by thelifeandtimes** [comment]
Weird, as a note, after assigning a single role to a test ship (in addition to the default `member` role), the list of channels was paired down to the ones to which the test ship had been given permissions. Perhaps this just happens on initial group join for some reason?

**Comment by thelifeandtimes** [comment]
Additional expected behavior: Sections with channels exclusively for which a ship does not have access should not show up either. 

e.g.: no perms
<img width="1609" alt="image" src="https://github.com/tloncorp/landscape-apps/assets/82244264/f1587318-a028-4b06-9fad-8aaeffcf609a">

full perms:
<img width="1607" alt="image" src="https://github.com/tloncorp/landscape-apps/assets/82244264/bd8924a5-1f85-47ee-9abd-d05345ecf327">

**Comment by thelifeandtimes** [comment]
Relatedly, members with insufficient roles can see and get notifications that edits have been made to a channel they don't have access to. Again, this leaks information about channels that one might prefer are wholly private without having to do obscure naming schemas.

**Comment by jamesacklin** [comment]
Tracking internally as LAND-542

**Comment by jamesacklin** [comment]
Fixed by #2632
