### ISSUE TITLE
talk: can't switch from DM view to all messages view

### ISSUE THREAD

**Issue by tinnus-napbus** [tloncorp/landscape-apps#2606]
**Describe the bug, optionally with screenshots**

When I try switch it just goes back to DMs and the console says:

```
GET https://u.tinnus-napbus.xyz/~/scry/settings/desk/talk.json 404
```

I'm getting talk/groups/landscape from binnec btw

```
> +vats %garden %groups %talk
%garden
  /sys/kelvin:           [%zuse 413]
  base hash ends in:     nikb7
  %cz hash ends in:      nikb7
  app status:            running
  pending updates:       ~
::
%groups
  /sys/kelvin:           [%zuse 413]
  base hash ends in:     t68u4
  %cz hash ends in:      t68u4
  app status:            running
  pending updates:       ~
::
%talk
  /sys/kelvin:           [%zuse 413]
  base hash ends in:     v5lbf
  %cz hash ends in:      v5lbf
  app status:            running
  pending updates:       ~
::
```

**To Reproduce**
1. try switching from DM view to all messsages view
2. observe you're stuck in DM view
3. look in console

**Expected behavior**
should be able to switch to all messages view

**Additional context:**
- Ship type: planet
- Instance type: self-hosted
- OS/browser: linux/chromium

**Comment by arthyn** [comment]
we just did some deploy juggling to make sure, but can you ensure you're synced to ~mister-dister-dozzod-dozzod and have a hash of 2ldqa?

**Comment by jamesacklin** [comment]
Excellent. We seem to have had some strangeness with mismatches between garden and groups/talk versions.
