### ISSUE TITLE
chat: scrollable thread doesn't stay at the bottom

### ISSUE THREAD

**Issue by Fang-** [tloncorp/landscape-apps#2610]
I'm viewing a thread that has a Twitter embed at the top. It's just gotten long enough to necessitate scrolling. Whenever I get to the bottom of the thread (and the thread re-renders for whatever reason?) it caused my scroll position to jump up. Not fully, just some, enough to occlude the last message or two.

![un-scroll](https://github.com/tloncorp/landscape-apps/assets/3829764/48b8b79d-85e8-4694-a2e7-b220c832fc14)

Feel like there was a similar bug some time ago. Hadn't seen problems recently, but then this happened.

**Comment by Fang-** [comment]
Hint: just experienced this same issue for a normal chat (not inside a thread, but also with a Twitter embed higher up in scrollback), but only whenever the window did not have focus??

**Comment by jamesacklin** [comment]
Tracked internally as LAND-580.
