### ISSUE TITLE
Deleting all text in a notebook note when editing immediately replaces the original text

### ISSUE THREAD

**Issue by ashelkovnykov** [tloncorp/landscape-apps#2620]
**Describe the bug, optionally with screenshots**
If you select an existing notebook post for editing and delete all of the text (either with `ctrl + a` then `del` or one character at a time with `backspace`), once the last of the original characters is deleted, the entirety of the text from when you first started editing will be restored.

**To Reproduce**
1. Go to an existing note in a notebook channel
2. Click on 'edit'
3. Highlight all of the text
4. Press `del`
5. See error

**Expected behavior**
All text should be deleted

**Additional context:**
- Ship type = planet
- Instance type = self-hosted locally
- OS/browser = Chromium-based browser on Pop!_OS 22.04

**Comment by jamesacklin** [comment]
Fixed by #2629
