### ISSUE TITLE
group DMs: consistency issues

### ISSUE THREAD

**Issue by philipcmonk** [tloncorp/landscape-apps#2642]
Some of the deltas in `+club` do not commute, so if they happen "simultaneously", we can settle to different results on different ships.  For example:

- ~zod creates a group DM and invites ~nec
- ~zod sets the group DM's name to "~zod's name 1".  ~nec soon reflects this.
- ~nec sets the group DM's name to "~nec's name 2".  ~zod soon reflects this.
- So far so good.
- Shut down ~zod, then on ~nec set the group DM's name to "~nec's name 3".
- Shut down ~nec, then bring up ~zod again, and set the group DM's name to "~zod's name 3".
- Bring up ~nec again.
- Soon, they will talk to each and swap names.  ~zod will display the group DM's name as "~nec's name 3", and ~nec will display the group DM's name as "~zod's name 3".

It's pretty unclear to me what the right answer should be in this case.  For a real group, there's no issue, since the host determines the right answer.  However, group DMs are gossiped.

The general classes of solution are:
- Accept some amount of inconsistency.  After all, this applies primarily to metadata, and if it's wrong, you can just change the metadata again to get everyone who's online back in sync.
- Use CRDTs.  However, it's not obvious what's the least upper bound of two "set the metadata" updates without a monotonic revision number.
- Elect a leader, using something like Raft (assumes members of DM are trustworthy)
- If you can't use CRDTs and wanted to do it without trusting any members of the DM, you would need to post (hashes of) messages to a blockchain to get an ordering.

However, I don't have an answer to setting the metadata.  I believe there's also an issue for the member list of a group DM, where a ship could be invited, then uninvited, then reinvited, and if some ships are offline during the uninvitation, they may hear both invitations before the uninvitation, and so come to the conclusion that the ship is not meant to be invited after all.  This may be solvable by attaching a redundancy counter to invitations, so that we can count that there were two invitations and only one uninvation, so they must still be invited.

I ran into this while refactoring chat's data structures.  In particular, my work makes chat messages themselves into a CRDT, and reactions can be interpreted as having no conflicts if only the ship doing the reacting is making updates to them.

For metadata, I may just accept the inconsistency for now, since that matches the existing behavior.  Otherwise, I would be inclined to designate a leader suing something like Raft.

**Comment by jamesacklin** [comment]
Tracking internally as LAND-605
