### ISSUE TITLE
Messages Missing When Viewing Messages Made in Web App from SmallTalk or Vice Versa

### ISSUE THREAD

**Issue by ashelkovnykov** [tloncorp/landscape-apps#2653]
Issue created on behalf of @forfel-norfel

**Describe the bug, optionally with screenshots**
Sometimes, only some of the messages posted from the web app will be viewable in SmallTalk, or vice versa.

EXAMPLE 1:
*correct order:*
![correct order 1](https://nyc3.digitaloceanspaces.com/forfel-norfel/forfel-norfel/2023.6.24..11.24.06-Screen%20Shot%202023-06-24%20at%207.08.22%20AM.png)
![correct order 2](https://nyc3.digitaloceanspaces.com/forfel-norfel/forfel-norfel/2023.6.24..11.24.17-Screen%20Shot%202023-06-24%20at%207.06.24%20AM.png)

*incorrect order:*
![incorrect order](https://nyc3.digitaloceanspaces.com/forfel-norfel/forfel-norfel/JfCf8nywShf3.png)

EXAMPLE 2:
*posts:*
![posts](https://nyc3.digitaloceanspaces.com/forfel-norfel/forfel-norfel/pCLQHrDF6lVB.png)
*problem:*
![description of problem](https://nyc3.digitaloceanspaces.com/forfel-norfel/forfel-norfel/eXKCKHj9TgqN.png)

**To Reproduce**
1. Go to web app (preferably on mobile)
2. Make a bunch of quick posts
3. Open same group chat in SmallTalk

**Expected behavior**
All of the messages should be visible and in the correct order in both the web app and SmallTalk, regardless of from where they were posted.

**Comment by forfel-norfel** [comment]
Here's another example

![image](https://github.com/tloncorp/landscape-apps/assets/63629037/f47a20b2-2877-40e8-a58c-4d0dd568813e)

**Comment by forfel-norfel** [comment]
![B0DAAA41-AE05-41A9-89A9-7F8F2CAA7B3D](https://github.com/tloncorp/landscape-apps/assets/63629037/85636296-1574-4a22-93de-c4d5a40ebcf6)

**Comment by zalberico** [comment]
Small talk is dead - the ordering issues that appeared here are no longer related to the current app or backend (which we moved to in part to reduce this class of problem).
