### ISSUE TITLE
Can't invite to a Private group

### ISSUE THREAD

**Issue by vvisigoth** [tloncorp/landscape-apps#2672]
When I invite someone to a private group, the input doesn't seem to process anything.

After invite is sent, invitee reports not seeing invite and invitee doesn't appear on the Invited list.

@jamesacklin

**Comment by jamesacklin** [comment]
Can't reproduce this, unfortunately. If you don't mind, do you want to try debugging in a call this week (or sending me an invite)?

Inviter side:
<img width="847" alt="image" src="https://github.com/tloncorp/landscape-apps/assets/748181/f238aabf-be1e-4986-b8c7-0924004ed147">

Invitee:
<img width="892" alt="Screenshot 2023-07-03 at 12 07 05 PM" src="https://github.com/tloncorp/landscape-apps/assets/748181/a922ba49-9c54-4281-9f0f-02a8f53f90e8">
<img width="1191" alt="Screenshot 2023-07-03 at 12 07 29 PM" src="https://github.com/tloncorp/landscape-apps/assets/748181/1e9a8b0b-9ef1-4dfe-8874-e2518186a43e">

**Comment by vvisigoth** [comment]
HOld plz. Making sure host has latest.

**Comment by jamesacklin** [comment]
How are things looking?

**Comment by jamesacklin** [comment]
@vvisigoth Any progress?

**Comment by vvisigoth** [comment]
We can go ahead and close. It _seems_ like it was an issue of host ship being out of date. In any case, can't repro since an update, so ...
