### ISSUE TITLE
kicked from all talk channels, cannot rejoin

### ISSUE THREAD

**Issue by rcrdlbl** [tloncorp/landscape-apps#2723]
**Describe the bug, optionally with screenshots**
I seem to have left every talk channel in every group, attempting to re-join from the channel list just displays a "Retry" button.

**To Reproduce**
1. open talk
2. see no groups or DMs in the sidebar
3. open groups
4. go to a group with talk channels
5. go into channel list
6. attempt to join talk channel
7. see error

**Expected behavior**
talk channels work as normal

**Additional context:**
- planet
- self-hosted (digitalocean)
- macOS Safari

**Comment by jamesacklin** [comment]
Did this resolve itself?

**Comment by rcrdlbl** [comment]
yeah
