### ISSUE TITLE
Can view chat channel but cannot post.

### ISSUE THREAD

**Issue by sigilante** [tloncorp/landscape-apps#3033]
I can see the chat log in ~nattyv/native-planet but am unable to post any messages.  (This has been true since their migration to this point.)

I can `|hi ~nattyv` successfully, so it's not a straightforward connectivity problem.  I can enter and submit text in the chatbox but it never resolves to sent.  (One `>`, never `>>`)

On ~lagrev-nocfep (self-hosted on Linux):

```
> +vats %groups
%groups
  /sys/kelvin:           [%zuse 412]
  %cz hash ends in:      1d6ue
  app status:            running
  source ship:           ~bosdev-dozzod-marnus
  pending updates:       ~
::
> +vats %landscape
%landscape
  /sys/kelvin:           [%zuse 412]
  %cz hash ends in:      vdj46
  app status:            running
  source ship:           ~bosdev-dozzod-marnus
  pending updates:       ~
::
```

**Comment by sigilante** [comment]
(No other groups are affected, to my knowledge.)

**Comment by mrozanski** [comment]
Thanks for bringing this up, can you please confirm if this is till happening with the current version?

**Comment by sigilante** [comment]
It looks like it is now resolved!
