### ISSUE TITLE
groups: page doesn't load after recent OTA

### ISSUE THREAD

**Issue by jalehman** [tloncorp/landscape-apps#3085]
Opening groups (in incognito with fresh ship login, so no caching shenanigans afoot) fails to load a page.

Here's the console output:
<img width="1668" alt="Screenshot 2023-12-05 at 12 47 02 PM" src="https://github.com/tloncorp/landscape-apps/assets/550978/048d35ca-3f6a-429d-9d07-7e83c3b550c5">

Here's my `+vat` output for %groups.
<img width="1032" alt="Screenshot 2023-12-05 at 12 43 18 PM" src="https://github.com/tloncorp/landscape-apps/assets/550978/396df9c5-fd98-41ae-8a65-8c9f053fc51d">

I'm self-hosted. It's worth noting that I used to be pulling %groups from `~bosdev-dozzod-marnus`, originally encountered this issue 15 minutes after the [release](https://github.com/tloncorp/landscape-apps/releases/tag/v5.0.0) appeared on GH, and persisted after conclusion of `|install ~sogryp-dister-dozzod-dozzod %groups`.

**Comment by patosullivan** [comment]
Can you try clearing the cache and refreshing?

**Comment by patosullivan** [comment]
Actually, I mean you should open chrome dev tools, go to the "Application" tab and click "clear site data"

**Comment by jalehman** [comment]
There was no cache, because it was done in incognito mode.

**Comment by patosullivan** [comment]
Josh was synced to ~bitdeg for %landscape, seemed to cause a docket issue. Updated the source ship to ~mister-dister-dozzod-dozzod and it went away.

**Comment by Fang-** [comment]
Resolved out of band.

@jalehman's ship had the `%landscape` desk installed from `~bitdeg`, but that was a(n older?) version which was presumably not serving the glob correctly.
