### ISSUE TITLE
Unhandled message type: {"code":{"lang":"hoon","code":"?~  work  ~~"}}

### ISSUE THREAD

**Issue by thelifeandtimes** [tloncorp/landscape-apps#3258]
**Describe the bug, optionally with screenshots**
Clicked the Support chat channel on mobile (iOS) and got this error. 
1. Be on iOS
2. Click on Support chat channel in Tlon Studio group
3. See error

**Expected behavior**
See the chat channel. 

**Additional context:**
- Ship type: planet
- Instance type: self hosted
- OS/browser: Tlon iOS mobile app

**Comment by mrozanski** [comment]
https://github.com/tloncorp/landscape-apps/pull/3259
https://github.com/tloncorp/landscape-apps/releases/tag/v5.7.0
