### ISSUE TITLE
chat: difficult to differentiate similarly-named chat channels from Groups

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#496]
![image.png](https://images.zenhubusercontent.com/6245cc0024d90711bcf4ea06/9c928c01-a916-4459-ae00-8e2eabe1b4d6)

**Comment by zalberico** [comment]
I wrote this up in #1379 but we should have something to differentiate chats with the same name that originate from different groups. Many groups don't have an image and have the same name (often "General"). The origin group for the channel shown there in some way that looks nice would be useful (maybe small text in the lower right of the row?). I'm not sure what the solution is, but this is definitely a design problem.

**Comment by urcades** [comment]
Now that I think of it, we could normalize the titling across all rows in the Talk app if we also double-stack DMs with the @p they're associated with, but this generally results in sidebar spacing we'd need to completely revisit.

**Comment by urcades** [comment]
A related change to our channel representation in the header:

<img width="374" alt="Screenshot 2023-04-27 at 12 57 12 AM" src="https://user-images.githubusercontent.com/1195363/234763201-29b20d21-a7c5-436b-9987-17a6e6d07c00.png">

The idea is to mirror the group/channel context for group-scoped Talk channels, which will become more important if we explore sidebar compression/hiding, and addresses the pain point noted in #2264
