### ISSUE TITLE
groups: per-channel cordon

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#555]
For each channel, users need to be added to one of several roles:

- **Viewer**: can only read the channel's contents
- **Commenter**: can comment on items in the channel (add to thread but only on existing items)
- **Contributor**: can add items (write) to the channel, as well as edit/delete said items
- **Editor**: all of the above, plus edit and delete others' items

Group admin abilities supersede all of these permissions.

**Comment by jamesacklin** [comment]
Additional request in #1766

**Comment by jamesacklin** [comment]
Also implicated: #1572

**Comment by lukestiles** [comment]
Editor sounds like moderator in this context. </bikeshed>
