### ISSUE TITLE
group/chat: mark channel as read on scrollback/load/etc

### ISSUE THREAD

**Issue by nerveharp** [tloncorp/landscape-apps#600]
Use the intersection of the last unread + vscroller height to update the brief and mark the channel as read.

**Comment by rcrdlbl** [comment]
I'm having trouble reproducing this on the current master branch – @nerveharp could you try this again?

I think what might be missing is actually optimistic updating for the "mark read", and the lag on livenet is making it feel like it's not getting marked read (maybe?)
