### ISSUE TITLE
chat: edit my own already-sent messages

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#631]
I searched for this feature/proposal in zenhub and did not find it — It was suggested that we explore a quick take on editing existing messages:

<img width="4240" alt="Editing a Message" src="https://user-images.githubusercontent.com/1195363/185036070-98878bb6-1bd3-4052-8c6c-884aa3e43fb1.png">

"As a user, I'd like to be able to edit a message I sent in order to correct a typo or hide an embarrassing mistake."

1. Hover over an already-sent message to expose its action bar, and click "Edit Message" to turn the entire row into a mini-field.
2. As a quick/pro alternative, one can press the up arrow key to quickly edit their last note.

We could always surface "viewing a message's previous versions/edits" at a later date, but I think it's not necessary for implementing a message-editing feature.

Designs here: https://www.figma.com/file/mdozWm05YsYcUdmYcsWcLA/2022-Q2-Talk?node-id=1572%3A66408

**Comment by jamesacklin** [comment]
Closing in favor of #1740 (updated design).
