### ISSUE TITLE
groups/join: search autocomplete lists match at top and still includes match in the list below

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/landscape-apps#651]
**Describe the bug**
When searching for a user or group, the match is inserted at the top, and remains in the list below. 

**To Reproduce**
1. Search for ~nocsyx-lassul
2. Watch the list down select while typing the name
3. ~nocsyx-lassul appears as the top choice 
4. ~nocsyx-lassul also appears at the bottom of the list

**Expected behavior**
I would expect to only see the match once, either at the top of the list for easy selection or preselected in some other sort order in the full list. 

**Screenshots**
<img width="1515" alt="Screen Shot 2022-08-19 at 8 52 29 AM" src="https://user-images.githubusercontent.com/1903610/185658876-31c64792-1502-4a55-8c52-f3a5402ebaa4.png">

**Additional context:**
- Searching from ~famhut-wolpyx
- Digital Ocean self-hosted
- Chrome on Mac

**Comment by arthyn** [comment]
This isn't really a bug. This was only ever intended to be a ship search. Do we really need to do this?
