### ISSUE TITLE
groups/join: full group path not auto-completing

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/landscape-apps#652]
**Describe the bug**
When manually typing in the host ship and group name, the Shadow Tlon group doesn't appear until I hit enter. 

**To Reproduce**
1. Search for ~nocsyx-lassul/shadow-tlon
2. Watch the auto-complete
3. Finish typing and hit enter
4. Group appears below and is selectable

**Expected behavior**
I would expect the group to appear in autocomplete once search has enough information.

**Screenshots**
<img width="1515" alt="Screen Shot 2022-08-19 at 8 56 29 AM" src="https://user-images.githubusercontent.com/1903610/185659817-c32b4eae-0af6-4af9-a685-e2508615dee4.png">
<img width="1515" alt="Screen Shot 2022-08-19 at 8 56 33 AM" src="https://user-images.githubusercontent.com/1903610/185659871-0fc573aa-8e54-4fca-8626-08a62530392f.png">

**Additional context:**
- planet
- Digital Ocean self-hosted
- Chrome Mac OS

**Comment by patosullivan** [comment]
The search component here is ShipSelector, it can only search for ships or detect an input that looks like a group link. We would need to completely re-engineer this in order to achieve this UX.

**Comment by jamesacklin** [comment]
Fixed.
