### ISSUE TITLE
groups: "canceling a join" of a group that doesn't exist is broken

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#782]
**Describe the bug**
After attempting to join a nonexistent (or slow/offline) group, I can't use the provided interface to cancel the join

**To Reproduce**
1. Ask someone to invite you to a nonexistent or offline group, or attempt to join one with a random endpoint
2. Click on the pending group row in the sidebar
3. Try clicking 'cancel join' — If it doesn't work, you've repro'd the bug

**Expected behavior**
No matter the state of the join, or why it's persisting, I should be able to cancel out of a join by clicking this button once. This is one of those interfaces that can't feel fiddly — it needs to perform what it says on the label, or else it undermines the trust of the interface (this applies to all "cancel"-type actions)

**Screenshots**

https://user-images.githubusercontent.com/1195363/188934121-38843a65-949d-47dc-b946-fe606f18e83c.mov

**Comment by nerveharp** [comment]
I also experience this daily.
