### ISSUE TITLE
groups: significant UX issues with group creation

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#788]
**Describe the bug**
At the moment, groups creation is littered with a lot of small issues that compound into a larger issue of groups creation feeling needlessly baroque/heavy. 

Edit: While this isn't a demo path concern, it's still a rather core set of interfaces that we can stand to improve for a v1 release.

In the following video, I attempt to create a group:

https://user-images.githubusercontent.com/1195363/188939772-60ef5350-a206-4aec-8512-1cce18b5083f.mov

- At 4 seconds, we already begin to see some issues with the form field design: The insertion point isn't automatically inserted into the "Group Name" field — I should be able to immediately begin typing the moment this field appears
- At 0:29 seconds I attempt to create my group after naming it and granting it a description, only to run into a wall — while the interface (barely) makes it clear that setting an avatar is a required action, the fact that an avatar needs to be explicitly provided in order to proceed feels close to a dark pattern, or at least a needlessly halting one. The "avatar" field should default to the "Letter" + Color presentation, so that all I need to do to proceed is give my group a name
- At 0:35 seconds, when I click into the "Group Icon" field, and click out of it to reset the state  (an expectation), it doesn't work. I need to explicitly press the "X" button to clear the field
- At 0:39 seconds, when I finally select the "Choose fill color" option, the default "black" icon color apparently isn't enough to proceed. Even _after_ setting the color of the icon at 0:51, I can't proceed to create my group.
- It isn't until 0:59 where I finally realize that I need to edit my group's name in order to proceed — this is almost certainly a bug

It nearly takes a minute for me to simply proceed from setting my group's default information — this is pretty insane, and certainly a blocker in getting people to the result they actually expect. Moving onward:

- Selecting a Group's privacy level is pretty straightforward, nothing particularly wrong here
- At 1:11 we run into an interface that visually blocks you from proceeding unless you invite people to the group. I think this tertiary "Skip" pattern is an antipattern that detracts from an otherwise straightforward interface.
- At 1:20, I'm dumped into a blank "groups" screen, rather than the group I just created

Combined, the above issues make for a creation process that feels more difficult than it needs to be.

There are a few updates to the groups creation flow that are on the cusp of being formalized:

**Group Details:**

<img width="1440" alt="Frame 2429" src="https://user-images.githubusercontent.com/1195363/188954778-e9b16169-0b32-4248-923a-029accdf6f98.png">

**Group Privacy**

<img width="634" alt="Screen Shot 2022-09-07 at 2 46 20 PM" src="https://user-images.githubusercontent.com/1195363/188954599-e6b9ce55-fea6-41a7-ac9b-2a9ccda64a9d.png">

**Invite People**

<img width="543" alt="Screen Shot 2022-09-07 at 2 46 39 PM" src="https://user-images.githubusercontent.com/1195363/188954673-23adf13a-764c-49b1-8292-3a271dad465d.png">

<img width="636" alt="Screen Shot 2022-09-07 at 2 46 42 PM" src="https://user-images.githubusercontent.com/1195363/188954689-02e4841b-6d5f-4776-b2ea-407a716c3276.png">

The most dramatic + notable changes pertain to "**Group Details**", which has the most issues in my assessment, and "**Invite People**", which could be slightly updated for ergonomic reasons, and to eliminate the "Skip" pattern that feels indirect.

cc @jyng + @marisarow + @nerveharp  — tagging y'all because this is an example of one of the more significant updates we're proposing edits to, ~~that directly maps to demo path delivery~~. A flow that captures the minutiae of these edits is close to being complete.

Edit: This does not in fact get visited by Galen on the demo path, but it's still a significant part of the Groups interface that could use updating sooner than later, I feel.

**Comment by jamesacklin** [comment]
Please ensure the following:

1. State is saved if you click out of the modal
2. The @ps typed in via dropdown are not duplicated (see #651)
