### ISSUE TITLE
talk: no pinning for chat channels

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#801]
Refer to the video below. 

I can pin arbitrary 1:1 DMs and Groups DMs, but I cannot pin group channels:

https://user-images.githubusercontent.com/1195363/189013806-49283977-3113-40d9-8bb6-c205cd9616e8.mov

It appears as though no "options dropdown menu" is surfaced for "group channels" in the Talk app.

I'm about to write up a "dropdown unification" issue I'll link this issue to momentarily.

**Comment by nerveharp** [comment]
Needs back-end support.
