### ISSUE TITLE
chat: clicking accept on the DM invite, does not give me any visual feedback

### ISSUE THREAD

**Issue by jyng** [tloncorp/landscape-apps#879]
**Describe the bug**
clicking accept on the DM invite, does not give me any visual feedback. I see something about `modal: not open` in the console.
![Screen Recording 2022-09-14 at 5 04 20 PM](https://user-images.githubusercontent.com/9557907/190263129-c5806410-786f-426d-8c50-dc821ff4b861.gif)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context:**
- Ship type (comet/moon/planet/star/galaxy)
- Instance type (Tlon-hosted/self-hosted with Port/CLI)
- OS/browser (Safari on MacOS, Chrome on Windows, Firefox on Linux, etc.)

**Comment by rcrdlbl** [comment]
@jyng I'm having trouble replicating this going off the master branch – is this still happening for you?

**Comment by jyng** [comment]
Just tried repro with @rcrdlbl. Looks like this issue has been fixed.
