### ISSUE TITLE
group: joining a invite to a private group takes me to find groups

### ISSUE THREAD

**Issue by jyng** [tloncorp/landscape-apps#880]
**Describe the bug**
group: joining a invite to a private group takes me to find groups
![Screen Recording 2022-09-14 at 5 23 06 PM](https://user-images.githubusercontent.com/9557907/190265325-6904d15f-3356-4fe9-b9af-6b0cc4d13822.gif)

**Comment by rcrdlbl** [comment]
@jyng Can you try this one again? I can't reproduce it locally.
