### ISSUE TITLE
chat: reactions should be additive

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#935]
Steps to reproduce:
1. Add a reaction to a chat message
2. Add _another_ reaction to a chat message using a different emoji
3. Observe the loss of your first reaction and the addition of this new emoji

Expected behavior:
Reactions should be additive -- selecting more than one emoji should add multiple reactions (look to Slack or Discord for inspiration).

**Comment by patosullivan** [comment]
It looks like this requires a backend change. @arthyn is that right?

**Comment by arthyn** [comment]
It does yeah

**Comment by jamesacklin** [comment]
We decided that one reaction per user is a good pattern and prevents reaction spam. Make your one emoji count.
