### ISSUE TITLE
 garden: adjust object-fill for avatars in header to prevent squishing

### ISSUE THREAD

**Issue by nerveharp** [tloncorp/landscape-apps#938]
This should be a perfect circle:
![image.png](https://images.zenhubusercontent.com/6245cc0024d90711bcf4ea06/c367e2c7-2c23-447b-b01f-cf436b194690)

**Comment by arthyn** [comment]
shouldn't this be in urbit/garden

**Comment by nerveharp** [comment]
It should, just tracking here.
