### ISSUE TITLE
talk: various issues with posting new messages + virtual scroller behavior

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#965]
**Describe the bug**
I'm noting a handful of issues while posting to a channel in Groups:
1. As I post new messages, which are a day removed from prior messages, I'm not seeing a new day separator populate the chat scroll
2. As I a) post new messages while b) situated at the "bottom" of the scroll, I'm not "pinned" to the bottom of the scroll — I seemingly jump back in time to the last date separator, which happens on every new message sent (see video)

https://user-images.githubusercontent.com/1195363/193628063-299a7988-77d2-4f78-b826-18a6863a8b63.mov

**To Reproduce**
1. Go `~fabled-faster/interface-testing-facility` in nuGroups
4. Visit the "Spam Chat" channel
5. Post a message
6. If you observe any of the behavior I've mentioned above, you've replicated the bug

**Expected behavior**
1. I expect messages to display a new date separator when they're posted on a day after a message posted to a previous day
3. While satisfying the condition of "scrolled all the way to the bottom of a chat", I'd expect to remain positionally "pinned" to the bottom of the scroll while new messages are posted to the chat area

**Additional context:**
- Ship: planet (~fabled-faster)
- Instance type: Tlon-hosted
- MacOS Monterey — 12.6 (21G115)
- Safari — 15.6.1 (17613.3.9.1.16)

**Comment by jamesacklin** [comment]
Also appearing in @zalberico's testing:

> In channels with one message it often doesn’t show up or it shows up below the screen with weirdly broken scroll behavior (seen here my text is below the visible area and scroll pulls it up)
![image.png](https://images.zenhubusercontent.com/6245cc0024d90711bcf4ea06/56d4ea86-a1c3-44d8-8097-ed8ba9f25701)

> When clicking around between channels, the messages don’t always load (sometimes I just see a white page where the messages should be)

**Comment by jamesacklin** [comment]
Clicking away from a chat channel and back into it also positions my scrollback way above where I was (presumably when I opened the app, before others chatted more and increased the log length).

**Comment by jamesacklin** [comment]
Closed in favor of leaf issues.
