### ISSUE TITLE
Group privacy is broken

### ISSUE THREAD

**Issue by forfel-norfel** [tloncorp/landscape-apps#971]
I made a group and I believe I picked 'secret' originally while I was setting it up. The privacy mode currently shows 'private'. I want it to be public, but changing the setting to 'public' or 'secret' and clicking 'save' does nothing. The setting changes back to 'private' after a few seconds. I'm not sure if joining after being invited or approved works. Feel free to try joining to test that: /1/group/~forfel-norfel/dead-mall-club

This PUT gets a 204 ok response
<img width="1081" alt="Screen Shot 2022-10-03 at 11 52 19 PM" src="https://user-images.githubusercontent.com/63629037/193731160-e3084f17-2d05-4577-a491-45b225182815.png">

<img width="1720" alt="Screen Shot 2022-10-03 at 11 51 23 PM" src="https://user-images.githubusercontent.com/63629037/193731332-4e91549b-fab1-4268-b31e-cd4343578294.png">

This appears in dojo when I try to change the setting:
```
%groups: on-poke with mark %group-action
%diary: on-agent on wire /groups, %fact
%chat: on-agent on wire /groups, %fact
%heap: on-agent on wire /groups, %fact
```

The only obvious error is when the page originally loads

POST /apps/groups/groups/~forfel-norfel/dead-mall-club/undefined HTTP/1.1
[{"action":"delete"}]

which returns a 404.

I'm using Chrome if that matters.

**Comment by nerveharp** [comment]
In progress as #969
