### ISSUE TITLE
No groups info loads

### ISSUE THREAD

**Issue by critesjosh** [tloncorp/landscape-apps#972]
**Describe the bug**

I open groups and no content loads.

**To Reproduce**

1. Install groups 
2. Open it

**Expected behavior**
I expect to see a list of my groups 

**Screenshots**

![Screenshot_20221004-143132_EScape.jpg](https://user-images.githubusercontent.com/18372439/193897946-ab787a4b-4ec8-4d74-b082-ead6badd8149.jpg)

**Additional context:**
- planet
- self hosted
- android, escape app

**Comment by nerveharp** [comment]
Groups and Talk use completely new back-ends, they do not talk to %graph-store (old Groups, Escape). Think of this interim alpha period as a great do-over, or a temporary state that will be wiped on launch.

We will migrate all Groups data on final launch via OTA -- keep an eye on #573, #574, #520, and #572 for incoming PRs to see what will happen.
