### ISSUE TITLE
groups: channels "sticking" where they shouldn't be, within other groups

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#985]
**Describe the bug**
This is a very strange bug that I haven't been able to replicate more than once, but while rapidly switching between groups, I caught a bug in which a chat channel from "group A" stuck around on-screen after switching to "group B", with none of the channels in "group B" being highlighted — check the video below to see what I mean

**Expected behavior**
I basically expect the following:
1. When switching from one group to another, I do not expect _any_ channels from groups to intermix with one another, for any reason
2. While navigating "back" to the list of "All Groups", from any group, I expect the state of the screen to essentially revert to whatever Groups App screen I had been looking at prior (find groups, notifications, profile, etc.)
3. As an extension to point #2, I expect to likewise land in whatever channel I last accessed in a group I'm visiting. We should avoid "resetting" the state of the group view whenever possible, and if we somehow _need_ to reset the state of the group I last visited, we should place people in the "All channels" screen

**Screenshots**

In the following video, I start off in Notifications (which isn't visually highlighted in the sidebar), and click into **Interface Testing Facility** — after idling for a second, I click BACK to the list of All Groups, and into Landscapers, where the channel I was viewing in ITF is persisting.

https://user-images.githubusercontent.com/1195363/194224141-db48e210-081a-4cfc-a36b-581bc8ee1754.mov

**Additional context:**
- Ship: planet (~fabled-faster)
- Instance type: Tlon-hosted
- MacOS Monterey — 12.6 (21G115)
- Chromium Engine Version 106.0.5249.91

**Comment by nerveharp** [comment]
Related to #940
