### ISSUE TITLE
chat/talk: inline formatting inserts linebreak

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#987]
Steps to reproduce:
1. Type into the ChatMessage input
2. Insert some _italics_, maybe a **bold**, definitely [a link](https://tlon.io)
3. Press "Send"
4. Observe linebreaks (above) inserted on either side of the inline elements

![image.png](https://images.zenhubusercontent.com/6245cc0024d90711bcf4ea06/414f1730-d0c5-4b07-bb6b-1f84b5193e75)

![image.png](https://images.zenhubusercontent.com/6245cc0024d90711bcf4ea06/134f37fa-0f67-4c02-9d43-5e0b35e43285)

**Comment by nerveharp** [comment]
I think this is https://github.com/tloncorp/landscape-apps/blob/de44f7a0b54ae466efa0a48bb6ef6c08eb276d4c/desk/app/chat.hoon#L490, since stories themselves look like this:

```hoon
[ %story
    p
  [ p=~
      q
    ~[
      'testing '
      [%break ~]
      [%italics p=[i='a thing' t=~]]
      [%break ~]
    ]
  ]
]
```
